#### Librerias y Carga de Datos

Pero son Json por ende primero se cargan json y despues los convierto de data frame

- df1 -> licitaciones 
- df2 -> adjudicaciones

In [1]:
import pandas as pd
import json
with open("../data/licitaciones.json", "r", encoding="utf-8") as f:
    data = json.load(f)
with open("../data/adjudicatarios_licitaciones.json", "r", encoding="utf-8") as f:
    data_2 = json.load(f)

In [16]:
# Exploración de los datos Json data
type(data)
len(data)

72018

In [ ]:

data[0]

{'licitacion_id': '47e7d739e530e98c',
 'title': 'Servicios de mantenimiento de las casetas de las estaciones Minerva, Eva´s Consumo y Eva´s Regeneradas',
 'detail_url': 'http://www.madrid.org/cs/Satellite?op2=PCON&idPagina=1204201624785&c=CM_ConvocaPrestac_FA&pagename=PortalContratacion%2FPage%2FPCON_contratosPublicos&language=es&idConsejeria=1109266187224&cid=1354626779636',
 'updated': '2018-01-11T17:25:23.580+01:00',
 'expediente': '107/2014',
 'pais_codigo': '',
 'pais_nombre': '',
 'tipo_contrato_codigo': 'Servicios',
 'subtipo_contrato_codigo': '',
 'lugar_ejecucion': '',
 'lugar_ejecucion_codigo': 'ES300',
 'cpv_codes': '50000000',
 'organo_contratacion': 'Canal de Isabel II',
 'estado_codigo': 'ADJ',
 'fecha_publicacion': '2018-01-02',
 'procedimiento_codigo': '1',
 'sistema_contratacion_codigo': '',
 'importe_estimado': '170000',
 'importe_sin_impuestos': '170000',
 'importe_total': '',
 'forma_presentacion_codigo': '',
 'financiacion_ue_codigo': '',
 'financiacion_ue_nombre': '',
 'fuente_publicacion': 'BOCM;PCPCM – Perfil contratante',
 'tipo_tramitacion_codigo': '',
 'presentacion_desde': '',
 'presentacion_hasta': '',
 'presentacion_hora': '',
 'notice_types': 'DOC_CN;DOC_CAN_ADJ',
 'organo_dir3': '',
 'organo_nif': '',
 'org_hierarchy': 'Consejería de Presidencia, Justicia y Portavocía del Gobierno',
 'contrato_duracion': '2',
 'contrato_duracion_unidad': 'ANN',
 'ofertas_recibidas': '6',
 'pymes_ofertas': '',
 'pyme_adjudicada': '',
 'adjudicatario': 'ELABORACIONES INDUSTRIALES ELÉCTRICAS NORMALIZADAS, S.L.',
 'adjudicatario_nif': 'B82124025'}

In [3]:
print(data[0].keys())

dict_keys(['licitacion_id', 'title', 'detail_url', 'updated', 'expediente', 'pais_codigo', 'pais_nombre', 'tipo_contrato_codigo', 'subtipo_contrato_codigo', 'lugar_ejecucion', 'lugar_ejecucion_codigo', 'cpv_codes', 'organo_contratacion', 'estado_codigo', 'fecha_publicacion', 'procedimiento_codigo', 'sistema_contratacion_codigo', 'importe_estimado', 'importe_sin_impuestos', 'importe_total', 'forma_presentacion_codigo', 'financiacion_ue_codigo', 'financiacion_ue_nombre', 'fuente_publicacion', 'tipo_tramitacion_codigo', 'presentacion_desde', 'presentacion_hasta', 'presentacion_hora', 'notice_types', 'organo_dir3', 'organo_nif', 'org_hierarchy', 'contrato_duracion', 'contrato_duracion_unidad', 'ofertas_recibidas', 'pymes_ofertas', 'pyme_adjudicada', 'adjudicatario', 'adjudicatario_nif'])

In [4]:
#exploración de los datos Json data_2
type(data_2)
len(data_2)

71834

In [5]:

data_2[0]

{'licitacion_id': '47e7d739e530e98c',
 'expediente': '107/2014',
 'titulo': 'Servicios de mantenimiento de las casetas de las estaciones Minerva, Eva´s Consumo y Eva´s Regeneradas',
 'estado': 'Adjudicada',
 'fecha_publicacion': '2018-01-02',
 'tipo_contrato': 'Servicios',
 'organo_contratacion': 'Canal de Isabel II',
 'importe_total': '',
 'importe_sin_impuestos': '170000',
 'importe_estimado': '170000',
 'adjudicatario': 'ELABORACIONES INDUSTRIALES ELÉCTRICAS NORMALIZADAS, S.L.',
 'adjudicatario_nif': 'B82124025',
 'url': 'http://www.madrid.org/cs/Satellite?op2=PCON&idPagina=1204201624785&c=CM_ConvocaPrestac_FA&pagename=PortalContratacion%2FPage%2FPCON_contratosPublicos&language=es&idConsejeria=1109266187224&cid=1354626779636',
 'fuente_scraping': '',
 'observaciones_scraping': ''}

#### Exploración df1

In [6]:
df1 = pd.DataFrame(data)
df1.head()

,licitacion_id,title,detail_url,updated,expediente,pais_codigo,pais_nombre,tipo_contrato_codigo,subtipo_contrato_codigo,lugar_ejecucion,...,ofertas_recibidas,pymes_ofertas,pyme_adjudicada,adjudicatario,adjudicatario_nif,fecha_scraping,scraping_fuente_url,scraping_nota,scraping_fuente_tipo,scraping_observaciones
0,47e7d739e530e98c,Servicios de mantenimiento de las casetas de l...,http://www.madrid.org/cs/Satellite?op2=PCON&id...,2018-01-11T17:25:23.580+01:00,107/2014,,,Servicios,,,...,6,,,ELABORACIONES INDUSTRIALES ELÉCTRICAS NORMALIZ...,B82124025,NaN,NaN,NaN,NaN,NaN
1,8067895aa39046e4,Suministro de víveres varios (productos no per...,http://www.riojasalud.es/empresas/consulta-de-...,2018-01-11T14:05:39.875+01:00,15-3-2.01-0008/2018,,,Obras,,,...,2,,,AGUSTIN DOMINGUEZ RODRIGUEZ S.L.,B09491523,NaN,NaN,NaN,NaN,NaN
2,d3e2093ba2efe6b2,Realización de los trabajos de coordinación en...,https://contratacion.jcyl.es/web/jcyl/Contrata...,2018-01-09T14:26:54.157+01:00,A2017/009768,,,Servicios,,,...,1,,,"INGENIERÍA Y PREVENCIÓN DE RIESGOS, S.L.",,NaN,NaN,NaN,NaN,NaN
3,69059a070f8f4f39,Realización de los trabajos de coordinación en...,https://contratacion.jcyl.es/web/jcyl/Contrata...,2018-01-09T14:26:54.341+01:00,A2017/011022,,,Servicios,,,...,2,,,"INGENIERÍA Y PREVENCIÓN DE RIESGOS, S.L.",,NaN,NaN,NaN,NaN,NaN
4,34aa967d51ea4eff,Subministrament d'equipaments de xarxa inhalàm...,https://contractaciopublica.gencat.cat/ecofin_...,2018-01-03T08:27:58.940+01:00,CHV 12/17 GESP,,,Obras,,,...,1,,,"Servicios Microinformatica, S.A.",A25027145,NaN,NaN,NaN,NaN,NaN

In [7]:
df1.columns

Index(['licitacion_id', 'title', 'detail_url', 'updated', 'expediente',
       'pais_codigo', 'pais_nombre', 'tipo_contrato_codigo',
       'subtipo_contrato_codigo', 'lugar_ejecucion', 'lugar_ejecucion_codigo',
       'cpv_codes', 'organo_contratacion', 'estado_codigo',
       'fecha_publicacion', 'procedimiento_codigo',
       'sistema_contratacion_codigo', 'importe_estimado',
       'importe_sin_impuestos', 'importe_total', 'forma_presentacion_codigo',
       'financiacion_ue_codigo', 'financiacion_ue_nombre',
       'fuente_publicacion', 'tipo_tramitacion_codigo', 'presentacion_desde',
       'presentacion_hasta', 'presentacion_hora', 'notice_types',
       'organo_dir3', 'organo_nif', 'org_hierarchy', 'contrato_duracion',
       'contrato_duracion_unidad', 'ofertas_recibidas', 'pymes_ofertas',
       'pyme_adjudicada', 'adjudicatario', 'adjudicatario_nif',
       'fecha_scraping', 'scraping_fuente_url', 'scraping_nota',
       'scraping_fuente_tipo', 'scraping_observaciones'],
      dtype='object')

In [8]:
len(df1)

72018

In [9]:
df1.isnull().sum()

licitacion_id                      0
title                              0
detail_url                         0
updated                           13
expediente                         0
pais_codigo                       13
pais_nombre                       13
tipo_contrato_codigo               0
subtipo_contrato_codigo           13
lugar_ejecucion                   13
lugar_ejecucion_codigo            13
cpv_codes                          3
organo_contratacion               13
estado_codigo                      0
fecha_publicacion                 13
procedimiento_codigo              13
sistema_contratacion_codigo       13
importe_estimado                   8
importe_sin_impuestos              7
importe_total                      5
forma_presentacion_codigo         13
financiacion_ue_codigo            13
financiacion_ue_nombre            13
fuente_publicacion                13
tipo_tramitacion_codigo           13
presentacion_desde                13
presentacion_hasta                13
presentacion_hora                 13
notice_types                      13
organo_dir3                       13
organo_nif                        13
org_hierarchy                     13
contrato_duracion                 13
contrato_duracion_unidad          13
ofertas_recibidas                 11
pymes_ofertas                     13
pyme_adjudicada                   13
adjudicatario                      0
adjudicatario_nif                  1
fecha_scraping                 71833
scraping_fuente_url            72000
scraping_nota                  72005
scraping_fuente_tipo           72013
scraping_observaciones         72013
dtype: int64

#### Exploración df2

In [10]:
df2 = pd.DataFrame(data_2)
df2.head()

,licitacion_id,expediente,titulo,estado,fecha_publicacion,tipo_contrato,organo_contratacion,importe_total,importe_sin_impuestos,importe_estimado,adjudicatario,adjudicatario_nif,url,fuente_scraping,observaciones_scraping
0,47e7d739e530e98c,107/2014,Servicios de mantenimiento de las casetas de l...,Adjudicada,2018-01-02,Servicios,Canal de Isabel II,,170000,170000,ELABORACIONES INDUSTRIALES ELÉCTRICAS NORMALIZ...,B82124025,http://www.madrid.org/cs/Satellite?op2=PCON&id...,,
1,8067895aa39046e4,15-3-2.01-0008/2018,Suministro de víveres varios (productos no per...,Resuelta,2018-01-02,Obras,"Servicio Riojano de Salud, Gobierno de La Rioja",,67499.19,134998.38,AGUSTIN DOMINGUEZ RODRIGUEZ S.L.,B09491523,http://www.riojasalud.es/empresas/consulta-de-...,,
2,d3e2093ba2efe6b2,A2017/009768,Realización de los trabajos de coordinación en...,Resuelta,2018-01-02,Servicios,Consejería de Agricultura y Ganadería,,37333.72,37333.72,"INGENIERÍA Y PREVENCIÓN DE RIESGOS, S.L.",,https://contratacion.jcyl.es/web/jcyl/Contrata...,,
3,69059a070f8f4f39,A2017/011022,Realización de los trabajos de coordinación en...,Resuelta,2018-01-02,Servicios,Consejería de Agricultura y Ganadería,,26353.92,26353.92,"INGENIERÍA Y PREVENCIÓN DE RIESGOS, S.L.",,https://contratacion.jcyl.es/web/jcyl/Contrata...,,
4,34aa967d51ea4eff,CHV 12/17 GESP,Subministrament d'equipaments de xarxa inhalàm...,Resuelta,2018-01-02,Obras,Consorci Hospitalari de Vic,,26000,26000,"Servicios Microinformatica, S.A.",A25027145,https://contractaciopublica.gencat.cat/ecofin_...,,

In [11]:
df2.isnull().sum()

licitacion_id             0
expediente                0
titulo                    0
estado                    0
fecha_publicacion         0
tipo_contrato             0
organo_contratacion       0
importe_total             0
importe_sin_impuestos     0
importe_estimado          0
adjudicatario             0
adjudicatario_nif         0
url                       0
fuente_scraping           0
observaciones_scraping    0
dtype: int64

In [12]:
df2.shape

(71834, 15)

In [15]:
df1.shape

(72018, 44)

In [13]:
if df1.shape[0] == df2.shape[0]:
    print("✅ Ambos DataFrames tienen el mismo número de filas")
else:
    print("❌ Los DataFrames tienen diferente número de filas")

❌ Los DataFrames tienen diferente número de filas

In [14]:
print("Duplicados en df1:",
      df1["licitacion_id"].duplicated().sum())

print("Duplicados en df2:",
      df2["licitacion_id"].duplicated().sum())

Duplicados en df1: 0
Duplicados en df2: 0

### Revisar si las columnas son iguales o diferentes

In [17]:
# Columnas de cada DataFrame
cols_df1 = set(df1.columns)
cols_df2 = set(df2.columns)

# Columnas iguales
columnas_iguales = cols_df1.intersection(cols_df2)

# Columnas que están solo en df1
solo_df1 = cols_df1 - cols_df2

# Columnas que están solo en df2
solo_df2 = cols_df2 - cols_df1


print("=== Columnas iguales ===")
print(sorted(columnas_iguales))

print("\n=== Solo en df1 ===")
print(sorted(solo_df1))

print("\n=== Solo en df2 ===")
print(sorted(solo_df2))

=== Columnas iguales ===
['adjudicatario', 'adjudicatario_nif', 'expediente', 'fecha_publicacion', 'importe_estimado', 'importe_sin_impuestos', 'importe_total', 'licitacion_id', 'organo_contratacion']

=== Solo en df1 ===
['contrato_duracion', 'contrato_duracion_unidad', 'cpv_codes', 'detail_url', 'estado_codigo', 'fecha_scraping', 'financiacion_ue_codigo', 'financiacion_ue_nombre', 'forma_presentacion_codigo', 'fuente_publicacion', 'lugar_ejecucion', 'lugar_ejecucion_codigo', 'notice_types', 'ofertas_recibidas', 'org_hierarchy', 'organo_dir3', 'organo_nif', 'pais_codigo', 'pais_nombre', 'presentacion_desde', 'presentacion_hasta', 'presentacion_hora', 'procedimiento_codigo', 'pyme_adjudicada', 'pymes_ofertas', 'scraping_fuente_tipo', 'scraping_fuente_url', 'scraping_nota', 'scraping_observaciones', 'sistema_contratacion_codigo', 'subtipo_contrato_codigo', 'tipo_contrato_codigo', 'tipo_tramitacion_codigo', 'title', 'updated']

=== Solo en df2 ===
['estado', 'fuente_scraping', 'observaciones_scraping', 'tipo_contrato', 'titulo', 'url']

In [18]:
# Columnas comunes entre df1 y df2
columnas_comunes = list(set(df1.columns).intersection(set(df2.columns)))

# NA en df1 solo para columnas comunes
na_df1_comunes = df1[columnas_comunes].isna().sum().sort_values(ascending=False)

# NA en df2 solo para columnas comunes
na_df2_comunes = df2[columnas_comunes].isna().sum().sort_values(ascending=False)

print("NA en df1 - columnas comunes")
print(na_df1_comunes)

print("\nNA en df2 - columnas comunes")
print(na_df2_comunes)

NA en df1 - columnas comunes
fecha_publicacion        13
organo_contratacion      13
importe_estimado          8
importe_sin_impuestos     7
importe_total             5
adjudicatario_nif         1
adjudicatario             0
expediente                0
licitacion_id             0
dtype: int64

NA en df2 - columnas comunes
importe_total            0
adjudicatario            0
fecha_publicacion        0
expediente               0
adjudicatario_nif        0
importe_sin_impuestos    0
importe_estimado         0
licitacion_id            0
organo_contratacion      0
dtype: int64

In [ ]:
# Renombrar columnas para que tengan el mismo nombre
df1 = df1.rename(columns={
    "title": "titulo"
})

## Eliminar las columnas con muchos NA

In [ ]:
def resumen_na(df, nombre_df):

    resumen = pd.DataFrame({
        "columna": df.columns,
        "tipo_dato": df.dtypes.values,
        "nulos": df.isna().sum().values,
        "porcentaje_nulos": (
            df.isna().mean().values * 100
        ).round(2),
        "valores_unicos": df.nunique(dropna=True).values
    })

    resumen["dataset"] = nombre_df

    return resumen.sort_values(
        by="porcentaje_nulos",
        ascending=False
    )

In [ ]:
na_df1 = resumen_na(df1, "df1")
na_df2 = resumen_na(df2, "df2")

In [ ]:
na_df1[na_df1["porcentaje_nulos"] >= 95]

In [ ]:
na_df2[na_df2["porcentaje_nulos"] >= 95]

In [ ]:
cols_drop_df1 = [
    "scraping_fuente_tipo",
    "scraping_observaciones",
    "scraping_nota",
    "scraping_fuente_url"
]

df1 = df1.drop(columns=cols_drop_df1)

In [ ]:
df1.shape

### Comparar si las columnas son iguales en el contenido

In [ ]:
# Excluir la llave de comparación
columnas_comunes = [
    col for col in columnas_comunes
    if col != "licitacion_id"
]

resultado = []

for col in columnas_comunes:

    # Comparar columna entre df1 y df2
    temp = (
        df1[["licitacion_id", col]]
        .merge(
            df2[["licitacion_id", col]],
            on="licitacion_id",
            how="inner",
            suffixes=("_df1", "_df2")
        )
    )

    # Comparación normalizada
    iguales = (
        temp[f"{col}_df1"]
        .fillna("<<NA>>")
        .astype(str)
        .str.strip()
        .str.lower()
        .eq(
            temp[f"{col}_df2"]
            .fillna("<<NA>>")
            .astype(str)
            .str.strip()
            .str.lower()
        )
    )

    # Guardar resultados
    resultado.append({
        "columna": col,
        "total_registros": len(temp),
        "iguales": iguales.sum(),
        "diferentes": (~iguales).sum(),
        "porcentaje_igualdad": round(
            iguales.mean() * 100,
            2
        )
    })

In [ ]:
# Convertir a DataFrame
comparacion_columnas = pd.DataFrame(resultado)

# Ordenar resultados
comparacion_columnas.sort_values(
    by="porcentaje_igualdad",
    ascending=False
)

In [ ]:
df1.columns

In [ ]:
df2.columns

In [ ]:
df1.columns[df1.columns.duplicated()]

In [ ]:
df2.columns[df2.columns.duplicated()]

In [ ]:
na_df1 = (
    df1[columnas_comunes]
    .isna()
    .sum()
)

na_df1[na_df1 > 0]

In [ ]:
na_df2 = (
    df2[columnas_comunes]
    .isna()
    .sum()
)

na_df2[na_df2 > 0]

In [ ]:
df1_completado = df1.copy()

df2_indexado = df2.set_index("licitacion_id")

for col in columnas_comunes:

    df1_completado[col] = (
        df1_completado[col]
        .fillna(
            df1_completado["licitacion_id"]
            .map(df2_indexado[col])
        )
    )

In [ ]:
resultado = []

df1_sorted = (
    df1_completado
    .sort_values("licitacion_id")
    .reset_index(drop=True)
)

df2_sorted = (
    df2
    .sort_values("licitacion_id")
    .reset_index(drop=True)
)

for col in columnas_comunes:

    iguales = (
        df1_sorted[col]
        .fillna("<<NA>>")
        .astype(str)
        .equals(
            df2_sorted[col]
            .fillna("<<NA>>")
            .astype(str)
        )
    )

    resultado.append({
        "columna": col,
        "iguales_post_fillna": iguales
    })

comparacion_post = pd.DataFrame(resultado)

comparacion_post

In [ ]:
solo_df2 = list(
    set(df2.columns) - set(df1.columns)
)

solo_df2

In [ ]:
df_final = df1_completado.merge(
    df2[["licitacion_id"] + solo_df2],
    on="licitacion_id",
    how="left"
)

In [ ]:
df2.columns

# Eliminar filas SOLO DEJAR SERVICIOS

In [ ]:
df1["cpv_codes"].apply(type).value_counts()
df1["cpv_codes"].value_counts().head(50)
df1 = df1[
    df1["cpv_codes"]
    .astype(str)
    .apply(
        lambda x: any(
            codigo.startswith("851")
            for codigo in x.split(";")
        )
    )
].copy()
df1["cpv_codes"].astype(str).str.contains(";").sum()
df1["cpv_codes"].str.startswith("0").value_counts()

# --------------------- 
# --------------------- EDAD ---------------------------------
# ---------------------

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df_final.shape

In [ ]:
(
    df_final
    .isna()
    .mean()
    .sort_values(ascending=False)
    .head(30)
)

In [ ]:
na_por_columna = (
    df_final
    .isna()
    .sum()
    .sort_values(ascending=False)
)

na_por_columna[na_por_columna > 0]

In [ ]:
df_final[
    df_final.isna().any(axis=1)
]

In [ ]:
# ============================================
# INVENTARIO GENERAL DE VARIABLES - df_final
# ============================================

resumen_variables = pd.DataFrame({
    "columna": df_final.columns,
    "tipo_dato": df_final.dtypes.astype(str).values,
    "n_registros": len(df_final),
    "n_no_nulos": df_final.notna().sum().values,
    "n_nulos": df_final.isna().sum().values,
    "pct_nulos": (df_final.isna().mean() * 100).round(4).values,
    "n_unicos": df_final.nunique(dropna=True).values,
    "pct_unicos": (df_final.nunique(dropna=True) / len(df_final) * 100).round(4).values
})

resumen_variables = resumen_variables.sort_values(
    by=["pct_nulos", "n_unicos"],
    ascending=[False, False]
)

resumen_variables

In [ ]:
# ============================================
# EJEMPLOS DE VALORES POR COLUMNA
# ============================================

ejemplos_columnas = []

for col in df_final.columns:
    valores = (
        df_final[col]
        .dropna()
        .astype(str)
        .drop_duplicates()
        .head(5)
        .tolist()
    )
    
    ejemplos_columnas.append({
        "columna": col,
        "ejemplos": valores
    })

ejemplos_columnas = pd.DataFrame(ejemplos_columnas)

ejemplos_columnas

In [ ]:
# ============================================
# EXPORTAR INVENTARIO A EXCEL
# ============================================

with pd.ExcelWriter("inventario_variables_licitaciones.xlsx") as writer:
    resumen_variables.to_excel(writer, sheet_name="resumen_variables", index=False)
    ejemplos_columnas.to_excel(writer, sheet_name="ejemplos_columnas", index=False)

print("Archivo exportado: inventario_variables_licitaciones.xlsx")

- ¿Cómo se distribuyen las licitaciones?  
- ¿Qué tan concentrado está el mercado?  
- ¿Qué tamaños de contratos existen?  
- ¿Qué entidades contratan más?

In [ ]:
# Copia de trabajo
df_eda = df_final.copy()

# Dimensión general
print("Número de filas:", df_eda.shape[0])
print("Número de columnas:", df_eda.shape[1])
print("Número de licitaciones únicas:", df_eda["licitacion_id"].nunique())

In [ ]:
resumen_base = pd.DataFrame({
    "indicador": [
        "Total registros",
        "Licitaciones únicas",
        "Columnas disponibles",
        "Órganos de contratación únicos",
        "Adjudicatarios únicos",
        "CPV únicos"
    ],
    "valor": [
        df_eda.shape[0],
        df_eda["licitacion_id"].nunique(),
        df_eda.shape[1],
        df_eda["organo_contratacion"].nunique(),
        df_eda["adjudicatario"].nunique(),
        df_eda["cpv_codes"].nunique()
    ]
})

resumen_base

La base de datos consolidada utilizada en el proyecto está compuesta por 71.834 registros únicos de licitaciones públicas relacionadas con el sector salud, obtenidos a partir de información disponible en la Plataforma de Contratación del Sector Público de España. Este volumen de información representa una muestra suficientemente amplia para realizar análisis estadísticos, segmentaciones y procesos de caracterización del ecosistema licitatorio analizado. La ausencia de duplicados en la variable licitacion_id confirma la integridad estructural de la base y garantiza que cada registro corresponde a un proceso licitatorio independiente.

En términos de cobertura institucional, la base contiene información proveniente de 1.878 órganos de contratación distintos, lo que evidencia un entorno institucional amplio y heterogéneo dentro del conjunto de licitaciones recopiladas. Este hallazgo sugiere que las oportunidades de contratación analizadas no se concentran exclusivamente en una única entidad pública, sino que involucran múltiples organismos y niveles administrativos, aspecto relevante para la construcción de estrategias de priorización y segmentación institucional.

Adicionalmente, se identificaron 16.834 adjudicatarios únicos, reflejando una elevada participación de actores económicos dentro de la muestra analizada. Este comportamiento preliminar sugiere una estructura competitiva relativamente fragmentada, aunque posteriormente será necesario evaluar formalmente el nivel de concentración mediante indicadores estadísticos específicos. Desde una perspectiva estratégica, este resultado indica la posible existencia de nichos de mercado y oportunidades de especialización para clínicas privadas interesadas en participar en procesos de contratación pública.

Finalmente, la presencia de 6.605 códigos CPV únicos evidencia una alta diversidad de servicios y categorías contractuales dentro del conjunto analizado. Este aspecto resulta especialmente importante para el desarrollo del sistema de recomendación propuesto, ya que los códigos CPV constituyen un mecanismo estandarizado de clasificación de servicios públicos y permiten identificar áreas temáticas, niveles de especialización y compatibilidad potencial entre las capacidades operativas de una institución sanitaria y las características de las licitaciones disponibles.

In [ ]:
df_eda["importe_sin_impuestos"] = pd.to_numeric(
    df_eda["importe_sin_impuestos"],
    errors="raise"
)

In [ ]:
df_eda["importe_sin_impuestos"].describe(
    percentiles=[0.01, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
)

El análisis descriptivo de la variable importe_sin_impuestos evidencia una distribución altamente asimétrica y concentrada en licitaciones de bajo y mediano valor económico, acompañada por un conjunto reducido de procedimientos de importe extremadamente elevado. La diferencia entre la media (aproximadamente 896 mil euros) y la mediana (cerca de 66 mil euros) confirma la presencia de una fuerte asimetría positiva, indicando que un número reducido de licitaciones de gran magnitud incrementa considerablemente el promedio general del mercado.

El análisis por percentiles permite observar con mayor precisión esta estructura desigual. Mientras que el 50% de las licitaciones presentan importes inferiores a aproximadamente 66 mil euros, el percentil 75 se sitúa alrededor de los 267 mil euros y el percentil 90 supera el millón de euros. Adicionalmente, el percentil 95 alcanza aproximadamente 2,4 millones de euros y el percentil 99 supera los 12 millones. Finalmente, el importe máximo registrado supera los 1.700 millones de euros, evidenciando la existencia de valores extremos de gran magnitud económica.

En conjunto, estos resultados muestran que el mercado de licitaciones sanitarias no presenta una distribución homogénea del valor económico, sino una estructura fuertemente concentrada, donde una proporción reducida de procedimientos acumula una parte significativa del volumen económico total analizado.

Desde una perspectiva estratégica, este comportamiento tiene implicaciones relevantes para el desarrollo del sistema de priorización de licitaciones propuesto en el proyecto. La elevada dispersión económica sugiere que las oportunidades de contratación pública no son directamente comparables entre sí y que resulta necesario considerar segmentaciones por tamaño económico antes de construir mecanismos de recomendación o scoring. En términos prácticos, las licitaciones de gran magnitud podrían implicar mayores requisitos técnicos, financieros y operativos, así como niveles de competencia potencialmente superiores, mientras que las licitaciones pequeñas y medianas podrían representar oportunidades más accesibles para determinadas capacidades institucionales.

Metodológicamente, la presencia de asimetría extrema y valores atípicos implica que las siguientes etapas analíticas deberán incorporar transformaciones logarítmicas, métricas robustas y segmentaciones distributivas, evitando depender exclusivamente de medidas sensibles a valores extremos como la media aritmética.

In [ ]:
plt.figure(figsize=(10,5))

plt.hist(
    df_eda["importe_sin_impuestos"].dropna(),
    bins=50
)

plt.title("Distribución de importes")
plt.xlabel("Importe sin impuestos")
plt.ylabel("Frecuencia")

plt.show()

La distribución de los importes evidencia una fuerte concentración de licitaciones en valores económicos bajos y medianos, acompañada por una cola derecha extremadamente extensa. Visualmente, el histograma muestra una asimetría positiva severa, donde la gran mayoría de procedimientos se acumula cerca de los valores inferiores, mientras que un número reducido de licitaciones alcanza importes considerablemente superiores.

Este comportamiento es consistente con los resultados observados previamente en los percentiles y en la diferencia existente entre la media y la mediana. Las licitaciones de gran magnitud económica actúan como valores atípicos extremos que expanden significativamente la escala de la distribución y comprimen visualmente la mayor parte de las observaciones cerca del origen. Como consecuencia, la estructura interna del mercado no puede interpretarse adecuadamente utilizando únicamente escalas lineales o medidas tradicionales de tendencia central.

Desde una perspectiva metodológica, esta distribución sugiere que el mercado de contratación pública sanitaria no presenta un comportamiento homogéneo, sino una estructura económica compuesta por múltiples escalas de contratación coexistiendo simultáneamente. En términos prácticos, las licitaciones de bajo importe probablemente responden a dinámicas operativas y competitivas diferentes a las observadas en procedimientos de gran magnitud económica.

Adicionalmente, la presencia de una cola derecha pronunciada y de valores extremos justifica la necesidad de incorporar transformaciones logarítmicas y técnicas robustas de segmentación en las siguientes etapas analíticas. Estas metodologías permiten reducir el efecto distorsionador de las licitaciones atípicas y facilitan una interpretación más precisa de la estructura distributiva del mercado.

En conjunto, los resultados evidencian que el valor económico de las licitaciones no se distribuye de manera uniforme, sino que presenta una elevada concentración en un subconjunto reducido de procedimientos de gran magnitud económica, comportamiento característico de mercados complejos con alta heterogeneidad distributiva.

In [ ]:
df_eda["importe_log"] = np.log1p(df_eda["importe_sin_impuestos"])

In [ ]:
plt.figure(figsize=(10,5))

plt.hist(
    df_eda["importe_log"].dropna(),
    bins=50
)

plt.title("Distribución logarítmica de importes")
plt.xlabel("log(1 + importe_total)")
plt.ylabel("Frecuencia")

plt.show()

La transformación logarítmica permitió reducir significativamente el efecto de los valores extremos y visualizar de manera más clara la estructura subyacente de la distribución económica de las licitaciones. A diferencia del histograma original, donde las licitaciones de gran magnitud comprimían visualmente la mayoría de observaciones cerca del origen, la escala logarítmica genera una distribución considerablemente más extendida y analíticamente interpretable.

Este comportamiento sugiere que la distribución de los importes responde a dinámicas compatibles con procesos económicos de carácter multiplicativo, patrón frecuentemente observado en mercados complejos donde coexisten procedimientos de contratación de muy distinta magnitud económica. La transformación permite evidenciar que el mercado no está compuesto únicamente por licitaciones pequeñas acompañadas de algunos valores atípicos aislados, sino por múltiples escalas económicas intermedias distribuidas de forma continua.

Desde una perspectiva metodológica, este resultado resulta especialmente relevante para las siguientes etapas analíticas del proyecto, ya que justifica el uso de transformaciones logarítmicas, segmentaciones distributivas y técnicas robustas de análisis estadístico. La reducción del efecto distorsionador de las licitaciones de importe extremadamente elevado facilita comparaciones más estables entre procedimientos y mejora la interpretabilidad de futuras técnicas de clasificación, clustering y segmentación económica.

Adicionalmente, los resultados sugieren que las comparaciones entre licitaciones no deberían realizarse exclusivamente sobre valores monetarios absolutos, sino sobre escalas normalizadas o segmentadas por percentiles, evitando que los procedimientos de gran magnitud económica dominen completamente el comportamiento agregado de la distribución.

Desde una perspectiva estratégica, la coexistencia de múltiples escalas económicas dentro del mercado de contratación pública sanitaria refuerza la necesidad de desarrollar un sistema de priorización capaz de diferenciar oportunidades según su tamaño económico. Esto implica que organizaciones con capacidades operativas distintas podrían competir de manera más eficiente en segmentos específicos del mercado, en lugar de abordar el ecosistema licitatorio como un conjunto homogéneo de oportunidades.

In [ ]:
from scipy.stats import skew, kurtosis

In [ ]:
asimetria = skew(df_eda["importe_sin_impuestos"].dropna())

curtosis = kurtosis(df_eda["importe_sin_impuestos"].dropna())

print("Asimetría:", asimetria)
print("Curtosis:", curtosis)

In [ ]:
asimetria_log = skew(df_eda["importe_log"].dropna())

curtosis_log = kurtosis(df_eda["importe_log"].dropna())

print("Asimetría log:", asimetria_log)
print("Curtosis log:", curtosis_log)

El análisis estadístico de la variable importe_sin_impuestos evidencia que el conjunto de licitaciones analizado presenta una estructura económica extremadamente desigual y heterogénea. La distribución original mostró una asimetría positiva severa (82,78), indicando que la mayor parte de las licitaciones se concentra en importes relativamente bajos y medianos, mientras que un número reducido de procedimientos alcanza magnitudes económicas excepcionalmente elevadas. Este comportamiento confirma la existencia de una cola derecha extremadamente extensa, característica frecuente en distribuciones económicas complejas donde una pequeña proporción de licitaciones concentra una parte significativa del valor total observado.

Adicionalmente, la curtosis obtenida (9934,32) evidencia una presencia extremadamente elevada de valores atípicos y colas pesadas dentro de la distribución. En términos prácticos, esto significa que existen licitaciones de magnitud económica extraordinaria que distorsionan significativamente las medidas tradicionales de tendencia central y dispersión. Como consecuencia, estadísticas sensibles a valores extremos, como la media aritmética y la desviación estándar, no representan adecuadamente el comportamiento típico del mercado analizado.

Con el objetivo de estabilizar la distribución y mejorar su interpretabilidad analítica, se aplicó una transformación logarítmica sobre los importes. Los resultados posteriores muestran una reducción drástica tanto de la asimetría como de la curtosis. La asimetría pasó de 82,78 a aproximadamente -0,86, mientras que la curtosis disminuyó de 9934,32 a cerca de 1,80. Esto indica que la transformación logró reducir significativamente el efecto distorsionador de las licitaciones de importe extremadamente elevado, generando una distribución considerablemente más estable y adecuada para análisis estadísticos posteriores.

Desde una perspectiva metodológica, estos resultados justifican el uso de escalas logarítmicas, segmentaciones distributivas y técnicas robustas en futuras etapas del proyecto, incluyendo procesos de clustering, segmentación económica y construcción del sistema de scoring. Asimismo, evidencian que las licitaciones no deben analizarse como un conjunto homogéneo de oportunidades, sino como un ecosistema compuesto por múltiples escalas económicas coexistiendo simultáneamente.

En términos estratégicos, este comportamiento refuerza la necesidad de desarrollar mecanismos de priorización capaces de diferenciar licitaciones según su magnitud económica, ya que las capacidades operativas, financieras y técnicas requeridas para competir en procedimientos de gran escala probablemente difieren sustancialmente de aquellas necesarias para participar en licitaciones pequeñas o medianas.

In [ ]:
top_organos = (
    df_eda
    .groupby("organo_contratacion")
    .agg(
        n_licitaciones=("licitacion_id", "count"),
        importe_total_acumulado=("importe_sin_impuestos", "sum"),
        importe_promedio=("importe_sin_impuestos", "mean")
    )
    .sort_values(
        "importe_total_acumulado",
        ascending=False
    )
)

top_organos.head(20)

In [ ]:
top10 = top_organos.head(10)

plt.figure(figsize=(12,6))

plt.barh(
    top10.index.astype(str),
    top10["importe_total_acumulado"]
)

plt.title("Top 10 órganos por importe acumulado")
plt.xlabel("Importe acumulado sin impuestos")
plt.ylabel("Órgano de contratación")

plt.gca().invert_yaxis()

plt.show()

El análisis de los órganos de contratación evidencia una distribución institucional heterogénea dentro del conjunto de licitaciones analizadas. Tanto la tabla resumen como la representación gráfica muestran diferencias significativas en el volumen económico acumulado gestionado por los distintos organismos públicos presentes en la muestra. En particular, destacan entidades como el Servicio Andaluz de Salud, el Servicio Madrileño de Salud y la Consellería de Sanidade - SERGAS, cuyos importes acumulados superan ampliamente los valores observados en la mayoría de organismos restantes.

La representación gráfica permite identificar una caída pronunciada después de los primeros organismos del ranking, lo que sugiere una elevada concentración institucional del volumen económico analizado. Mientras algunos órganos acumulan miles de licitaciones y presupuestos multimillonarios, el resto presenta volúmenes considerablemente menores. Este comportamiento podría estar asociado tanto a diferencias en capacidad presupuestaria como al tamaño operativo y al alcance territorial de cada sistema sanitario regional o institución pública.

Adicionalmente, se observa que ciertos organismos alcanzan importes acumulados elevados con un número relativamente reducido de licitaciones. Algunos casos presentan procedimientos de gran magnitud económica que incrementan significativamente el importe promedio gestionado por la entidad. Este comportamiento evidencia la coexistencia de distintos perfiles institucionales dentro del mercado: organismos con alta frecuencia de contratación y otros con menor volumen licitatorio, pero asociados a procedimientos económicamente más grandes o especializados.

Desde una perspectiva analítica, la diferencia entre número de licitaciones, importe acumulado e importe promedio permite identificar distintos patrones de participación institucional dentro del ecosistema de contratación pública sanitaria. Mientras algunas entidades concentran volumen económico a través de una actividad licitatoria intensiva, otras participan mediante procedimientos menos frecuentes pero de mayor magnitud económica.

No obstante, estos resultados deben interpretarse en el contexto de la muestra analizada y no como una representación exhaustiva de toda la contratación sanitaria pública española. Los valores observados corresponden exclusivamente a las licitaciones recuperadas mediante el proceso de extracción realizado sobre la Plataforma de Contratación del Sector Público, por lo que pueden verse influenciados por la temporalidad de la recolección, los criterios de búsqueda utilizados y la disponibilidad de información en la plataforma al momento de la extracción.

Desde una perspectiva estratégica, esta heterogeneidad institucional resulta especialmente relevante para el desarrollo del sistema de priorización propuesto en el proyecto. La diferencia en magnitud económica, frecuencia de contratación y perfil institucional entre organismos sugiere que no todas las oportunidades presentan el mismo nivel de accesibilidad para una clínica privada. En este sentido, variables asociadas al órgano contratante podrían constituir componentes relevantes dentro de futuros criterios de scoring y recomendación, permitiendo diferenciar oportunidades según tamaño económico, recurrencia institucional y complejidad operativa del procedimiento.

In [ ]:
import numpy as np

def gini(x):

    x = np.array(x, dtype=np.float64)

    # eliminar NA
    x = x[~np.isnan(x)]

    # evitar negativos
    x = x[x >= 0]

    # ordenar
    x = np.sort(x)

    n = len(x)

    indice = np.arange(1, n + 1)

    gini_coef = (
        np.sum((2 * indice - n - 1) * x)
        / (n * np.sum(x))
    )

    return gini_coef

In [ ]:
gini_importe = gini(df_eda["importe_sin_impuestos"].dropna())

print(gini_importe)

In [ ]:
df_eda["importe_sin_impuestos"].describe(
    percentiles=[0.5, 0.9, 0.95, 0.99, 0.999]
)

In [ ]:
df_eda["importe_sin_impuestos"].sort_values(
    ascending=False
).head(20)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# limpiar datos
valores = df_eda["importe_sin_impuestos"].dropna()

# mantener positivos
valores = valores[valores >= 0]

# ordenar valores
valores_ordenados = np.sort(valores)

# suma acumulada
acumulado = np.cumsum(valores_ordenados)

# normalizar acumulado
acumulado_normalizado = acumulado / acumulado[-1]

# porcentaje acumulado de licitaciones
proporcion_licitaciones = np.arange(
    1,
    len(valores_ordenados) + 1
) / len(valores_ordenados)

# agregar punto inicial (0,0)
proporcion_licitaciones = np.insert(
    proporcion_licitaciones,
    0,
    0
)

acumulado_normalizado = np.insert(
    acumulado_normalizado,
    0,
    0
)

# gráfica
plt.figure(figsize=(8,8))

plt.plot(
    proporcion_licitaciones,
    acumulado_normalizado,
    linewidth=3,
    label="Curva de Lorenz"
)

# línea de igualdad perfecta
plt.plot(
    [0,1],
    [0,1],
    linestyle="--",
    linewidth=2,
    label="Equidad perfecta"
)

plt.title(
    "Curva de Lorenz - Importe total de licitaciones",
    fontsize=14
)

plt.xlabel(
    "Proporción acumulada de licitaciones",
    fontsize=12
)

plt.ylabel(
    "Proporción acumulada del importe total",
    fontsize=12
)

plt.grid(True, alpha=0.3)

plt.legend()

plt.show()

El análisis exploratorio de la variable importe_sin_impuestos evidencia que el mercado de licitaciones sanitarias presenta una estructura económica extremadamente desigual y altamente concentrada. Para comprender adecuadamente este comportamiento no resultó suficiente utilizar únicamente medidas descriptivas tradicionales como la media o la desviación estándar, sino que fue necesario incorporar métricas especializadas de distribución y concentración económica.

Inicialmente, el análisis descriptivo mostró diferencias muy pronunciadas entre los valores centrales y los extremos de la distribución. Mientras la mediana del importe se sitúa alrededor de 66 mil euros, el percentil 90 supera el millón de euros y el percentil 99 alcanza aproximadamente 12,5 millones. Adicionalmente, el percentil 99,9 supera los 94 millones de euros y el valor máximo registrado alcanza aproximadamente 1.743 millones de euros. Estas diferencias evidencian la existencia de una cola derecha extremadamente extensa y de una estructura distributiva dominada por licitaciones de magnitud económica excepcionalmente elevada.

La asimetría positiva severa observada en la distribución confirma que la mayor parte de las licitaciones se concentra en importes relativamente bajos y medianos, mientras que un subconjunto reducido de procedimientos concentra valores económicos extraordinariamente altos. Complementariamente, la curtosis extremadamente elevada evidencia la presencia de colas pesadas y valores atípicos extremos que distorsionan significativamente las medidas tradicionales de tendencia central y dispersión.

Sin embargo, aunque la asimetría y la curtosis permiten describir la forma estadística de la distribución, estas métricas no cuantifican directamente el nivel de desigualdad económica existente entre las licitaciones. Por esta razón se incorporó el coeficiente de Gini, ampliamente utilizado en economía y análisis de concentración para medir desigualdad distributiva.

El coeficiente de Gini obtenido fue aproximadamente de:

Gini≈0.904

Este valor representa una concentración económica extremadamente elevada, indicando que una proporción muy reducida de licitaciones concentra gran parte del importe económico total observado, mientras que la mayoría de procedimientos participa con una fracción relativamente pequeña del volumen económico agregado.

Con el objetivo de visualizar gráficamente esta desigualdad se construyó la Curva de Lorenz. Esta técnica representa la proporción acumulada de licitaciones frente a la proporción acumulada del importe económico total. La línea diagonal representa un escenario hipotético de igualdad perfecta, donde todas las licitaciones tendrían el mismo peso económico. Sin embargo, la curva observada se aleja de manera muy pronunciada respecto a dicha diagonal, evidenciando una fuerte concentración económica en un subconjunto reducido de procedimientos de gran magnitud.

La utilización conjunta de asimetría, curtosis, coeficiente de Gini y Curva de Lorenz permite caracterizar de manera rigurosa la estructura económica del mercado analizado. Mientras la asimetría y la curtosis describen la forma estadística de la distribución, el coeficiente de Gini y la Curva de Lorenz cuantifican y visualizan el nivel de concentración económica existente. En conjunto, los resultados confirman que el mercado de licitaciones sanitarias presenta una estructura distributiva altamente desigual, dominada por procedimientos de gran magnitud económica que condicionan significativamente el comportamiento agregado del mercado.

Desde la perspectiva del proyecto, este hallazgo resulta especialmente relevante, ya que justifica la necesidad de desarrollar mecanismos de priorización y análisis estratégico de licitaciones. Dado que no todas las oportunidades poseen el mismo impacto económico potencial, la elevada concentración observada respalda la implementación de sistemas de scoring y clasificación capaces de diferenciar procedimientos según su relevancia económica, complejidad operativa y potencial estratégico para la clínica.

In [ ]:
participacion_organos = (
    df_eda
    .groupby("organo_contratacion")[
        "importe_sin_impuestos"
    ]
    .sum()
)

participacion_organos = (
    participacion_organos
    / participacion_organos.sum()
)

In [ ]:
hhi = np.sum(participacion_organos ** 2)

print("HHI institucional:", hhi)

In [ ]:
hhi_10000 = hhi * 10000

print("HHI (0-10000):", hhi_10000)

Con el objetivo de complementar el análisis de desigualdad económica, se calculó el índice Herfindahl-Hirschman (HHI) sobre la distribución del importe acumulado gestionado por los distintos órganos de contratación. Esta métrica permite evaluar el nivel de concentración institucional del mercado, considerando la participación relativa de cada organismo dentro del volumen económico total analizado.

El valor obtenido fue aproximadamente de 0,1404, equivalente a 1404 puntos en la escala tradicional utilizada en análisis de competencia económica.

Este resultado sugiere que el mercado de licitaciones sanitarias presenta un nivel de concentración institucional moderado. Aunque existen organismos públicos con una participación considerablemente superior al resto —como el Servicio Andaluz de Salud, el Servicio Madrileño de Salud o la Consellería de Sanidade - SERGAS—, el volumen económico total no se encuentra completamente dominado por una única entidad contratante.

La diferencia observada entre el coeficiente de Gini y el índice HHI resulta especialmente relevante desde una perspectiva analítica. Mientras el coeficiente de Gini evidenció una desigualdad económica extremadamente elevada entre licitaciones, el HHI indica que dicha concentración no se explica exclusivamente por una monopolización institucional del mercado. En otras palabras, el ecosistema de contratación pública sanitaria presenta una elevada concentración económica, pero distribuida entre múltiples organismos de contratación relevantes.

Este comportamiento sugiere la coexistencia de diversos actores institucionales con alta capacidad presupuestaria y operativa, generando un mercado parcialmente descentralizado desde la perspectiva institucional, aunque fuertemente concentrado en términos económicos. Desde el punto de vista estratégico, este hallazgo refuerza la necesidad de incorporar variables asociadas al órgano contratante dentro de futuros mecanismos de priorización y scoring, ya que diferentes entidades podrían representar perfiles de oportunidad distintos en términos de frecuencia, tamaño económico y complejidad operativa de las licitaciones publicadas.

In [ ]:
percentiles = df_eda["importe_sin_impuestos"].quantile(
    [0.25, 0.50, 0.75, 0.95, 0.99]
)

p25 = percentiles[0.25]
p50 = percentiles[0.50]
p75 = percentiles[0.75]
p95 = percentiles[0.95]
p99 = percentiles[0.99]

In [ ]:
def clasificar_tamano(x):

    if pd.isna(x):
        return np.nan

    elif x <= p25:
        return "Muy pequeña"

    elif x <= p50:
        return "Pequeña"

    elif x <= p75:
        return "Mediana"

    elif x <= p95:
        return "Grande"

    elif x <= p99:
        return "Muy grande"

    else:
        return "Macrolicitación"

df_eda["tamano_licitacion"] = (
    df_eda["importe_sin_impuestos"]
    .apply(clasificar_tamano)
)

In [ ]:
tamano_resumen = (
    df_eda
    .groupby("tamano_licitacion")
    .agg(
        n_licitaciones=("licitacion_id", "count"),
        importe_total=("importe_sin_impuestos", "sum"),
        importe_promedio=("importe_sin_impuestos", "mean")
    )
)

tamano_resumen

In [ ]:
tamano_resumen["n_licitaciones"].plot(
    kind="bar"
)

In [ ]:
tamano_resumen["importe_total"].plot(
    kind="bar"
)

Interpretación de la segmentación por tamaños de licitación

Con el objetivo de caracterizar la estructura económica del mercado de licitaciones sanitarias, se realizó una segmentación de los procedimientos según percentiles distributivos del importe sin impuestos. Esta clasificación permitió identificar distintos grupos de licitaciones en función de su magnitud económica relativa, diferenciando entre procedimientos muy pequeños, pequeños, medianos, grandes, muy grandes y macrolicitaciones.

Los resultados muestran que la distribución del número de licitaciones es relativamente equilibrada entre las categorías centrales de la segmentación, especialmente en los grupos de licitaciones pequeñas, medianas y muy pequeñas. Sin embargo, las categorías de mayor magnitud económica presentan una frecuencia considerablemente menor. En particular, las macrolicitaciones representan únicamente una fracción muy reducida del total de procedimientos analizados.

No obstante, al analizar el importe económico acumulado por segmento, se observa un comportamiento radicalmente distinto. A pesar de su baja frecuencia relativa, las macrolicitaciones concentran el mayor volumen económico agregado dentro del mercado analizado, superando ampliamente a categorías con miles de procedimientos adicionales. De manera similar, las licitaciones clasificadas como muy grandes también concentran una proporción significativa del importe total.

Este comportamiento confirma nuevamente la existencia de una estructura económica altamente desigual y concentrada, donde una pequeña cantidad de procedimientos de gran magnitud económica domina gran parte del volumen financiero total del mercado sanitario público.

Desde una perspectiva analítica, la diferencia observada entre frecuencia e importe acumulado evidencia que la importancia estratégica de una licitación no depende únicamente de la cantidad de procedimientos existentes dentro de una categoría, sino también de la magnitud económica asociada a cada segmento. En términos prácticos, mientras las licitaciones pequeñas y medianas representan la mayor parte de la actividad licitatoria en términos de frecuencia, las macrolicitaciones poseen un peso desproporcionadamente alto sobre el comportamiento económico agregado del mercado.

Este hallazgo resulta especialmente relevante para el desarrollo del sistema de priorización propuesto en el proyecto. La coexistencia de múltiples escalas económicas sugiere que las oportunidades de contratación pública deben evaluarse considerando no solo la probabilidad de participación, sino también el tamaño económico, la complejidad operativa y las capacidades institucionales requeridas para competir en cada segmento del mercado.

En conjunto, los resultados refuerzan la necesidad de incorporar segmentaciones económicas dentro de futuros mecanismos de scoring y recomendación, permitiendo diferenciar estrategias de análisis según el perfil económico de las licitaciones observadas.

# Segundo bloque

- ¿Qué tipos de contrato dominan el mercado sanitario?
- ¿Qué modalidades contractuales concentran mayor volumen económico?
- ¿Existen diferencias económicas entre tipos de contrato?
- ¿Cómo se distribuye la actividad licitatoria entre Obras, Servicios y Suministros?
- ¿Qué implicaciones estratégicas presentan las distintas modalidades contractuales para una clínica privada?

In [ ]:
df_eda["tipo_contrato"].value_counts(dropna=False)

In [ ]:
otros = [
    "999",
    "7",
    "32",
    "40",
    "2"
]

df_eda["tipo_contrato"] = (
    df_eda["tipo_contrato"]
    .replace(otros, "Otros / No clasificado")
)

In [ ]:
df_eda["tipo_contrato"] = (
    df_eda["tipo_contrato"]
    .astype("string")
    .str.strip()
)

df_eda["tipo_contrato"] = df_eda["tipo_contrato"].replace(
    ["", "nan", "None", "<NA>"],
    pd.NA
)

df_eda["tipo_contrato"] = df_eda["tipo_contrato"].fillna(
    "Otros / No clasificado"
)

In [ ]:
df_eda["tipo_contrato"].value_counts(dropna=False)

In [ ]:
tipos_contrato = (
    df_eda
    .groupby("tipo_contrato")
    .agg(
        n_licitaciones=("licitacion_id", "count"),
        importe_total=("importe_sin_impuestos", "sum"),
        importe_promedio=("importe_sin_impuestos", "mean")
    )
    .sort_values(
        "importe_total",
        ascending=False
    )
)

tipos_contrato

In [ ]:
tipos_contrato = (
    df_eda
    .groupby("tipo_contrato")
    .agg(
        n_licitaciones=("licitacion_id", "count"),
        importe_total=("importe_sin_impuestos", "sum"),
        importe_promedio=("importe_sin_impuestos", "mean")
    )
    .sort_values(
        "importe_total",
        ascending=False
    )
)

tipos_contrato

In [ ]:
import matplotlib.pyplot as plt

# ordenar
grafica = tipos_contrato.sort_values(
    "n_licitaciones",
    ascending=False
)

# figura
fig, ax = plt.subplots(figsize=(12,7))

# barras
bars = ax.bar(
    grafica.index,
    grafica["n_licitaciones"]
)

# título
ax.set_title(
    "Número de licitaciones por tipo de contrato",
    fontsize=16,
    fontweight="bold",
    pad=15
)

# etiquetas
ax.set_xlabel(
    "Tipo de contrato",
    fontsize=12
)

ax.set_ylabel(
    "Número de licitaciones",
    fontsize=12
)

# grid suave
ax.grid(
    axis="y",
    linestyle="--",
    alpha=0.3
)

# rotación etiquetas
plt.xticks(rotation=20)

# valores arriba
for bar in bars:

    altura = bar.get_height()

    ax.text(
        bar.get_x() + bar.get_width()/2,
        altura,
        f'{int(altura):,}',
        ha='center',
        va='bottom',
        fontsize=10,
        fontweight='bold'
    )

plt.tight_layout()

plt.show()

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

# ordenar de mayor a menor
grafica = tipos_contrato.sort_values(
    "importe_total",
    ascending=False
)

# crear figura
fig, ax = plt.subplots(figsize=(12,7))

# barras
bars = ax.bar(
    grafica.index,
    grafica["importe_total"]
)

# títulos
ax.set_title(
    "Importe acumulado por tipo de contrato",
    fontsize=16,
    fontweight="bold",
    pad=15
)

ax.set_xlabel(
    "Tipo de contrato",
    fontsize=12
)

ax.set_ylabel(
    "Importe acumulado (€)",
    fontsize=12
)

# formato eje Y en miles de millones
ax.yaxis.set_major_formatter(
    ticker.FuncFormatter(
        lambda x, pos: f'{x/1e9:.0f}B'
    )
)

# rotar etiquetas
plt.xticks(rotation=20)

# grid suave
ax.grid(
    axis="y",
    linestyle="--",
    alpha=0.3
)

# valores arriba de cada barra
for bar in bars:

    altura = bar.get_height()

    ax.text(
        bar.get_x() + bar.get_width()/2,
        altura,
        f'{altura/1e9:.1f}B',
        ha='center',
        va='bottom',
        fontsize=10,
        fontweight='bold'
    )

plt.tight_layout()

plt.show()

Interpretación de la distribución por tipo de contrato

El análisis de los tipos de contrato evidencia una estructura claramente dominada por tres grandes categorías: Obras, Servicios y Suministros. Tanto la frecuencia de licitaciones como el importe económico acumulado muestran que estas modalidades concentran prácticamente la totalidad de la actividad contractual observada dentro del mercado sanitario analizado.

La categoría Obras presenta el mayor número de licitaciones, superando ampliamente al resto de modalidades con más de 45 mil procedimientos registrados. Adicionalmente, esta categoría también concentra el mayor volumen económico acumulado, alcanzando aproximadamente 34 mil millones de euros. Este comportamiento indica que las contrataciones asociadas a infraestructura, construcción, adecuaciones o mantenimiento poseen un peso especialmente relevante dentro del ecosistema sanitario público analizado.

Por su parte, la categoría Servicios constituye el segundo segmento más importante tanto en frecuencia como en volumen económico acumulado. Sin embargo, el importe promedio de las licitaciones de servicios resulta superior al observado en Obras, lo que sugiere la existencia de procedimientos de prestación sanitaria, soporte técnico, gestión operativa o servicios especializados con una magnitud económica considerablemente elevada.

En contraste, los Suministros presentan una frecuencia significativamente menor respecto a Obras y Servicios, aunque mantienen un importe promedio relativamente alto. Este comportamiento sugiere que, aunque existen menos procedimientos asociados a adquisición de bienes y equipamiento, estos pueden involucrar volúmenes económicos importantes relacionados con tecnología médica, equipamiento hospitalario o materiales especializados.

Las restantes categorías —como concesiones, contratos mixtos o patrimoniales— representan una proporción marginal dentro de la muestra analizada, tanto en frecuencia como en importe acumulado. No obstante, algunas de estas modalidades presentan importes promedio elevados, indicando la posible existencia de procedimientos puntuales de gran escala económica.

Desde una perspectiva estratégica, los resultados evidencian que el mercado de contratación pública sanitaria no se distribuye homogéneamente entre modalidades contractuales, sino que presenta una fuerte concentración en determinados tipos de contratación. Este comportamiento resulta especialmente relevante para el desarrollo del sistema de priorización propuesto, ya que diferentes modalidades contractuales pueden implicar niveles distintos de complejidad técnica, capacidad operativa, requisitos financieros y barreras de entrada para una clínica privada.

Adicionalmente, la elevada participación de la categoría Obras dentro del mercado sanitario sugiere la necesidad de realizar análisis posteriores más específicos sobre la naturaleza real de estos procedimientos. Dado el contexto sanitario de la muestra, resulta relevante identificar si estas contrataciones corresponden principalmente a infraestructura hospitalaria, remodelaciones, mantenimiento, adecuaciones técnicas u otros tipos de proyectos asociados al sistema público de salud.

En conjunto, los resultados confirman que la estructura operativa del mercado sanitario público español presenta patrones diferenciados según modalidad contractual, reforzando la necesidad de incorporar variables relacionadas con el tipo de contrato dentro de futuros mecanismos de segmentación, scoring y recomendación de licitaciones.

In [ ]:
import pandas as pd
dic_cpv = pd.read_excel(
    "../data/CPV_Tabla_descripcion.xlsx",
    sheet_name="Hoja1"
)

dic_cpv.head()

In [ ]:
dic_cpv["cpv_codigo_limpio"] = (
    dic_cpv["Código CPV"]
    .str.split("-")
    .str[0]
)

In [ ]:
dic_cpv.head()

In [ ]:
dic_cpv_simple = (
    dic_cpv[["cpv_codigo_limpio", "Descripción"]]
    .drop_duplicates()
    .rename(columns={
        "cpv_codigo_limpio": "cpv_code",
        "Descripción": "cpv_descripcion"
    })
)

dic_cpv_simple["cpv_code"] = (
    dic_cpv_simple["cpv_code"]
    .astype(str)
    .str.strip()
)

In [ ]:
df_cpv_match = (
    df_eda[["licitacion_id", "cpv_codes"]]
    .dropna(subset=["cpv_codes"])
    .assign(
        cpv_code=lambda x: x["cpv_codes"].astype(str).str.split(";")
    )
    .explode("cpv_code")
)

df_cpv_match["cpv_code"] = (
    df_cpv_match["cpv_code"]
    .astype(str)
    .str.strip()
)

In [ ]:
df_cpv_match = df_cpv_match.merge(
    dic_cpv_simple,
    on="cpv_code",
    how="left"
)

In [ ]:
cpv_desc_por_licitacion = (
    df_cpv_match
    .groupby("licitacion_id")
    .agg(
        cpv_descripciones=(
            "cpv_descripcion",
            lambda x: "; ".join(
                sorted(set(x.dropna().astype(str)))
            )
        )
    )
    .reset_index()
)

In [ ]:
df_cpv_match[df_cpv_match["cpv_codes"].str.startswith("0", na=False)]["cpv_codes"].head(50)

In [ ]:
df_cpv_match["cpv_descripcion"].notna().mean()

In [ ]:
df_cpv_match[
    df_cpv_match["cpv_descripcion"].isna()
]["cpv_code"].value_counts().head(30)

In [ ]:
df_cpv_match["cpv_code"].isna()

In [ ]:
df_eda.head()

In [ ]:
# 2. Unir esas descripciones al dataframe principal del EDA
df_eda = df_eda.merge(
    cpv_desc_por_licitacion,
    on="licitacion_id",
    how="left"
)

In [ ]:
# 3. Validar que quedó bien
df_eda[["licitacion_id", "cpv_descripciones","cpv_codes"]].head()

In [ ]:
df_eda["cpv_descripciones"].isna().sum()

In [ ]:
cpv_freq = (
    df_eda["cpv_descripciones"]
    .value_counts(dropna=False)
    .reset_index()
)

cpv_freq.columns = [
    "cpv_descripcion",
    "n_licitaciones"
]

cpv_freq["porcentaje"] = (
    cpv_freq["n_licitaciones"]
    / cpv_freq["n_licitaciones"].sum()
) * 100

cpv_freq["porcentaje_acumulado"] = (
    cpv_freq["porcentaje"]
    .cumsum()
)

cpv_freq.head(30)

In [ ]:
top_10 = cpv_freq.head(10).copy()

top_10["porcentaje"] = (
    top_10["porcentaje"]
    .round(2)
)

top_10

In [ ]:
import matplotlib.pyplot as plt

top_10 = cpv_freq.head(10).copy()

total_cpv = len(cpv_freq)

top_10["etiqueta"] = (
    top_10["n_licitaciones"].astype(str)
    + " lic. | "
    + top_10["porcentaje"].round(2).astype(str)
    + "%"
)

fig, ax = plt.subplots(figsize=(14, 7))

bars = ax.barh(
    top_10["cpv_descripcion"][::-1],
    top_10["porcentaje"][::-1]
)

# espacio extra a la derecha para etiquetas
ax.set_xlim(
    0,
    top_10["porcentaje"].max() * 1.25
)

for bar, etiqueta in zip(bars, top_10["etiqueta"][::-1]):

    ax.text(
        bar.get_width() + 0.15,
        bar.get_y() + bar.get_height()/2,
        etiqueta,
        va="center",
        fontsize=9
    )

ax.set_xlabel("Participación sobre el total de licitaciones (%)")
ax.set_ylabel("")

ax.set_title(
    "Participación de las 10 principales categorías CPV\n"
)

plt.tight_layout()

plt.show()

In [ ]:
plt.figure(figsize=(12,5))

plt.plot(
    range(1, len(cpv_freq)+1),
    cpv_freq["n_licitaciones"].values
)

plt.yscale("log")

plt.xlabel("Ranking CPV")
plt.ylabel("Número de licitaciones (log)")

plt.title("Distribución logarítmica de categorías CPV")

plt.show()

El análisis de frecuencia de categorías CPV evidencia que el mercado de contratación sanitaria pública presenta simultáneamente una estructura altamente concentrada y una elevada diversidad funcional. Aunque se identificaron aproximadamente 5.978 categorías CPV diferentes dentro de la muestra analizada, únicamente las 10 principales categorías concentran cerca del 43% de todas las licitaciones registradas. Este resultado indica que la actividad contractual no se distribuye homogéneamente entre las distintas categorías existentes, sino que existe un núcleo funcional claramente dominante dentro del mercado sanitario.

La gráfica de barras permite identificar que la categoría “Servicios de salud” representa aproximadamente el 16,7% del total de licitaciones, posicionándose como el principal componente estructural de la contratación sanitaria pública. Posteriormente aparecen categorías relacionadas con equipamiento médico, productos farmacéuticos, material médico fungible y reactivos de laboratorio, evidenciando que gran parte de la demanda pública se concentra en actividades asistenciales, abastecimiento clínico y soporte operativo hospitalario.

Sin embargo, la distribución logarítmica de frecuencias muestra que, después de las categorías dominantes, la frecuencia de aparición de los CPV cae abruptamente y da lugar a una extensa cola larga compuesta por miles de categorías de baja recurrencia. Este comportamiento refleja una estructura típica de mercados altamente especializados, donde coexisten segmentos masivos y recurrentes junto con múltiples nichos técnicos asociados a procedimientos médicos específicos, tecnología sanitaria, mantenimiento hospitalario, infraestructura y servicios complementarios.

En conjunto, ambos resultados evidencian que el mercado sanitario público combina fenómenos de concentración estructural y fragmentación técnica. Mientras un pequeño grupo de categorías concentra una proporción significativa de la actividad licitatoria, existe simultáneamente una elevada heterogeneidad funcional representada por miles de categorías altamente específicas. Este hallazgo resulta relevante para el sistema de priorización propuesto en el TFM, ya que sugiere que la identificación de oportunidades no debe limitarse únicamente a las categorías más frecuentes, sino también considerar segmentos especializados que podrían representar oportunidades estratégicas dependiendo de la capacidad operativa y experiencia de la clínica.

## Importe sin impuestos

In [ ]:
cpv_importe = (
    df_eda
    .groupby("cpv_descripciones", as_index=False)
    .agg(
        n_licitaciones=("licitacion_id", "count"),
        importe_total=("importe_sin_impuestos", "sum"),
        importe_promedio=("importe_sin_impuestos", "mean"),
        importe_mediano=("importe_sin_impuestos", "median")
    )
)

cpv_importe = cpv_importe.sort_values(
    "importe_total",
    ascending=False
)

cpv_importe.head(10)

In [ ]:
top_importe = (
    cpv_importe
    .head(10)
    .sort_values("importe_total", ascending=True)
)

plt.figure(figsize=(13,7))

bars = plt.barh(
    top_importe["cpv_descripciones"],
    top_importe["importe_total"]
)

# Etiquetas
for bar, valor in zip(bars, top_importe["importe_total"]):

    plt.text(
        valor * 1.01,
        bar.get_y() + bar.get_height()/2,
        f"{valor/1e9:.2f} B",
        va="center",
        fontsize=9
    )

plt.xlabel("Importe total sin impuestos")
plt.ylabel("")

plt.title(
    "Categorías CPV con mayor volumen económico"
)

plt.tight_layout()
plt.show()

In [ ]:
df_cpv_explotado = (
    df_eda[
        [
            "licitacion_id",
            "cpv_descripciones",
            "importe_sin_impuestos"
        ]
    ]
    .dropna(subset=["cpv_descripciones"])
    .copy()
)

df_cpv_explotado["cpv_descripcion"] = (
    df_cpv_explotado["cpv_descripciones"]
    .str.split(";")
)

df_cpv_explotado = (
    df_cpv_explotado
    .explode("cpv_descripcion")
)

df_cpv_explotado["cpv_descripcion"] = (
    df_cpv_explotado["cpv_descripcion"]
    .str.strip()
)

df_cpv_explotado = (
    df_cpv_explotado
    .reset_index(drop=True)
)

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

cpv_interes = [
    "Servicios de salud",
    "Productos farmacéuticos",
    "Equipamiento médico",
    "Servicios de ambulancia",
    "Servicios hospitalarios"
]

df_dispersion = (
    df_cpv_explotado[
        df_cpv_explotado["cpv_descripcion"].isin(cpv_interes)
    ]
    .copy()
)

plt.figure(figsize=(14,7))

# Boxplot
sns.boxplot(
    data=df_dispersion,
    x="cpv_descripcion",
    y="importe_sin_impuestos",
    showcaps=True,
    boxprops={"facecolor":"white"},
    showfliers=False,
    whiskerprops={"linewidth":1}
)

# Puntos individuales
sns.stripplot(
    data=df_dispersion,
    x="cpv_descripcion",
    y="importe_sin_impuestos",
    hue="cpv_descripcion",
    jitter=0.3,
    alpha=0.35,
    size=3
)

plt.yscale("log")

plt.xlabel("")
plt.ylabel("Importe sin impuestos (log)")

plt.title(
    "Distribución y dispersión de importes por principales categorías CPV"
)

plt.legend([],[], frameon=False)

plt.tight_layout()
plt.show()

## Concentración económica por categoría CPV

La distribución económica de las licitaciones sanitarias evidencia una fuerte concentración del presupuesto en un número reducido de categorías CPV. La categoría **Productos farmacéuticos** domina ampliamente el mercado, alcanzando aproximadamente 12 mil millones de euros en importe acumulado sin impuestos, superando de forma considerable al resto de categorías analizadas. Su volumen económico es más de tres veces superior al de la segunda categoría con mayor importe acumulado, lo que refleja el peso estructural que tienen los productos farmacéuticos dentro de la contratación sanitaria pública.

En un segundo nivel aparecen categorías como **Servicios de ambulancia**, **Equipamiento médico**, **Servicios de transporte por carretera**, **Vacunas** y **Servicios hospitalarios**, las cuales también concentran importes elevados, aunque significativamente inferiores al segmento farmacéutico. Este comportamiento confirma que el gasto sanitario no se distribuye de manera homogénea entre categorías, sino que existe una marcada concentración presupuestaria en áreas estratégicas relacionadas con medicamentos, equipamiento e infraestructura asistencial.

Adicionalmente, resulta relevante observar que la categoría **Servicios de salud**, pese a ser la que concentra el mayor número de licitaciones, no lidera el volumen económico total. Esto indica que la frecuencia de contratación no necesariamente implica una mayor concentración presupuestaria, diferenciando claramente entre actividad operativa y peso económico dentro del mercado sanitario.

---

## Distribución y dispersión de importes por categoría

La distribución interna de los importes evidencia diferencias estructurales importantes entre categorías CPV. En la categoría **Servicios de salud** se observa una alta concentración de contratos de bajo y mediano importe, acompañada de una mediana considerablemente inferior al resto de categorías analizadas. Este comportamiento sugiere que se trata de un segmento altamente operativo y recurrente, compuesto principalmente por un gran volumen de licitaciones de menor tamaño económico.

Por el contrario, la categoría **Productos farmacéuticos** presenta una distribución claramente desplazada hacia importes más elevados. Tanto la mediana como la dispersión reflejan que los contratos farmacéuticos manejan valores significativamente superiores de manera más consistente, lo que explica su dominancia económica dentro del mercado sanitario.

Las categorías **Servicios hospitalarios** y **Servicios de ambulancia** muestran una dispersión extremadamente amplia y una fuerte presencia de contratos de gran magnitud económica. Este comportamiento evidencia una elevada heterogeneidad contractual y una importante dependencia de macrocontratos que incrementan sustancialmente el importe total acumulado.

En conjunto, los resultados permiten identificar tres grandes estructuras dentro de la contratación sanitaria pública:

| Tipo de estructura | Características |
|---|---|
| Operativa recurrente | Gran volumen de licitaciones de menor importe |
| Económicamente dominante | Contratos consistentemente altos |
| Dependiente de macrocontratos | Alta dispersión y presencia de contratos extremos |

En términos generales, el mercado sanitario combina segmentos masivos de operación recurrente con nichos estratégicos altamente concentrados desde el punto de vista presupuestario.

# Bloque 3
- ¿Cómo evoluciona la actividad licitatoria en el tiempo?
- ¿Existen tendencias crecientes o decrecientes?
- ¿Hay estacionalidad?
- ¿Existen meses con mayor actividad?
- ¿El volumen económico sigue patrones temporales?
- ¿Existen ciclos recurrentes?

# Fecha de publicación

In [ ]:
[col for col in df_eda.columns if "fecha" in col.lower()]

In [ ]:
df_eda.columns

In [ ]:
df_eda["fecha_publicacion"].dtype
df_eda["fecha_publicacion"].head(20)

In [ ]:
df_eda["fecha_publicacion"].isna().sum()

In [ ]:
df_eda["fecha_publicacion"] = pd.to_datetime(
    df_eda["fecha_publicacion"],
    errors="raise"
)

In [ ]:
df_eda["fecha_publicacion"].head()

In [ ]:
df_eda["fecha_publicacion"].isna().sum()

In [ ]:
df_eda["fecha_publicacion"].min()

In [ ]:
df_eda["fecha_publicacion"].max()

# Presentación hasta

In [ ]:
df_eda["presentacion_hasta"].head()

In [ ]:
df_eda["presentacion_hasta"].isna().sum()

In [ ]:
df_eda.loc[2631, [
    "licitacion_id",
    "titulo",
    "fecha_publicacion",
    "presentacion_hasta",
    "estado",
    "url"
]]

In [ ]:
df_eda[
    df_eda["presentacion_hasta"]
    .astype(str)
    .str.startswith("0019", na=False)
][
    ["licitacion_id", "presentacion_hasta", "titulo"]
]

In [ ]:
df_eda.loc[[2631], [
    "licitacion_id",
    "titulo",
    "fecha_publicacion",
    "presentacion_hasta",
    "estado",
    "url"
]]

In [ ]:
df_eda["presentacion_hasta"].unique()[:20]

In [ ]:
df_eda["presentacion_hasta"] = (
    df_eda["presentacion_hasta"]
    .replace("", pd.NA)
)

In [ ]:
df_eda["presentacion_hasta"].isna().sum()

In [ ]:
import numpy as np

df_eda["presentacion_hasta"] = (
    df_eda["presentacion_hasta"]
    .replace("", np.nan)
)

In [ ]:
df_eda.loc[2631, "presentacion_hasta"]

In [ ]:
df_eda.loc[6769, "presentacion_hasta"] = "2019-02-20"
df_eda.loc[9563, "presentacion_hasta"] = "2019-10-31"

In [ ]:
df_eda[
    df_eda["presentacion_hasta"]
    .astype(str)
    .str.contains(":", na=False)
][
    ["licitacion_id", "presentacion_hasta", "titulo"]
].head(20)

In [ ]:
df_eda["presentacion_hasta"] = (
    df_eda["presentacion_hasta"]
    .astype(str)
    .str[:10]
    .replace({
        "": np.nan,
        "<NA>": np.nan,
        "nan": np.nan
    })
)

In [ ]:
df_eda["presentacion_hasta"] = pd.to_datetime(
    df_eda["presentacion_hasta"],
    errors="raise"
)

In [ ]:
df_eda["presentacion_hasta"].isna().sum()

In [ ]:
df_eda["presentacion_hasta"].min()

In [ ]:
df_eda["presentacion_hasta"].max()

In [ ]:
df_eda[
    df_eda["presentacion_hasta"] == df_eda["presentacion_hasta"].min()
][
    [
        "licitacion_id",
        "titulo",
        "fecha_publicacion",
        "presentacion_hasta",
        "estado"
    ]
]

In [ ]:
df_eda[
    df_eda["presentacion_hasta"] == df_eda["presentacion_hasta"].max()
][
    [
        "licitacion_id",
        "titulo",
        "fecha_publicacion",
        "presentacion_hasta",
        "estado"
    ]
]

# presentaciones desde

In [ ]:
df_eda["presentacion_desde"].astype(str).value_counts().head(20)

In [ ]:
df_eda["presentacion_desde"] = (
    df_eda["presentacion_desde"]
    .astype(str)
    .str.strip()
    .replace({
        "": np.nan,
        "<NA>": np.nan,
        "nan": np.nan
    })
)

In [ ]:
df_eda[
    df_eda["presentacion_desde"]
    .astype(str)
    .str.contains(":", na=False)
][
    ["licitacion_id", "presentacion_desde", "titulo"]
].head(20)

In [ ]:
df_eda[
    df_eda["presentacion_desde"]
    .astype(str)
    .str.startswith("0019", na=False)
][
    ["licitacion_id", "presentacion_desde", "titulo"]
]

In [ ]:
df_eda.loc[[2], [
    "licitacion_id",
    "titulo",
    "presentacion_desde",
    "estado",
    "url"
]]

In [ ]:
df_eda[
    df_eda["presentacion_desde"]
    .astype(str)
    .str.contains(r"\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}", regex=True, na=False)
][
    ["licitacion_id", "presentacion_desde", "titulo"]
]

In [ ]:
df_eda.loc[
    df_eda["presentacion_desde"] == "2018-06-28 09:00",
    "presentacion_desde"
] = "2018-06-28"

In [ ]:
df_eda[
    df_eda["presentacion_desde"]
    .astype(str)
    .str.contains(r"\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}", regex=True, na=False)
][
    ["licitacion_id", "presentacion_desde", "titulo"]
]

In [ ]:
df_eda["presentacion_desde"] = pd.to_datetime(
    df_eda["presentacion_desde"],
    errors="raise"
)

In [ ]:
df_eda["presentacion_desde"].isna().sum()

In [ ]:
df_eda["presentacion_desde"].min()

In [ ]:
df_eda["presentacion_desde"].max()

# updated

In [ ]:
df_eda["updated"].astype(str).value_counts().head(20)

In [ ]:
df_eda.loc[[1238], [
    "licitacion_id",
    "titulo",
    "fecha_publicacion",
    "updated",
    "estado",
    "url"
]]

In [ ]:
df_eda["updated"] = pd.to_datetime(
    df_eda["updated"],
    format="ISO8601",
    utc=True,
    errors="raise"
)

In [ ]:
df_eda["updated"].isna().sum()

In [ ]:
df_eda["updated"].apply(type).value_counts()

In [ ]:
df_eda["updated"].min()

In [ ]:
df_eda["updated"].max()

In [ ]:
df_eda["fecha_scraping"].head(20)

In [ ]:
df_eda["fecha_scraping"].isna().sum()

In [ ]:
df_eda["fecha_scraping"] = pd.to_datetime(
    df_eda["fecha_scraping"],
    errors="raise"
)

In [ ]:
df_eda["fecha_scraping"].min()

In [ ]:
df_eda["fecha_scraping"].max()

## Auditoría y validación de variables temporales

Previo al desarrollo del bloque de temporalidad, se realizó una auditoría exhaustiva de las variables temporales presentes en el conjunto de datos con el objetivo de evaluar su calidad, consistencia y utilidad analítica. Esta fase fue fundamental para garantizar la validez de los análisis longitudinales posteriores, evitando sesgos derivados de formatos inconsistentes, fechas inválidas o pérdida silenciosa de información.

Inicialmente se identificaron las siguientes variables temporales relevantes dentro de la base de licitaciones:

- `fecha_publicacion`
- `presentacion_desde`
- `presentacion_hasta`
- `updated`
- `fecha_scraping`

Durante la validación se optó por una estrategia de conversión estricta utilizando `errors="raise"` en los procesos de transformación temporal, evitando el uso de conversiones automáticas que pudieran ocultar inconsistencias mediante la generación silenciosa de valores nulos. Este enfoque permitió detectar explícitamente anomalías estructurales presentes en los datos originales.

La variable `fecha_publicacion` presentó la mayor calidad y consistencia del conjunto temporal. Tras la validación, únicamente se identificaron 18 registros faltantes sobre más de 72.000 observaciones, con una cobertura temporal comprendida entre enero de 2018 y mayo de 2026. Debido a su alta completitud y coherencia estructural, esta variable fue definida como la referencia temporal principal para los análisis de series temporales, tendencias y evolución del mercado licitatorio sanitario.

En contraste, las variables `presentacion_desde` y `presentacion_hasta` presentaron una calidad más heterogénea. Durante la auditoría se detectaron múltiples problemáticas típicas de datos públicos y procesos de scraping multiportal, entre ellas:

- valores vacíos representados como cadenas (`''`) en lugar de valores nulos estándar;
- coexistencia de formatos con y sin componente horaria;
- registros con años corruptos, como `0019-02-20`;
- fechas extremas potencialmente utilizadas como *placeholders* administrativos, por ejemplo `1900-02-24` y `2125-12-31`.

Adicionalmente, ambas variables mostraron una elevada proporción de valores faltantes, especialmente `presentacion_desde`, lo que limita su aplicabilidad para análisis longitudinales masivos. Sin embargo, los registros válidos restantes mostraron una calidad relativamente adecuada tras las correcciones manuales realizadas, por lo que estas variables podrían utilizarse posteriormente en análisis parciales de duración de convocatorias o estudios exploratorios de supervivencia.

La variable `updated` mostró una estructura temporal significativamente más robusta y moderna. Los datos se encontraban en formato ISO8601 con información completa de *timestamp* y zonas horarias. Aunque inicialmente se detectaron diferencias en offsets horarios (`+01:00`, `+02:00`) debido a cambios estacionales de horario en España, la variable fue normalizada correctamente a UTC para garantizar consistencia interna. Tras el procesamiento, únicamente se identificaron 13 valores faltantes, lo que permite considerar esta variable como altamente confiable para análisis de trazabilidad administrativa y seguimiento del ciclo de vida de los expedientes.

Por último, `fecha_scraping` presentó un comportamiento estable y consistente, al corresponder a una variable generada directamente por el pipeline de extracción. No obstante, debido a que representa el momento técnico de captura de los datos y no un evento propio del mercado licitatorio, su utilización quedó restringida a fines de auditoría y control del proceso ETL.

Como resultado de esta auditoría, se estableció una diferenciación conceptual entre cuatro dimensiones temporales presentes en la base de datos:

| Dimensión temporal | Variable principal |
|---|---|
| Temporalidad del mercado | `fecha_publicacion` |
| Ventanas operativas de convocatoria | `presentacion_desde` / `presentacion_hasta` |
| Temporalidad administrativa | `updated` |
| Temporalidad técnica de extracción | `fecha_scraping` |

En consecuencia, el análisis temporal principal del proyecto se desarrollará utilizando `fecha_publicacion` como eje cronológico central, debido a su mayor cobertura, consistencia y representatividad del comportamiento real del mercado sanitario público.

# Sereis

In [ ]:
# =========================================================
# BLOQUE 2 — SERIES TEMPORALES
# Cantidad de licitaciones
# Frecuencia mensual y semanal
# =========================================================

# =========================================================
# 1. SERIE MENSUAL
# =========================================================

# Crear variable año-mes
df_eda["year_month"] = (
    df_eda["fecha_publicacion"]
    .dt.to_period("M")
    .astype(str)
)

# Agregación mensual
df_mensual = (
    df_eda
    .groupby("year_month")
    .agg(
        n_licitaciones=(
            "licitacion_id",
            "nunique"
        )
    )
    .reset_index()
)

# Convertir a datetime
df_mensual["year_month"] = pd.to_datetime(
    df_mensual["year_month"]
)

# Ordenar
df_mensual = (
    df_mensual
    .sort_values("year_month")
    .reset_index(drop=True)
)

# Visualizar
df_mensual.head()

In [ ]:
# =========================================================
# GRÁFICA — LICITACIONES POR MES
# =========================================================

import matplotlib.pyplot as plt

plt.figure(figsize=(14,6))

plt.plot(
    df_mensual["year_month"],
    df_mensual["n_licitaciones"]
)

plt.title(
    "Número de licitaciones por mes",
    fontsize=16
)

plt.xlabel("Fecha")
plt.ylabel("Número de licitaciones")

plt.grid(True)

plt.show()

In [ ]:
# =========================================================
# 2. SERIE SEMANAL
# =========================================================

# Crear variable año-semana
df_eda["year_week"] = (
    df_eda["fecha_publicacion"]
    .dt.to_period("W")
    .astype(str)
)

# Agregación semanal
df_semanal = (
    df_eda
    .groupby("year_week")
    .agg(
        n_licitaciones=(
            "licitacion_id",
            "nunique"
        )
    )
    .reset_index()
)

# Convertir inicio de semana a datetime
df_semanal["fecha_semana"] = pd.to_datetime(
    df_semanal["year_week"]
    .str.split("/")
    .str[0]
)

# Ordenar
df_semanal = (
    df_semanal
    .sort_values("fecha_semana")
    .reset_index(drop=True)
)

# Visualizar
df_semanal.head()

In [ ]:
# =========================================================
# GRÁFICA — LICITACIONES POR SEMANA
# =========================================================

plt.figure(figsize=(14,6))

plt.plot(
    df_semanal["fecha_semana"],
    df_semanal["n_licitaciones"]
)

plt.title(
    "Número de licitaciones por semana",
    fontsize=16
)

plt.xlabel("Fecha")
plt.ylabel("Número de licitaciones")

plt.grid(True)

plt.show()

La serie temporal mensual y semanal del número de licitaciones sanitarias evidencia un comportamiento relativamente estable entre 2018 y 2022, período en el cual la actividad licitatoria oscila alrededor de niveles moderados y con variaciones controladas. Durante estos años se observan fluctuaciones normales del mercado, con algunos incrementos puntuales, pero sin cambios estructurales significativos en la intensidad de contratación pública sanitaria.

Sin embargo, a comienzos de 2023 aparece una anomalía extremadamente marcada en ambas series temporales. En la agregación mensual se registra un pico cercano a las 9.000 licitaciones, mientras que en la serie semanal se alcanzan valores próximos a las 4.000 licitaciones en una sola semana. Este comportamiento rompe completamente la escala histórica observada en el resto del período analizado, ya que inmediatamente después la serie retorna a niveles similares a los registrados antes del evento.

Desde una perspectiva analítica, este patrón no parece corresponder a una tendencia natural del mercado sanitario, debido a que no existe un crecimiento progresivo previo ni una estabilización posterior en niveles elevados. Por el contrario, la forma abrupta del incremento y su rápida reversión sugieren la posible presencia de anomalías derivadas de procesos de captura, duplicación de registros, cambios en la estructura de publicación de la fuente de datos o cargas masivas excepcionales.

A pesar de ello, la serie también muestra señales relevantes posteriores a 2024, donde se aprecia un aumento moderado en la volatilidad y en la frecuencia de licitaciones respecto a los años iniciales del período. Esto podría indicar una expansión gradual de la actividad contractual sanitaria o una mayor intensidad de publicación de procesos públicos en los años más recientes.

Metodológicamente, la detección de estos comportamientos atípicos resulta fundamental antes de aplicar técnicas avanzadas de análisis temporal como medias móviles, estacionalidad o autocorrelación, ya que la presencia de anomalías extremas puede distorsionar significativamente la interpretación estadística de las tendencias reales del mercado.

La serie temporal semanal fue seleccionada como unidad principal de análisis debido a que proporciona una mayor granularidad temporal para estudiar el comportamiento del mercado de licitaciones sanitarias. Aunque la agregación mensual permite visualizar tendencias generales de largo plazo con menor ruido, la frecuencia semanal conserva una mayor cantidad de información temporal, lo que resulta especialmente relevante para los objetivos analíticos y predictivos del proyecto.

Desde una perspectiva metodológica, el uso de datos semanales permite capturar con mayor precisión cambios en la intensidad licitatoria, patrones operativos de corto plazo, concentraciones temporales de actividad y posibles ciclos recurrentes del mercado. Adicionalmente, esta granularidad incrementa significativamente el número de observaciones disponibles para análisis estadísticos avanzados y futuros modelos predictivos.

En términos prácticos, mientras una serie mensual desde 2018 produciría menos de cien observaciones temporales, la agregación semanal permite disponer de más de cuatrocientas observaciones, mejorando la capacidad para aplicar técnicas de análisis de series temporales como autocorrelación, identificación de estacionalidad, medias móviles y modelos de forecasting.

Por esta razón, la frecuencia semanal se adopta como eje central del análisis temporal del proyecto, mientras que la agregación mensual se conserva únicamente como apoyo descriptivo y visual para resumir tendencias generales del mercado sanitario.

# Analsis serie temporal semanal

In [ ]:
# =========================================================
# TOP SEMANAS CON MÁS LICITACIONES
# =========================================================

df_semanal.sort_values(
    "n_licitaciones",
    ascending=False
).head(15)

La serie temporal semanal evidencia un comportamiento relativamente estable entre 2018 y 2022, con fluctuaciones moderadas en el número de licitaciones sanitarias publicadas en la Plataforma de Contratación del Sector Público. Sin embargo, durante febrero y marzo de 2023 se observa un incremento extraordinario de actividad, alcanzando volúmenes superiores a 3.000 procesos semanales, valores significativamente superiores al comportamiento histórico del resto de la serie.

Las semanas con mayor intensidad corresponden principalmente a febrero y marzo de 2023, generando una ruptura visible en la escala temporal del conjunto de datos. Adicionalmente, las validaciones realizadas sobre identificadores únicos no evidencian problemas evidentes de duplicación estructural, lo que confirma que dichos registros corresponden efectivamente a publicaciones existentes dentro de la plataforma oficial de contratación pública.

Desde una perspectiva estadística, estos comportamientos pueden considerarse valores atípicos dentro de la serie temporal, debido a su magnitud excepcional respecto al patrón observado en el resto del período analizado. Posteriormente, la actividad retorna a niveles considerablemente inferiores, aunque manteniendo una volatilidad ligeramente superior respecto a los años iniciales de la serie.

Metodológicamente, la identificación de estos valores atípicos resulta especialmente relevante para las etapas posteriores del análisis temporal, ya que observaciones extremas pueden influir significativamente sobre métricas de tendencia, estacionalidad, autocorrelación y futuros modelos predictivos. Por esta razón, estos períodos deberán ser tratados cuidadosamente en las fases posteriores del análisis estadístico y de modelado temporal.

In [ ]:
# =========================================================
# MEDIA MÓVIL — 4 SEMANAS
# =========================================================

df_semanal["rolling_4"] = (
    df_semanal["n_licitaciones"]
    .rolling(window=4)
    .mean()
)

In [ ]:
# =========================================================
# GRÁFICA — SERIE ORIGINAL + MEDIA MÓVIL
# =========================================================

import matplotlib.pyplot as plt

plt.figure(figsize=(16,6))

# Serie original
plt.plot(
    df_semanal["fecha_semana"],
    df_semanal["n_licitaciones"],
    alpha=0.5,
    label="Serie semanal"
)

# Media móvil
plt.plot(
    df_semanal["fecha_semana"],
    df_semanal["rolling_4"],
    linewidth=3,
    label="Media móvil 4 semanas"
)

plt.title(
    "Tendencia semanal de licitaciones sanitarias",
    fontsize=16
)

plt.xlabel("Fecha")
plt.ylabel("Número de licitaciones")

plt.legend()

plt.grid(True)

plt.show()

Interpretación de la media móvil semanal

La incorporación de una media móvil de cuatro semanas permite suavizar la variabilidad natural de la serie semanal y visualizar con mayor claridad la tendencia general del comportamiento licitatorio sanitario a lo largo del tiempo. En comparación con la serie original, la media móvil reduce el impacto de fluctuaciones puntuales de corto plazo y facilita la identificación de patrones estructurales dentro del mercado de contratación pública sanitaria.

La tendencia suavizada evidencia que entre 2018 y 2021 el número de licitaciones semanales se mantuvo relativamente estable, con oscilaciones moderadas alrededor de un nivel constante de actividad. Durante este período no se observan cambios abruptos sostenidos ni tendencias crecientes pronunciadas, lo que sugiere un comportamiento relativamente homogéneo del volumen de publicaciones sanitarias.

Sin embargo, la media móvil también refleja claramente el evento atípico identificado previamente durante febrero y marzo de 2023. Aunque el suavizamiento reduce parcialmente la magnitud extrema de los valores observados en la serie original, el incremento continúa siendo significativamente superior al comportamiento histórico del resto del período, confirmando que se trata de una alteración relevante dentro de la dinámica temporal de la serie.

Posteriormente, la actividad retorna a niveles considerablemente inferiores, aunque se observa un aumento gradual tanto en la volatilidad como en la intensidad promedio de publicaciones durante 2025 y comienzos de 2026. Este comportamiento sugiere una dinámica temporal más activa en los períodos recientes en comparación con los primeros años de la serie.

Desde una perspectiva metodológica, la media móvil resulta especialmente útil como mecanismo de suavización previo al análisis de autocorrelación, estacionalidad y modelado predictivo, ya que permite diferenciar con mayor claridad las tendencias estructurales de las fluctuaciones aleatorias de corto plazo presentes en la serie semanal.

In [ ]:
# =========================================================
# SEMANA DEL AÑO
# =========================================================

df_eda["semana_anio"] = (
    df_eda["fecha_publicacion"]
    .dt.isocalendar()
    .week
)

In [ ]:
# =========================================================
# LICITACIONES PROMEDIO POR SEMANA DEL AÑO
# =========================================================

estacionalidad = (
    df_eda
    .groupby("semana_anio")
    .agg(
        promedio_licitaciones=(
            "licitacion_id",
            "nunique"
        )
    )
    .reset_index()
)

In [ ]:
# =========================================================
# GRÁFICA — ESTACIONALIDAD SEMANAL
# =========================================================

import matplotlib.pyplot as plt

plt.figure(figsize=(16,6))

plt.plot(
    estacionalidad["semana_anio"],
    estacionalidad["promedio_licitaciones"]
)

plt.title(
    "Estacionalidad semanal de licitaciones sanitarias",
    fontsize=16
)

plt.xlabel("Semana del año")
plt.ylabel("Número de licitaciones")

plt.grid(True)

plt.show()

In [ ]:
# =========================================================
# REMOVER SEMANAS ATÍPICAS
# =========================================================

semanas_outliers = [
    "2023-02-06/2023-02-12",
    "2023-02-13/2023-02-19",
    "2023-02-20/2023-02-26",
    "2023-03-06/2023-03-12"
]

df_eda_clean = df_eda[
    ~df_eda["year_week"].isin(semanas_outliers)
].copy()

In [ ]:
# =========================================================
# RECONSTRUIR ESTACIONALIDAD
# =========================================================

df_eda_clean["semana_anio"] = (
    df_eda_clean["fecha_publicacion"]
    .dt.isocalendar()
    .week
)

estacionalidad_clean = (
    df_eda_clean
    .groupby("semana_anio")
    .agg(
        promedio_licitaciones=(
            "licitacion_id",
            "nunique"
        )
    )
    .reset_index()
)

In [ ]:
# =========================================================
# ESTACIONALIDAD SIN OUTLIERS
# =========================================================

import matplotlib.pyplot as plt

plt.figure(figsize=(16,6))

plt.plot(
    estacionalidad_clean["semana_anio"],
    estacionalidad_clean["promedio_licitaciones"]
)

plt.title(
    "Estacionalidad semanal sin valores atípicos",
    fontsize=16
)

plt.xlabel("Semana del año")
plt.ylabel("Número de licitaciones")

plt.grid(True)

plt.show()

La estacionalidad semanal calculada sobre la serie depurada —excluyendo las semanas identificadas como valores atípicos extremos— muestra un comportamiento considerablemente más estable y consistente respecto al análisis inicial. La eliminación de estos eventos extraordinarios permitió recuperar la estructura temporal subyacente de la serie y reducir la distorsión generada por los picos anómalos observados durante 2023.

A diferencia de la primera aproximación, donde ciertas semanas aparecían artificialmente sobredimensionadas, la serie ajustada evidencia fluctuaciones moderadas a lo largo del año, sin observarse períodos que concentren de manera dominante la actividad licitatoria sanitaria. Esto sugiere que el mercado de contratación pública sanitaria presenta una distribución relativamente continua de publicaciones durante la mayor parte del calendario anual.

No obstante, sí se identifican incrementos moderados en determinadas semanas del año, particularmente alrededor de las semanas 10–12, 20–22, 36–37 y 45–51, donde el promedio de licitaciones tiende a ubicarse por encima del comportamiento medio de la serie. Aunque estas variaciones no constituyen una estacionalidad fuerte o altamente marcada, sí podrían indicar la existencia de ciertos patrones temporales recurrentes dentro de la dinámica administrativa de publicación de procesos sanitarios.

Adicionalmente, las semanas finales del año presentan una disminución considerable en el volumen promedio de licitaciones, especialmente durante las semanas 52 y 53. Este comportamiento resulta coherente con períodos de cierre institucional, festividades y reducción de actividad administrativa propios del calendario anual.

En términos generales, la serie depurada no evidencia una estacionalidad extrema, sino más bien una dinámica temporal relativamente estable con fluctuaciones moderadas a lo largo del año. Desde una perspectiva analítica, este comportamiento resulta favorable para el desarrollo de modelos temporales y predictivos, ya que la ausencia de ciclos excesivamente abruptos facilita la identificación de tendencias y dependencias temporales más consistentes dentro del mercado de contratación pública sanitaria.

In [ ]:
# Crear fecha_semana solo con fechas válidas
df_eda_clean["fecha_semana"] = pd.NaT

mask_fecha = df_eda_clean["fecha_publicacion"].notna()

df_eda_clean.loc[mask_fecha, "fecha_semana"] = (
    df_eda_clean.loc[mask_fecha, "fecha_publicacion"]
    .dt.to_period("W")
    .dt.start_time
)

In [ ]:
df_semanal_clean = (
    df_eda_clean
    .dropna(subset=["fecha_semana"])
    .groupby("fecha_semana")
    .agg(
        n_licitaciones=("licitacion_id", "nunique")
    )
    .reset_index()
    .sort_values("fecha_semana")
)

In [ ]:
# =========================================================
# AUTOCORRELACIÓN — SERIE SEMANAL LIMPIA
# =========================================================

from statsmodels.graphics.tsaplots import plot_acf

plt.figure(figsize=(14,6))

plot_acf(
    df_semanal_clean["n_licitaciones"],
    lags=52
)

plt.title(
    "Autocorrelación semanal de licitaciones sanitarias",
    fontsize=16
)

plt.xlabel("Rezagos semanales")
plt.ylabel("Autocorrelación")

plt.grid(True)

plt.show()

Interpretación de la autocorrelación

La función de autocorrelación (ACF) de la serie semanal depurada evidencia la existencia de dependencia temporal significativa entre observaciones consecutivas. Los primeros rezagos presentan valores positivos relativamente elevados, especialmente en las primeras semanas, indicando que el comportamiento de una semana mantiene relación con el de las semanas inmediatamente anteriores.

En particular, el rezago 1 presenta una autocorrelación superior a 0.5, lo que sugiere una persistencia temporal considerable en la dinámica de publicación de licitaciones sanitarias. Esto implica que semanas con alta actividad licitatoria tienden a estar seguidas por semanas también relativamente altas, mientras que períodos de baja actividad muestran igualmente cierta continuidad temporal.

A medida que aumentan los rezagos, la autocorrelación disminuye gradualmente, aunque permanece positiva durante una parte importante de la serie. Este comportamiento indica que la dependencia temporal no desaparece abruptamente, sino que existe una memoria parcial del proceso a lo largo de múltiples semanas.

Adicionalmente, se observan pequeños incrementos relativos alrededor de ciertos rezagos intermedios, lo que podría sugerir la presencia de patrones temporales recurrentes moderados dentro de la serie. Sin embargo, estos comportamientos no parecen reflejar una estacionalidad extremadamente fuerte, sino más bien fluctuaciones cíclicas suaves dentro de un mercado relativamente estable.

Desde una perspectiva metodológica, la presencia de autocorrelación positiva resulta especialmente relevante para las etapas posteriores del proyecto, ya que confirma que la serie temporal contiene estructura temporal aprovechable para modelos predictivos y técnicas de forecasting. En otras palabras, el comportamiento histórico de las licitaciones aporta información útil para estimar dinámicas futuras del mercado de contratación pública sanitaria.

En términos analíticos, este resultado sugiere que la serie no corresponde a un proceso completamente aleatorio, sino a un fenómeno temporal con cierto grado de persistencia y continuidad estadística, condición favorable para la aplicación de modelos ARIMA, SARIMA u otros enfoques de predicción temporal.

# PACF

In [ ]:
# =========================================================
# PACF — AUTOCORRELACIÓN PARCIAL
# =========================================================

from statsmodels.graphics.tsaplots import plot_pacf

plt.figure(figsize=(14,6))

plot_pacf(
    df_semanal_clean["n_licitaciones"],
    lags=52,
    method="ywm"
)

plt.title(
    "Autocorrelación parcial semanal de licitaciones sanitarias",
    fontsize=16
)

plt.xlabel("Rezagos semanales")
plt.ylabel("Autocorrelación parcial")

plt.grid(True)

plt.show()

Interpretación de la autocorrelación parcial (PACF)

La función de autocorrelación parcial (PACF) evidencia que la mayor parte de la dependencia temporal de la serie semanal se concentra en los primeros rezagos. En particular, el primer rezago presenta una autocorrelación parcial elevada, superior a 0.5, indicando que el comportamiento de una semana mantiene una relación directa importante con la semana inmediatamente anterior.

Después de los primeros rezagos, la magnitud de la autocorrelación parcial disminuye considerablemente y la mayoría de valores se mantienen cercanos a cero, permaneciendo dentro de los intervalos de confianza estadística. Este comportamiento sugiere que gran parte de la dependencia temporal de la serie puede explicarse principalmente por relaciones de corto plazo.

A diferencia de la ACF, donde la autocorrelación permanecía positiva durante múltiples rezagos debido a efectos acumulativos e indirectos, la PACF muestra que las relaciones temporales directas se debilitan rápidamente a medida que aumenta la distancia temporal entre observaciones. En términos prácticos, esto indica que la actividad licitatoria reciente tiene una influencia más relevante sobre el comportamiento actual que observaciones más antiguas de la serie.

Adicionalmente, no se observan patrones periódicos extremadamente marcados en la PACF, lo que resulta consistente con el análisis de estacionalidad realizado previamente. La serie parece presentar una dependencia temporal moderada y relativamente estable, más asociada a persistencia de corto plazo que a ciclos estacionales fuertes o altamente repetitivos.

Desde una perspectiva metodológica, este comportamiento es especialmente relevante para el desarrollo posterior de modelos de series temporales, ya que la concentración de dependencia en pocos rezagos sugiere que modelos autorregresivos de bajo orden podrían capturar una parte importante de la dinámica temporal observada en el mercado de licitaciones sanitarias.

In [ ]:
# =========================================================
# DESCOMPOSICIÓN TEMPORAL
# =========================================================

from statsmodels.tsa.seasonal import seasonal_decompose

descomposicion = seasonal_decompose(
    df_semanal_clean["n_licitaciones"],
    model="additive",
    period=52
)

In [ ]:
# =========================================================
# VISUALIZAR DESCOMPOSICIÓN
# =========================================================

fig = descomposicion.plot()

fig.set_size_inches(16, 10)

plt.show()

La descomposición temporal de la serie semanal de licitaciones sanitarias permitió separar el comportamiento observado en componentes de tendencia, estacionalidad y residuo, con el objetivo de identificar posibles estructuras temporales subyacentes dentro del mercado de contratación pública sanitaria.

El componente de tendencia evidencia una evolución relativamente estable entre 2018 y 2023, con fluctuaciones moderadas alrededor de un nivel promedio relativamente constante. Sin embargo, a partir de 2024 comienza a observarse un incremento progresivo en el nivel tendencial de la serie, sugiriendo un aumento gradual en la intensidad promedio de publicación de licitaciones sanitarias durante los años más recientes.

Por otra parte, la descomposición también genera una componente periódica recurrente a lo largo del calendario anual. No obstante, esta debe interpretarse con cautela desde una perspectiva metodológica, ya que los métodos clásicos de descomposición temporal tienden a ajustar patrones estacionales incluso cuando la estacionalidad real de la serie es débil o moderada. Adicionalmente, los análisis previos de autocorrelación y autocorrelación parcial no evidenciaron señales de estacionalidad fuerte o altamente dominante dentro de la dinámica temporal observada.

En consecuencia, los resultados sugieren que la serie presenta una estructura temporal caracterizada principalmente por persistencia y dependencia de corto plazo entre semanas consecutivas, más que por ciclos estacionales rígidos o altamente marcados. Esto resulta coherente con la naturaleza administrativa y continua de los procesos de contratación pública sanitaria, donde la actividad licitatoria puede mantenerse relativamente distribuida a lo largo del año sin depender estrictamente de temporadas específicas.

Finalmente, el componente residual concentra la variabilidad no explicada por la tendencia ni por la componente periódica ajustada. Aunque la mayor parte de los residuos se distribuye alrededor de cero, todavía se observan algunos eventos extremos aislados, especialmente en los años más recientes, lo que refleja la existencia de semanas excepcionalmente activas que no pueden ser explicadas completamente mediante patrones temporales regulares.

En términos generales, la descomposición temporal confirma que la serie no corresponde a un proceso completamente aleatorio, sino que contiene estructura temporal aprovechable para futuros análisis predictivos, particularmente asociada a dependencia temporal y persistencia operativa de corto plazo.

# Serie temporal importe_sin_impuestos

In [ ]:
# =========================================================
# SERIE SEMANAL — IMPORTE ECONÓMICO
# =========================================================

df_importe_semanal = (
    df_eda_clean
    .groupby("fecha_semana")
    .agg(
        importe_total=(
            "importe_sin_impuestos",
            "sum"
        )
    )
    .reset_index()
)

In [ ]:
# =========================================================
# GRÁFICA — IMPORTE SEMANAL
# =========================================================

import matplotlib.pyplot as plt

plt.figure(figsize=(16,6))

plt.plot(
    df_importe_semanal["fecha_semana"],
    df_importe_semanal["importe_total"]
)

plt.title(
    "Importe semanal de licitaciones sanitarias",
    fontsize=16
)

plt.xlabel("Fecha")
plt.ylabel("Importe sin impuestos")

plt.grid(True)

plt.show()

La dinámica temporal del importe económico presenta un comportamiento considerablemente más volátil y heterogéneo que la serie correspondiente al número de licitaciones. A diferencia de la actividad operativa, donde el principal evento atípico se concentraba durante febrero y marzo de 2023, la serie económica no evidencia un incremento equivalente en términos financieros durante dicho período.

Este comportamiento sugiere que el fuerte aumento observado previamente en el número de publicaciones estuvo asociado principalmente a una expansión operativa del volumen de procesos, pero no necesariamente a una concentración extraordinaria de recursos económicos. En otras palabras, un mayor número de licitaciones no implicó proporcionalmente un mayor volumen financiero adjudicable.

Por el contrario, la serie económica muestra múltiples picos financieros aislados distribuidos a lo largo de diferentes años, evidenciando la existencia de contratos individuales o grupos reducidos de procesos con importes significativamente elevados. Esto confirma una estructura económica altamente heterogénea dentro del mercado de contratación pública sanitaria, donde una proporción relativamente pequeña de procesos concentra una parte importante del volumen financiero total.

Adicionalmente, hacia los años más recientes se observa un incremento gradual tanto en la volatilidad como en la magnitud de los importes semanales, lo que podría indicar una creciente complejidad económica y presupuestal del mercado sanitario analizado.

In [ ]:
# =========================================================
# MEDIA MÓVIL — IMPORTE SEMANAL
# =========================================================

df_importe_semanal["rolling_4"] = (
    df_importe_semanal["importe_total"]
    .rolling(window=4)
    .mean()
)

In [ ]:
# =========================================================
# IMPORTE SEMANAL + MEDIA MÓVIL
# =========================================================

import matplotlib.pyplot as plt

plt.figure(figsize=(16,6))

# Serie original
plt.plot(
    df_importe_semanal["fecha_semana"],
    df_importe_semanal["importe_total"],
    alpha=0.5,
    label="Importe semanal"
)

# Media móvil
plt.plot(
    df_importe_semanal["fecha_semana"],
    df_importe_semanal["rolling_4"],
    linewidth=3,
    label="Media móvil 4 semanas"
)

plt.title(
    "Tendencia semanal del importe económico",
    fontsize=16
)

plt.xlabel("Fecha")
plt.ylabel("Importe sin impuestos")

plt.legend()

plt.grid(True)

plt.show()

Interpretación de la tendencia económica semanal

La serie temporal correspondiente al importe semanal de licitaciones sanitarias presenta un comportamiento considerablemente más volátil y heterogéneo que la serie asociada al número de procesos publicados. Mientras la actividad operativa mostraba una estructura relativamente estable con algunos eventos atípicos específicos, la dinámica económica evidencia fluctuaciones financieras de gran magnitud distribuidas a lo largo de prácticamente todo el período analizado.

La media móvil de cuatro semanas permite suavizar parcialmente esta volatilidad y visualizar con mayor claridad la evolución estructural del mercado sanitario desde una perspectiva económica. A nivel tendencial, se observa un incremento progresivo en el volumen financiero promedio de las licitaciones, particularmente a partir de 2021 y con mayor intensidad durante los años más recientes de la serie.

A diferencia del análisis basado en cantidad de licitaciones, el fuerte incremento operativo identificado durante febrero y marzo de 2023 no se traduce en un aumento proporcional del importe económico agregado. Esto sugiere que dicho período estuvo caracterizado principalmente por una expansión en el número de procesos publicados, pero no necesariamente por contratos de gran magnitud financiera.

Por otra parte, la serie económica muestra múltiples picos financieros extremos distribuidos en diferentes momentos del tiempo, lo que indica la existencia de contratos individuales o grupos reducidos de procesos con importes excepcionalmente elevados. Estos eventos generan una estructura temporal altamente asimétrica y reflejan una fuerte concentración económica dentro del mercado de contratación pública sanitaria.

Adicionalmente, hacia 2024, 2025 y comienzos de 2026 se observa no solo un aumento en la volatilidad financiera, sino también un crecimiento gradual en el nivel promedio de gasto semanal. Esto podría indicar una expansión progresiva del tamaño económico de las contrataciones sanitarias en los períodos más recientes.

En términos analíticos, la comparación entre la serie operativa y la serie económica evidencia que un mayor número de licitaciones no implica necesariamente un mayor volumen financiero, lo que refuerza la importancia de analizar ambas dimensiones de manera complementaria. Desde una perspectiva estratégica, este hallazgo resulta especialmente relevante para procesos de priorización y scoring, ya que las oportunidades económicamente más relevantes del mercado no siempre coinciden con los períodos de mayor actividad licitatoria.

In [ ]:
# =========================================================
# AUTOCORRELACIÓN — IMPORTE ECONÓMICO
# =========================================================

from statsmodels.graphics.tsaplots import plot_acf

plt.figure(figsize=(14,6))

plot_acf(
    df_importe_semanal["importe_total"],
    lags=52
)

plt.title(
    "Autocorrelación del importe económico semanal",
    fontsize=16
)

plt.xlabel("Rezagos semanales")
plt.ylabel("Autocorrelación")

plt.grid(True)

plt.show()

Interpretación de la autocorrelación del importe económico

La función de autocorrelación aplicada al importe económico semanal evidencia una dependencia temporal considerablemente más débil que la observada previamente en la serie correspondiente al número de licitaciones. Aunque los primeros rezagos presentan autocorrelaciones positivas, sus magnitudes son relativamente bajas y disminuyen rápidamente, permaneciendo cercanas a cero durante la mayor parte de la serie.

A diferencia de la serie operativa —donde la autocorrelación inicial superaba ampliamente 0.5 y mostraba una persistencia temporal clara—, el comportamiento financiero parece presentar una estructura mucho más irregular y menos dependiente del pasado reciente. Esto sugiere que el volumen económico semanal de las licitaciones sanitarias posee un componente aleatorio considerablemente más alto que la simple cantidad de procesos publicados.

En términos prácticos, estos resultados indican que semanas con importes elevados no necesariamente son seguidas por semanas igualmente altas, lo que refleja una dinámica financiera más impredecible y fuertemente influenciada por contratos específicos de gran magnitud. Este comportamiento resulta coherente con la elevada heterogeneidad económica observada previamente en la serie temporal del importe semanal, caracterizada por múltiples picos financieros aislados distribuidos a lo largo del tiempo.

Adicionalmente, la ausencia de patrones fuertes y persistentes de autocorrelación sugiere que el comportamiento económico del mercado sanitario depende menos de dinámicas operativas continuas y más de eventos contractuales puntuales, licitaciones extraordinarias o procesos individuales de gran volumen presupuestal.

Desde una perspectiva analítica y predictiva, este hallazgo resulta especialmente relevante, ya que indica que la cantidad de licitaciones podría ser más susceptible de modelado temporal clásico debido a su persistencia operativa, mientras que el importe económico presenta una estructura significativamente más volátil y difícil de anticipar únicamente mediante información temporal histórica.

In [ ]:
# =========================================================
# PACF — IMPORTE ECONÓMICO
# =========================================================

from statsmodels.graphics.tsaplots import plot_pacf

plt.figure(figsize=(14,6))

plot_pacf(
    df_importe_semanal["importe_total"],
    lags=52,
    method="ywm"
)

plt.title(
    "Autocorrelación parcial del importe económico semanal",
    fontsize=16
)

plt.xlabel("Rezagos semanales")
plt.ylabel("Autocorrelación parcial")

plt.grid(True)

plt.show()

Interpretación de la autocorrelación parcial del importe económico

La función de autocorrelación parcial del importe económico semanal evidencia una dependencia temporal directa relativamente débil y concentrada principalmente en los primeros rezagos. Aunque las primeras semanas muestran autocorrelaciones parciales positivas, sus magnitudes son considerablemente menores que las observadas previamente en la serie correspondiente al número de licitaciones.

Después de los primeros rezagos, la mayoría de valores permanecen cercanos a cero y dentro de los intervalos de confianza estadística, indicando que gran parte de la dependencia financiera desaparece rápidamente una vez se controlan los efectos temporales intermedios. Este comportamiento sugiere que la dinámica económica semanal del mercado sanitario posee una estructura autoregresiva limitada y mucho menos persistente que la actividad operativa de publicación de licitaciones.

En términos prácticos, los resultados indican que el importe económico de una semana tiene una capacidad relativamente baja para explicar directamente el comportamiento financiero de semanas posteriores. Esto resulta consistente con la elevada volatilidad observada previamente en la serie económica, donde contratos individuales de gran magnitud generan fluctuaciones abruptas y difíciles de anticipar mediante patrones temporales simples.

Adicionalmente, no se observan señales claras de periodicidad fuerte ni estructuras autoregresivas de largo alcance, lo que refuerza la idea de que la dinámica financiera del mercado sanitario depende en gran medida de eventos contractuales específicos y no exclusivamente de patrones operativos recurrentes.

Comparativamente, mientras la serie correspondiente al número de licitaciones mostró una persistencia temporal considerable y una estructura más adecuada para modelos temporales clásicos, la serie económica presenta un comportamiento significativamente más irregular y menos predecible a partir de la información histórica semanal. Desde una perspectiva estratégica, este hallazgo sugiere que anticipar el volumen financiero del mercado sanitario podría requerir variables adicionales más allá del componente temporal, como categorías CPV, organismos contratantes, tipos de contrato o características específicas de los procesos licitatorios.

In [ ]:
# =========================================================
# TOP CPV POR IMPORTE ECONÓMICO
# =========================================================

top_cpv_importe = (
    df_eda_clean
    .groupby("cpv_descripciones")["importe_sin_impuestos"]
    .sum()
    .sort_values(ascending=False)
    .head(5)
    .index
)

top_cpv_importe

In [ ]:
# =========================================================
# SERIE TEMPORAL ECONÓMICA POR CPV
# =========================================================

df_cpv_importe = (
    df_eda_clean[
        df_eda_clean["cpv_descripciones"].isin(top_cpv_importe)
    ]
    .groupby(
        ["fecha_semana", "cpv_descripciones"]
    )
    .agg(
        importe_total=(
            "importe_sin_impuestos",
            "sum"
        )
    )
    .reset_index()
)

In [ ]:
# =========================================================
# EVOLUCIÓN ECONÓMICA POR CPV
# =========================================================

import matplotlib.pyplot as plt

plt.figure(figsize=(18,7))

for cpv in top_cpv_importe:

    temp = df_cpv_importe[
        df_cpv_importe["cpv_descripciones"] == cpv
    ]

    plt.plot(
        temp["fecha_semana"],
        temp["importe_total"],
        label=cpv
    )

plt.title(
    "Evolución económica semanal por principales categorías CPV",
    fontsize=16
)

plt.xlabel("Fecha")
plt.ylabel("Importe sin impuestos")

plt.legend()

plt.grid(True)

plt.show()

In [ ]:
# =========================================================
# CPV SIN PRODUCTOS FARMACÉUTICOS
# =========================================================

cpv_sin_farma = [
    cpv for cpv in top_cpv_importe
    if cpv != "Productos farmacéuticos"
]

In [ ]:
# =========================================================
# EVOLUCIÓN ECONÓMICA SIN FARMACÉUTICOS
# =========================================================

plt.figure(figsize=(18,7))

for cpv in cpv_sin_farma:

    temp = df_cpv_importe[
        df_cpv_importe["cpv_descripciones"] == cpv
    ]

    plt.plot(
        temp["fecha_semana"],
        temp["importe_total"],
        label=cpv
    )

plt.title(
    "Evolución económica semanal por categorías CPV\n(sin productos farmacéuticos)",
    fontsize=16
)

plt.xlabel("Fecha")
plt.ylabel("Importe sin impuestos")

plt.legend()

plt.grid(True)

plt.show()

In [ ]:
# =========================================================
# CPV SIN FARMACÉUTICOS Y TRANSPORTE
# =========================================================

cpv_filtrado = [
    cpv for cpv in cpv_sin_farma
    if cpv != "Servicios de transporte por carretera"
]

In [ ]:
# =========================================================
# EVOLUCIÓN ECONÓMICA — CPV FILTRADOS
# =========================================================

plt.figure(figsize=(18,7))

for cpv in cpv_filtrado:

    temp = df_cpv_importe[
        df_cpv_importe["cpv_descripciones"] == cpv
    ]

    plt.plot(
        temp["fecha_semana"],
        temp["importe_total"],
        label=cpv
    )

plt.title(
    "Evolución económica semanal por categorías CPV\n(sin farmacéuticos ni transporte)",
    fontsize=16
)

plt.xlabel("Fecha")
plt.ylabel("Importe sin impuestos")

plt.legend()

plt.grid(True)

plt.show()

Las series temporales económicas por categorías CPV evidencian que el mercado de contratación pública sanitaria presenta comportamientos financieros altamente heterogéneos entre categorías, tanto en términos de magnitud económica como de estabilidad temporal. A diferencia del análisis agregado, donde el comportamiento general podía ocultar dinámicas particulares, la segmentación por categorías permite identificar estructuras financieras diferenciadas y potencialmente relevantes para la estrategia licitatoria de una institución sanitaria.

En la primera visualización, donde se incluyen las principales categorías económicas del mercado, se observa que la categoría Productos farmacéuticos domina ampliamente el comportamiento financiero total de la serie. Esta categoría concentra los mayores importes económicos del período analizado y presenta contratos extremadamente elevados en distintos momentos del tiempo, generando picos financieros muy superiores al resto de categorías. Este comportamiento sugiere una fuerte concentración presupuestal dentro del mercado farmacéutico, donde relativamente pocos procesos pueden movilizar volúmenes económicos extraordinarios.

Debido a esta dominancia financiera, la exclusión temporal de la categoría farmacéutica permitió observar con mayor claridad la dinámica de las demás categorías relevantes. En la segunda visualización, la categoría Servicios de transporte por carretera pasa a convertirse en el principal componente económico, evidenciando también una estructura altamente volátil caracterizada por contratos aislados de gran magnitud. Esto indica que ciertos segmentos logísticos y operativos del sistema sanitario pueden generar procesos económicos excepcionalmente elevados aunque con menor frecuencia temporal.

Finalmente, al excluir tanto productos farmacéuticos como servicios de transporte por carretera, se hace posible analizar con mayor detalle categorías como Servicios de ambulancia, Equipamiento médico y Vacunas, cuyas dinámicas presentan comportamientos considerablemente distintos.

La categoría Servicios de ambulancia muestra una actividad financiera relativamente continua a lo largo del tiempo, aunque acompañada de múltiples picos económicos relevantes distribuidos en diferentes años. Esto sugiere un mercado operativo recurrente, con contratación frecuente y contratos periódicamente elevados, posiblemente asociados a renovaciones de cobertura, concesiones o ampliaciones de servicios sanitarios.

Por su parte, Equipamiento médico presenta un comportamiento más irregular y concentrado, con períodos de baja actividad interrumpidos por incrementos financieros abruptos. Este patrón resulta coherente con procesos de adquisición tecnológica o renovación de infraestructura médica, donde ciertos contratos específicos generan aumentos significativos del gasto en momentos concretos.

La categoría Vacunas evidencia igualmente una estructura altamente volátil, aunque en escalas económicas menores respecto a farmacéuticos o ambulancias. La presencia de múltiples fluctuaciones y picos puntuales refleja una dinámica financiera sensible a procesos específicos de adquisición y abastecimiento sanitario.

En términos generales, las series temporales por categorías CPV muestran que el mercado sanitario no posee una dinámica homogénea, sino múltiples submercados con estructuras económicas y temporales diferenciadas. Algunas categorías presentan comportamientos relativamente continuos y persistentes, mientras otras dependen de contratos extraordinarios aislados que generan alta volatilidad financiera.

Desde una perspectiva estratégica, estos resultados son especialmente relevantes para procesos de priorización y análisis de oportunidades, ya que permiten identificar qué categorías presentan mercados más estables y recurrentes frente a aquellas dominadas por eventos económicos puntuales de gran magnitud. Esto refuerza la importancia de incorporar segmentación por categorías CPV dentro de futuros modelos de scoring y predicción aplicados al mercado de contratación pública sanitaria.

In [ ]:
# =========================================================
# SERIE OPERATIVA POR CPV
# =========================================================

df_cpv_cantidad = (
    df_eda_clean[
        df_eda_clean["cpv_descripciones"].isin(top_cpv_importe)
    ]
    .groupby(
        ["fecha_semana", "cpv_descripciones"]
    )
    .agg(
        n_licitaciones=(
            "licitacion_id",
            "nunique"
        )
    )
    .reset_index()
)

In [ ]:
# =========================================================
# EVOLUCIÓN OPERATIVA POR CPV
# =========================================================

plt.figure(figsize=(18,7))

for cpv in top_cpv_importe:

    temp = df_cpv_cantidad[
        df_cpv_cantidad["cpv_descripciones"] == cpv
    ]

    plt.plot(
        temp["fecha_semana"],
        temp["n_licitaciones"],
        label=cpv
    )

plt.title(
    "Evolución semanal del número de licitaciones por categorías CPV",
    fontsize=16
)

plt.xlabel("Fecha")
plt.ylabel("Número de licitaciones")

plt.legend()

plt.grid(True)

plt.show()

In [ ]:
# =========================================================
# CPV OPERATIVOS DOMINANTES
# =========================================================

cpv_operativos = [
    "Productos farmacéuticos",
    "Equipamiento médico",
    "Vacunas"
]

plt.figure(figsize=(18,7))

for cpv in cpv_operativos:

    temp = df_cpv_cantidad[
        df_cpv_cantidad["cpv_descripciones"] == cpv
    ]

    plt.plot(
        temp["fecha_semana"],
        temp["n_licitaciones"],
        label=cpv
    )

plt.title(
    "Productos farmacéuticos\nEquipamiento médico\nVacunas",
    fontsize=16
)

plt.xlabel("Fecha")
plt.ylabel("Número de licitaciones")

plt.legend()

plt.grid(True)

plt.show()

La evolución temporal del número de licitaciones por categorías CPV evidencia dinámicas operativas diferenciadas dentro del mercado sanitario. Entre las principales categorías analizadas, Productos farmacéuticos, Equipamiento médico y Vacunas presentan los comportamientos más representativos y consistentes en términos de actividad licitatoria a lo largo del período estudiado.

La categoría Productos farmacéuticos muestra el comportamiento operativo más dominante y continuo dentro del mercado sanitario. La serie presenta una elevada frecuencia de publicaciones durante prácticamente todo el período analizado, acompañada de múltiples incrementos operativos y una tendencia creciente particularmente marcada en los años más recientes. Esto sugiere que el mercado farmacéutico constituye uno de los segmentos más activos y recurrentes de la contratación pública sanitaria.

Por su parte, Equipamiento médico evidencia una dinámica temporal caracterizada por un crecimiento progresivo y una mayor intensidad operativa a partir de 2023. La serie muestra incrementos significativos tanto en frecuencia como en volatilidad, indicando una expansión importante de procesos asociados a adquisición tecnológica e infraestructura médica durante los períodos más recientes.

Finalmente, la categoría Vacunas presenta una actividad operativa considerablemente menor y más irregular respecto a las demás categorías analizadas. No obstante, se observan ciertos incrementos puntuales distribuidos a lo largo del tiempo, reflejando una dinámica más dependiente de procesos específicos y necesidades sanitarias concretas.

En términos generales, los resultados evidencian que el mercado sanitario está compuesto por submercados con comportamientos operativos heterogéneos. Mientras algunas categorías mantienen actividad continua y recurrente, otras presentan dinámicas más esporádicas y dependientes de eventos específicos. Desde una perspectiva estratégica, esta segmentación temporal resulta relevante para procesos de priorización y análisis de oportunidades, ya que permite identificar categorías con mayor estabilidad operativa y continuidad licitatoria dentro del sistema sanitario.

# Duración días

In [ ]:
# =========================================================
# COMPLETITUD VARIABLES TEMPORALES
# =========================================================

df_eda[
    [
        "fecha_publicacion",
        "presentacion_hasta"
    ]
].isna().sum()

In [ ]:
# =========================================================
# DURACIÓN DE CONVOCATORIA
# =========================================================

df_supervivencia = df_eda.copy()

# Mantener solo registros válidos
df_supervivencia = df_supervivencia[
    (
        df_supervivencia["fecha_publicacion"].notna()
    )
    &
    (
        df_supervivencia["presentacion_hasta"].notna()
    )
].copy()

In [ ]:
df_supervivencia[
    [
        "fecha_publicacion",
        "presentacion_hasta"
    ]
].dtypes

In [ ]:
df_supervivencia["presentacion_hasta"] = pd.to_datetime(
    df_supervivencia["presentacion_hasta"],
    errors="raise"
)

In [ ]:
# Calcular duración
df_supervivencia["duracion_dias"] = (
    df_supervivencia["presentacion_hasta"]
    -
    df_supervivencia["fecha_publicacion"]
).dt.days

In [ ]:
# =========================================================
# RESUMEN ESTADÍSTICO
# =========================================================

df_supervivencia["duracion_dias"].describe()

In [ ]:
df_supervivencia[
    df_supervivencia["duracion_dias"] < 0
].shape

In [ ]:
df_supervivencia[
    df_supervivencia["duracion_dias"] == 0
].shape

In [ ]:
df_supervivencia.sort_values(
    "duracion_dias",
    ascending=False
)[
    [
        "licitacion_id",
        "duracion_dias",
        "cpv_descripciones",
        "presentacion_desde",
        "presentacion_hasta"
    ]
].head(20)

In [ ]:
# =========================================================
# DISTRIBUCIÓN DE DURACIÓN
# =========================================================

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))

plt.hist(
    df_supervivencia["duracion_dias"],
    bins=50
)

plt.title(
    "Distribución de duración de convocatorias",
    fontsize=16
)

plt.xlabel("Duración (días)")
plt.ylabel("Frecuencia")

plt.grid(True)

plt.show()

In [ ]:
# =========================================================
# EJEMPLOS NEGATIVOS
# =========================================================

df_supervivencia[
    df_supervivencia["duracion_dias"] < 0
][
    [
        "fecha_publicacion",
        "presentacion_hasta",
        "duracion_dias",
        "cpv_descripciones"
    ]
].head(20)

In [ ]:
# =========================================================
# EXTREMOS POSITIVOS
# =========================================================

df_supervivencia.sort_values(
    "duracion_dias",
    ascending=False
)[
    [
        "fecha_publicacion",
        "presentacion_hasta",
        "duracion_dias",
        "cpv_descripciones"
    ]
].head(20)

## Hallazgos identificados en la auditoría de duración

El análisis exploratorio de la variable de duración de convocatorias evidenció múltiples inconsistencias temporales que impiden utilizar directamente la variable `presentacion_hasta` para modelado robusto de supervivencia o duración contractual sin un proceso adicional de depuración.

La duración preliminar fue calculada como:

\[
\text{Duración convocatoria} = \text{presentacion\_hasta} - \text{fecha\_publicacion}
\]

Sin embargo, los resultados iniciales mostraron una distribución altamente anómala, caracterizada por una elevada cantidad de duraciones negativas, múltiples registros con duración igual a cero y valores extremos incompatibles con el comportamiento operativo esperado de procesos licitatorios reales.

En particular, se identificaron aproximadamente 18.000 registros con duraciones negativas, indicando que la supuesta fecha de cierre de convocatoria ocurría antes de la fecha de publicación del proceso. La revisión manual de ejemplos específicos confirmó que muchas observaciones contenían fechas históricas previas a la publicación oficial, incluyendo registros correspondientes a años anteriores como 2015, 2016 y 2017 asociados a licitaciones publicadas en 2018.

Adicionalmente, se detectaron valores extremos positivos cercanos a 39.000 días de duración, originados por la utilización recurrente de la fecha `2125-12-31` dentro de la variable `presentacion_hasta`. Este patrón sugiere el uso de fechas *placeholder* o valores administrativos artificiales empleados por algunos sistemas fuente para representar procesos sin fecha final definida o campos incompletos.

Estos hallazgos evidencian que la variable `presentacion_hasta` no representa de manera homogénea una fecha operacional de cierre de convocatoria dentro del conjunto consolidado de licitaciones. Por el contrario, la variable parece mezclar distintos significados administrativos provenientes de múltiples portales y estructuras de origen, incluyendo posibles fechas históricas heredadas, *placeholders* técnicos y valores inconsistentes derivados del scraping automatizado.

En consecuencia, el análisis de supervivencia y duración contractual requiere un proceso adicional de depuración y normalización temporal antes de poder ser utilizado para modelado estadístico confiable. No obstante, la auditoría realizada permitió identificar explícitamente las principales anomalías estructurales presentes en los datos temporales, fortaleciendo la trazabilidad y rigor metodológico del proceso analítico desarrollado en el proyecto.

# Geografico

In [ ]:
(df_eda["lugar_ejecucion"] == "").sum()

In [ ]:
(df_eda["lugar_ejecucion_codigo"] == "").sum()

In [ ]:
df_eda["lugar_ejecucion"] = (
    df_eda["lugar_ejecucion"]
    .replace(r"^\s*$", pd.NA, regex=True)
)

In [ ]:
df_eda["lugar_ejecucion_codigo"] = (
    df_eda["lugar_ejecucion_codigo"]
    .replace(r"^\s*$", pd.NA, regex=True)
)

In [ ]:
df_eda["lugar_ejecucion"].value_counts().head(30)

In [ ]:
df_eda["lugar_ejecucion_codigo"].value_counts().head(30)

In [ ]:
df_eda["lugar_ejecucion"].nunique()

In [ ]:
df_eda["lugar_ejecucion_codigo"].nunique()

In [ ]:
df_eda["lugar_ejecucion"].isna().sum()

In [ ]:
df_eda["lugar_ejecucion_codigo"].isna().sum()

In [ ]:
codigos_nuts = (
    df_eda["lugar_ejecucion_codigo"]
    .dropna()
    .astype(str)
    .str.strip()
)

tabla_nuts = pd.DataFrame({
    "codigo_nuts": sorted(codigos_nuts.unique())
})

tabla_nuts.head()

In [ ]:
tabla_nuts.to_excel(
    "tabla_codigos_nuts.xlsx",
    index=False
)

In [ ]:

tabla_nuts = pd.read_excel("../data/tabla_codigos_nuts_completa.xlsx")

In [ ]:
tabla_nuts.head()

In [ ]:
df_eda["lugar_ejecucion_codigo"] = (
    df_eda["lugar_ejecucion_codigo"]
    .astype("string")
    .str.strip()
)

tabla_nuts["codigo_nuts"] = (
    tabla_nuts["codigo_nuts"]
    .astype("string")
    .str.strip()
)

In [ ]:
df_eda = df_eda.merge(
    tabla_nuts,
    how="left",
    left_on="lugar_ejecucion_codigo",
    right_on="codigo_nuts"
)

In [ ]:
df_eda[[
    "lugar_ejecucion_codigo",
    "codigo_nuts"
]].head(20)

In [ ]:
df_eda["codigo_nuts"].isna().sum()

In [ ]:
df_eda.loc[
    df_eda["lugar_ejecucion_codigo"].notna() &
    df_eda["codigo_nuts"].isna(),
    "lugar_ejecucion_codigo"
].value_counts()

In [ ]:
df_eda.head()

In [ ]:
df_eda["nombre_region"].notna().sum()

In [ ]:
(
    df_eda["nombre_region"]
    .notna()
    .mean()
) * 100

In [ ]:
(
    df_eda
    .groupby("nombre_region")["importe_sin_impuestos"]
    .sum()
    .sort_values(ascending=False)
    .head(20)
)

In [ ]:
(
    df_eda
    .groupby("nombre_region")["importe_sin_impuestos"]
    .mean()
    .sort_values(ascending=False)
    .head(20)
)

In [ ]:
(
    df_eda[
        ["codigo_nuts", "nombre_region"]
    ]
    .drop_duplicates()
    .sort_values("codigo_nuts")
    .head(100)
)

In [ ]:
df_ccaa = (
    df_eda[
        df_eda["codigo_nuts"]
        .str.len() == 4
    ]
    .copy()
)

In [ ]:
df_ccaa["nombre_region"].value_counts()

In [ ]:
(
    df_ccaa
    .groupby("nombre_region")["importe_sin_impuestos"]
    .sum()
    .sort_values(ascending=False)
)

In [ ]:
(
    df_ccaa
    .groupby("nombre_region")["importe_sin_impuestos"]
    .mean()
    .sort_values(ascending=False)
)

In [ ]:
importe_ccaa = (
    df_ccaa
    .groupby("nombre_region")["importe_sin_impuestos"]
    .sum()
    .reset_index()
    .sort_values(
        "importe_sin_impuestos",
        ascending=True
    )
)

In [ ]:
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter

plt.figure(figsize=(13, 7))

bars = plt.barh(
    importe_ccaa["nombre_region"],
    importe_ccaa["importe_sin_impuestos"]
)

# Formato miles de millones
formatter = FuncFormatter(
    lambda x, pos: f"{x/1e9:.1f}B"
)

plt.gca().xaxis.set_major_formatter(formatter)

# Etiquetas al final de barras
for bar in bars:

    width = bar.get_width()

    plt.text(
        width,
        bar.get_y() + bar.get_height()/2,
        f"{width/1e9:.2f}B",
        va="center",
        fontsize=9
    )

plt.title(
    "Volumen económico de licitaciones sanitarias por Comunidad Autónoma",
    fontsize=15,
    pad=15
)

plt.xlabel(
    "Importe total sin impuestos (miles de millones €)",
    fontsize=12
)

plt.ylabel(
    "Comunidad Autónoma",
    fontsize=12
)

plt.grid(
    axis="x",
    linestyle="--",
    alpha=0.4
)

plt.tight_layout()

plt.show()

In [ ]:
ticket_ccaa = (
    df_ccaa
    .groupby("nombre_region")["importe_sin_impuestos"]
    .mean()
    .reset_index()
    .sort_values(
        "importe_sin_impuestos",
        ascending=True
    )
)

In [ ]:
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter

plt.figure(figsize=(13, 7))

bars = plt.barh(
    ticket_ccaa["nombre_region"],
    ticket_ccaa["importe_sin_impuestos"]
)

# Formato millones
formatter = FuncFormatter(
    lambda x, pos: f"{x/1e6:.1f}M"
)

plt.gca().xaxis.set_major_formatter(formatter)

# Etiquetas
for bar in bars:

    width = bar.get_width()

    plt.text(
        width,
        bar.get_y() + bar.get_height()/2,
        f"{width/1e6:.2f}M",
        va="center",
        fontsize=9
    )

plt.title(
    "Ticket promedio de licitaciones sanitarias por Comunidad Autónoma",
    fontsize=15,
    pad=15
)

plt.xlabel(
    "Importe promedio sin impuestos (millones €)",
    fontsize=12
)

plt.ylabel(
    "Comunidad Autónoma",
    fontsize=12
)

plt.grid(
    axis="x",
    linestyle="--",
    alpha=0.4
)

plt.tight_layout()

plt.show()

In [ ]:
n_licitaciones_ccaa = (
    df_ccaa["nombre_region"]
    .value_counts()
    .reset_index()
)

n_licitaciones_ccaa.columns = [
    "nombre_region",
    "n_licitaciones"
]

n_licitaciones_ccaa = n_licitaciones_ccaa.sort_values(
    "n_licitaciones",
    ascending=True
)

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(13, 7))

bars = plt.barh(
    n_licitaciones_ccaa["nombre_region"],
    n_licitaciones_ccaa["n_licitaciones"]
)

for bar in bars:
    width = bar.get_width()

    plt.text(
        width,
        bar.get_y() + bar.get_height()/2,
        f"{int(width):,}".replace(",", "."),
        va="center",
        fontsize=9
    )

plt.title(
    "Número de licitaciones sanitarias por Comunidad Autónoma",
    fontsize=15,
    pad=15
)

plt.xlabel("Número de licitaciones")
plt.ylabel("Comunidad Autónoma")

plt.grid(
    axis="x",
    linestyle="--",
    alpha=0.4
)

plt.tight_layout()
plt.show()

In [ ]:
resumen_ccaa = (
    df_ccaa
    .groupby("nombre_region")
    .agg(
        n_licitaciones = (
            "licitacion_id",
            "count"
        ),
        ticket_promedio = (
            "importe_sin_impuestos",
            "mean"
        ),
        volumen_total = (
            "importe_sin_impuestos",
            "sum"
        )
    )
    .reset_index()
)

resumen_ccaa

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 8))

scatter = plt.scatter(
    resumen_ccaa["n_licitaciones"],
    resumen_ccaa["ticket_promedio"],
    s = resumen_ccaa["volumen_total"] / 1e7,
    alpha = 0.7
)

# Etiquetas
for _, row in resumen_ccaa.iterrows():

    x = row["n_licitaciones"]
    y = row["ticket_promedio"]

    # Ajustes manuales para regiones pequeñas
    if row["nombre_region"] in [
        "Cantabria",
        "Extremadura",
        "Comunidad Valenciana",
        "Illes Balears"
    ]:
        x = x + 20
        y = y + 150000

    plt.text(
        x,
        y,
        row["nombre_region"],
        fontsize=9
    )

plt.title(
    "Perfil estratégico territorial de licitaciones sanitarias",
    fontsize=15,
    pad=15
)

plt.xlabel("Número de licitaciones")
plt.ylabel("Ticket promedio (€)")

plt.grid(
    linestyle="--",
    alpha=0.4
)

plt.tight_layout()

plt.show()

In [ ]:
import requests
import json

url_geojson = "https://raw.githubusercontent.com/codeforgermany/click_that_hood/main/public/data/spain-communities.geojson"

geojson_ccaa = requests.get(url_geojson).json()

geojson_ccaa["features"][0]["properties"]

In [ ]:
resumen_ccaa["nombre_region"].unique()

In [ ]:
geojson_df = pd.DataFrame([
    feature["properties"]
    for feature in geojson_ccaa["features"]
])

geojson_df.head()

In [ ]:
geojson_df["name"].sort_values().unique()

In [ ]:
mapa_nombres_ccaa = {
    "Castilla y León": "Castilla-Leon",
    "Comunidad Valenciana": "Valencia",
    "Illes Balears": "Baleares",
    "Principado de Asturias": "Asturias",
    "Andalucía": "Andalucia",
    "País Vasco": "Pais Vasco"

}

In [ ]:
resumen_ccaa["nombre_geojson"] = (
    resumen_ccaa["nombre_region"]
    .replace(mapa_nombres_ccaa)
)

In [ ]:
set(resumen_ccaa["nombre_geojson"]) - set(geojson_df["name"])

In [ ]:
fig = px.choropleth(
    resumen_ccaa,
    geojson=geojson_ccaa,
    locations="nombre_geojson",
    featureidkey="properties.name",
    color="volumen_total",
    hover_name="nombre_region",
    hover_data={
        "volumen_total": ":,.0f",
        "n_licitaciones": ":,",
        "ticket_promedio": ":,.0f",
        "nombre_geojson": False
    },
    title="Volumen económico de licitaciones sanitarias por Comunidad Autónoma"
)

fig.update_traces(
    marker_line_width=1,
    marker_line_color="white"
)

fig.update_geos(
    fitbounds="locations",
    visible=True,
    showcountries=True,
    countrycolor="black",
    showsubunits=True,
    subunitcolor="black",
    showland=True,
    landcolor="lightgray",
    showocean=False,
    showlakes=False
)

fig.update_layout(
    margin={"r":0, "t":50, "l":0, "b":0}
)

fig.show()

Análisis geográfico del mercado sanitario regional

Con el objetivo de analizar la distribución territorial del mercado sanitario público español, se realizó una segmentación geográfica utilizando la clasificación oficial NUTS (Nomenclature of Territorial Units for Statistics) de la Unión Europea. Esta estructura permitió estandarizar territorialmente las licitaciones y diferenciar distintos niveles administrativos dentro de la contratación pública sanitaria.

Durante la auditoría geográfica se identificó que las licitaciones coexistían en múltiples niveles territoriales, incluyendo registros nacionales, autonómicos y provinciales. Debido a esta heterogeneidad, el análisis se dividió jerárquicamente para evitar mezclas territoriales inconsistentes. En esta primera fase se trabajó exclusivamente con licitaciones clasificadas a nivel NUTS2, correspondientes a Comunidades Autónomas.

Los resultados evidencian una fuerte concentración regional del volumen económico sanitario. Andalucía se posiciona como la comunidad autónoma con mayor volumen económico agregado, superando ampliamente al resto de regiones analizadas. Adicionalmente, presenta un elevado número de licitaciones y un ticket promedio alto, lo que sugiere la existencia de un mercado regional robusto, recurrente y con contratos de gran magnitud económica.

Cataluña, por su parte, concentra el mayor número de licitaciones regionales del conjunto analizado. Sin embargo, su ticket promedio es considerablemente menor respecto a otras comunidades. Este comportamiento sugiere una estructura contractual más fragmentada y distribuida, caracterizada por una mayor frecuencia operativa pero con contratos de menor tamaño relativo.

Madrid presenta una dinámica distinta. Aunque registra menos licitaciones regionales en comparación con Andalucía o Cataluña, sus contratos exhiben un ticket promedio significativamente elevado. Esto podría reflejar procesos de contratación sanitaria más centralizados y contratos regionales de alta escala económica.

Canarias constituye uno de los hallazgos más particulares del análisis territorial. A pesar de presentar un bajo número de licitaciones regionales, registra el ticket promedio más alto del conjunto estudiado. Esta situación podría estar asociada a procesos de contratación agregada, compras centralizadas o condiciones logísticas específicas derivadas de la insularidad del territorio.

De manera general, los resultados permiten concluir que el mercado sanitario regional español no presenta una distribución homogénea. Existen diferencias sustanciales entre comunidades autónomas tanto en volumen económico como en recurrencia contractual y tamaño promedio de los contratos. Estas diferencias reflejan estructuras regionales de contratación pública heterogéneas, con dinámicas territoriales particulares y distintos niveles de concentración económica.

Finalmente, el análisis territorial evidencia que determinadas comunidades autónomas concentran una parte significativa de la actividad sanitaria pública, lo que podría representar entornos estratégicamente relevantes para futuras iniciativas de participación competitiva, expansión operativa o priorización comercial dentro del sector sanitario.

# Ciudades

In [ ]:
df_nuts3 = (
    df_eda[
        df_eda["codigo_nuts"]
        .str.len() == 5
    ]
    .copy()
)

In [ ]:
df_nuts3["nombre_region"].value_counts().head(30)

In [ ]:
importe_nuts3 = (
    df_nuts3
    .groupby("nombre_region")["importe_sin_impuestos"]
    .sum()
    .sort_values(ascending=False)
)

importe_nuts3.head(20)

In [ ]:
ticket_nuts3 = (
    df_nuts3
    .groupby("nombre_region")["importe_sin_impuestos"]
    .mean()
    .sort_values(ascending=False)
)

ticket_nuts3.head(20)

In [ ]:
importe_nuts3 = (
    df_nuts3
    .groupby("nombre_region")["importe_sin_impuestos"]
    .sum()
    .reset_index()
    .sort_values(
        "importe_sin_impuestos",
        ascending=True
    )
    .tail(15)
)

In [ ]:
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter

plt.figure(figsize=(13, 7))

bars = plt.barh(
    importe_nuts3["nombre_region"],
    importe_nuts3["importe_sin_impuestos"]
)

formatter = FuncFormatter(
    lambda x, pos: f"{x/1e9:.1f}B"
)

plt.gca().xaxis.set_major_formatter(formatter)

for bar in bars:

    width = bar.get_width()

    plt.text(
        width,
        bar.get_y() + bar.get_height()/2,
        f"{width/1e9:.2f}B",
        va="center",
        fontsize=9
    )

plt.title(
    "Top 15 regiones NUTS3 por volumen económico sanitario",
    fontsize=15,
    pad=15
)

plt.xlabel(
    "Importe total sin impuestos (miles de millones €)"
)

plt.ylabel("Región")

plt.grid(
    axis="x",
    linestyle="--",
    alpha=0.4
)

plt.tight_layout()

plt.show()

In [ ]:
ticket_nuts3 = (
    df_nuts3
    .groupby("nombre_region")["importe_sin_impuestos"]
    .mean()
    .reset_index()
    .sort_values(
        "importe_sin_impuestos",
        ascending=True
    )
    .tail(15)
)

In [ ]:
plt.figure(figsize=(13, 7))

bars = plt.barh(
    ticket_nuts3["nombre_region"],
    ticket_nuts3["importe_sin_impuestos"]
)

formatter = FuncFormatter(
    lambda x, pos: f"{x/1e6:.1f}M"
)

plt.gca().xaxis.set_major_formatter(formatter)

for bar in bars:

    width = bar.get_width()

    plt.text(
        width,
        bar.get_y() + bar.get_height()/2,
        f"{width/1e6:.2f}M",
        va="center",
        fontsize=9
    )

plt.title(
    "Top 15 regiones NUTS3 por ticket promedio sanitario",
    fontsize=15,
    pad=15
)

plt.xlabel(
    "Ticket promedio sin impuestos (millones €)"
)

plt.ylabel("Región")

plt.grid(
    axis="x",
    linestyle="--",
    alpha=0.4
)

plt.tight_layout()

plt.show()

In [ ]:
resumen_nuts3 = (
    df_nuts3
    .groupby("nombre_region")
    .agg(
        n_licitaciones = (
            "licitacion_id",
            "count"
        ),
        ticket_promedio = (
            "importe_sin_impuestos",
            "mean"
        ),
        volumen_total = (
            "importe_sin_impuestos",
            "sum"
        )
    )
    .reset_index()
)

In [ ]:
plt.figure(figsize=(13, 8))

plt.scatter(
    resumen_nuts3["n_licitaciones"],
    resumen_nuts3["ticket_promedio"],
    s = resumen_nuts3["volumen_total"] / 1e7,
    alpha = 0.7
)

for _, row in resumen_nuts3.iterrows():

    plt.text(
        row["n_licitaciones"],
        row["ticket_promedio"],
        row["nombre_region"],
        fontsize=8
    )

plt.title(
    "Perfil estratégico territorial NUTS3",
    fontsize=15,
    pad=15
)

plt.xlabel("Número de licitaciones")
plt.ylabel("Ticket promedio (€)")

plt.grid(
    linestyle="--",
    alpha=0.4
)

plt.tight_layout()

plt.show()

In [ ]:
import requests

url_nuts3 = (
    "https://gisco-services.ec.europa.eu/distribution/v2/nuts/geojson/NUTS_RG_20M_2021_4326_LEVL_3.geojson"
)

geojson_nuts3 = requests.get(url_nuts3).json()

In [ ]:
geojson_nuts3["features"][0]["properties"]

In [ ]:
geojson_nuts3_es = {
    "type": "FeatureCollection",
    "features": [
        feature for feature in geojson_nuts3["features"]
        if feature["properties"]["CNTR_CODE"] == "ES"
    ]
}

In [ ]:
len(geojson_nuts3_es["features"])

In [ ]:
geojson_nuts3_es["features"][0]["properties"]

In [ ]:
locations="codigo_nuts"
featureidkey="properties.NUTS_ID"

In [ ]:
# Códigos NUTS3 que tenemos en la data
codigos_data_nuts3 = set(resumen_nuts3["codigo_nuts"].dropna().astype(str))

# Códigos NUTS3 disponibles en el GeoJSON de España
codigos_geojson_nuts3 = set(
    feature["properties"]["NUTS_ID"]
    for feature in geojson_nuts3_es["features"]
)

# Códigos de la data que NO están en el GeoJSON
codigos_no_en_geojson = codigos_data_nuts3 - codigos_geojson_nuts3

codigos_no_en_geojson

In [ ]:
resumen_nuts3[
    resumen_nuts3["codigo_nuts"].isin(codigos_no_en_geojson)
][["codigo_nuts", "nombre_region"]]

In [ ]:
len(codigos_data_nuts3), len(codigos_data_nuts3 & codigos_geojson_nuts3)

In [ ]:
resumen_nuts3.head()

In [ ]:
resumen_nuts3 = (
    df_nuts3
    .groupby(["codigo_nuts", "nombre_region"])
    .agg(
        n_licitaciones=("licitacion_id", "count"),
        ticket_promedio=("importe_sin_impuestos", "mean"),
        volumen_total=("importe_sin_impuestos", "sum")
    )
    .reset_index()
)

In [ ]:
import plotly.express as px

fig = px.choropleth(
    resumen_nuts3,
    geojson=geojson_nuts3_es,
    locations="codigo_nuts",
    featureidkey="properties.NUTS_ID",
    color="volumen_total",

    hover_name="nombre_region",

    hover_data={
        "volumen_total": ":,.0f",
        "n_licitaciones": ":,",
        "ticket_promedio": ":,.0f",
        "codigo_nuts": False
    },

    color_continuous_scale="Viridis",

    title="Volumen económico de licitaciones sanitarias por región NUTS3"
)

# Bordes internos
fig.update_traces(
    marker_line_width=1,
    marker_line_color="black"
)

# Configuración geográfica
fig.update_geos(

    fitbounds="locations",

    projection_type="mercator",

    visible=True,

    showcountries=True,
    countrycolor="black",
    countrywidth=2,

    showcoastlines=True,
    coastlinecolor="black",

    showland=True,
    landcolor="white",

    showocean=False,
    showlakes=False,

    bgcolor="white"
)

# Layout
fig.update_layout(

    title={
        "x": 0.5,
        "xanchor": "center"
    },

    paper_bgcolor="white",
    plot_bgcolor="white",

    margin={
        "r": 0,
        "t": 60,
        "l": 0,
        "b": 0
    },

    coloraxis_colorbar={
        "title": "Importe (€)",
        "tickformat": ".2s"
    }
)

fig.show()

Con el objetivo de profundizar en la estructura territorial del mercado sanitario público español, se desarrolló un segundo nivel de análisis geográfico utilizando regiones NUTS3, correspondientes principalmente a provincias y subregiones administrativas. Este nivel permitió identificar hotspots operativos reales de contratación sanitaria y evaluar la concentración territorial con un mayor nivel de granularidad.

Previo al análisis espacial, se realizó una validación de integridad geográfica entre los códigos NUTS presentes en la base de licitaciones y el archivo cartográfico oficial europeo (GeoJSON NUTS3). El cruce presentó una cobertura prácticamente completa, identificándose coincidencia espacial para 52 de los 53 códigos territoriales detectados. El único código no representado cartográficamente correspondió a la categoría “Extra-Regio NUTS3” (ESZZZ), la cual no representa una región física específica sino actividad territorial no asignable a una provincia concreta. Esta validación permitió garantizar consistencia espacial y confiabilidad en las visualizaciones geográficas posteriores.

Los resultados evidencian una concentración territorial extremadamente marcada de la contratación sanitaria. Madrid se posiciona como el principal núcleo operativo y económico del mercado sanitario español, concentrando simultáneamente el mayor número de licitaciones y el mayor volumen económico agregado. Este comportamiento sugiere una fuerte centralización administrativa y operativa de la contratación pública sanitaria.

Barcelona aparece como el segundo gran hub sanitario nacional, presentando también altos niveles de recurrencia y volumen económico. Sin embargo, el ticket promedio observado es considerablemente menor respecto a otras provincias líderes, lo que podría indicar una estructura contractual más fragmentada y distribuida.

Uno de los hallazgos más relevantes del análisis territorial es la fuerte presencia de múltiples provincias andaluzas dentro de las regiones con mayor volumen económico. Sevilla, Málaga, Jaén, Córdoba, Almería, Granada y Cádiz aparecen simultáneamente dentro de los principales focos territoriales del mercado sanitario. Este patrón sugiere que Andalucía no depende de una única provincia dominante, sino de una red territorial sanitaria ampliamente distribuida.

Sevilla destaca particularmente dentro del conjunto analizado. Además de ubicarse entre las regiones con mayor volumen económico, presenta el ticket promedio más alto del mercado sanitario provincial, superando los tres millones de euros por licitación. Esto posiciona a Sevilla como uno de los territorios estratégicamente más relevantes del sistema sanitario público español, combinando simultáneamente recurrencia, volumen económico y contratos de gran magnitud.

Galicia también presenta una dinámica territorial diferenciada. Provincias como A Coruña, Pontevedra y Ourense muestran una participación activa y distribuida dentro del mercado sanitario. A diferencia de otros territorios altamente centralizados, Galicia evidencia una estructura sanitaria regional más descentralizada, con actividad significativa en múltiples provincias.

El mapa geográfico provincial confirma visualmente la existencia de hotspots sanitarios claramente definidos. Las mayores concentraciones económicas se localizan principalmente en Madrid, Barcelona y diversas provincias andaluzas, mientras que el resto del territorio presenta niveles de actividad considerablemente inferiores. Este patrón espacial confirma la existencia de un mercado sanitario territorialmente heterogéneo y altamente concentrado.

Finalmente, el análisis NUTS3 permitió identificar territorios estratégicamente prioritarios para futuras iniciativas de participación competitiva dentro del sector sanitario. Regiones como Madrid, Barcelona y Sevilla emergen como núcleos críticos de contratación pública sanitaria, mientras que Andalucía en conjunto evidencia una estructura territorial especialmente atractiva debido a la coexistencia de alto volumen económico y elevada recurrencia operativa.

In [ ]:
df_salud = df_eda[
    df_eda["cpv_codes"]
    .astype(str)
    .str.startswith("851")
].copy()

In [ ]:
df_salud.shape