In [53]:
import pandas as pd

ruta = "../data/Silver/Inventario_Documentos_Licitaciones_Los_Tilos.xlsx"

excel = pd.ExcelFile(ruta)

print(excel.sheet_names)

['Inventario Completo', 'Resumen por Carpeta', 'Resumen por Categoría', 'Distribucion de formato']

In [54]:
inventario = pd.read_excel(
    ruta,
    sheet_name="Inventario Completo"
)

print(inventario.shape)

inventario.head()

(274, 9)

,Carpeta / Expediente,Organismo,Año,Descripción de la licitación,N°,Nombre del documento,Categoría,Formato,Tamaño (KB)
0,07_INSS_Reconocimientos_Medicos_2025,INSS,2025,Reconocimientos médicos personal INSS,1,Acta_Mesa_Contratacion_n1.pdf,Acta mesa contratación,PDF,436.1
1,07_INSS_Reconocimientos_Medicos_2025,INSS,2025,Reconocimientos médicos personal INSS,2,Acta_Mesa_Contratacion_n2.pdf,Acta mesa contratación,PDF,442.5
2,07_INSS_Reconocimientos_Medicos_2025,INSS,2025,Reconocimientos médicos personal INSS,3,Anuncio_Formalizacion.pdf,Anuncio formalización,PDF,91.1
3,07_INSS_Reconocimientos_Medicos_2025,INSS,2025,Reconocimientos médicos personal INSS,4,Anuncio_Formalizacion_02.pdf,Anuncio formalización,PDF,85.1
4,07_INSS_Reconocimientos_Medicos_2025,INSS,2025,Reconocimientos médicos personal INSS,5,Anuncio_de_Licitacion.pdf,Anuncio licitación,PDF,88.5

In [55]:
inventario.columns.tolist()

['Carpeta / Expediente',
 'Organismo',
 'Año',
 'Descripción de la licitación',
 'N°',
 'Nombre del documento',
 'Categoría',
 'Formato',
 'Tamaño (KB)']

In [56]:
resumen = pd.read_excel(
    ruta,
    sheet_name="Resumen por Carpeta"
)

print(resumen.shape)

resumen.head(20)

(15, 7)

,Carpeta,Organismo,Año,Descripción de la licitación,Total docs,Formatos,Categorías presentes
0,07_INSS_Reconocimientos_Medicos_2025,INSS,2025,Reconocimientos médicos personal INSS,21,"DOCX, PDF","Acta mesa contratación, Anuncio formalización,..."
1,10_INSS_Reconocimientos_Medicos_2023,INSS,2023,Reconocimientos médicos personal INSS,16,"DOCX, PDF","Anuncio formalización, Anuncio licitación, Can..."
2,11_TGSS_Reconocimientos_Medicos_2023,TGSS,2023,Reconocimientos médicos empleados TGSS/UPI/Int...,18,"DOCX, PDF","Anuncio formalización, Cancelación adjudicació..."
3,12_SACYL_Ecografias_Segovia_2023,SACYL,2023,Procedimientos diagnósticos mediante ultrasoni...,18,PDF,"Acta mesa contratación, Anuncio formalización,..."
4,13_FREMAP_RMN_Avila_Burgos_Salamanca_Segovia_2023,FREMAP,2023,"Resonancias magnéticas en Ávila, Burgos, Salam...",26,"PDF, XLSX, XML","Anexo, Anexo LOPD, Anexo nomenclator, Anexo se..."
5,14_UMIVALE_Asistencia_Ambulatoria_Segovia_2023,UMIVALE,2023,Asistencia ambulatoria y fisioterapia en Segovia,17,"DOCX, PDF, XLSM","Acta mesa contratación, Anuncio formalización,..."
6,15_FREMAP_Asistencia_Sanitaria_Especializada_C...,FREMAP,2023,Asistencia Sanitaria Especializada CyL y Canta...,6,PDF,"Anuncio licitación, Convocatoria adjudicación,..."
7,16_TGSS_Reconocimientos_Medicos_2024,TGSS,2024,Reconocimientos médicos laboral y oftalmológic...,15,"DOCX, PDF","Acta mesa contratación, Anuncio licitación, Co..."
8,17_FREMAP_Electromiografias_Segovia_2024,FREMAP,2024,Pruebas de electromiografías en Segovia,16,"DOC, PDF, XLS","Anexo, Anuncio formalización, Anuncio licitaci..."
9,18_SACYL_Procedimientos_Quirurgicos_Diagnostic...,SACYL,2024,Procedimientos quirúrgicos y diagnósticos GAS ...,23,PDF,"Acta mesa contratación, Anuncio licitación, Ca..."
10,20_SACYL_Procedimientos_Diagnosticos_Ecografia...,SACYL,2025,Procedimientos diagnósticos — ecografías e ima...,18,"DOCX, PDF","Acta mesa contratación, Anexo, Anuncio formali..."
11,21_FREMAP_RMN_Burgos_Salamanca_Segovia_2025,FREMAP,2025,"Radiodiagnóstico RMN en Burgos, Salamanca y Se...",33,"PDF, XLSX","Acta mesa contratación, Anexo, Anexo LOPD, Ane..."
12,22_TGSS_Reconocimientos_Medicos_2025,TGSS,2025,Reconocimientos médicos empleados TGSS/Interve...,24,"DOCX, PDF","Acta mesa contratación, Anuncio formalización,..."
13,23_FREMAP_Pruebas_Diagnosticas_CyL_2024_2025,FREMAP,2024-2025,Pruebas diagnósticas Castilla y León,23,"PDF, XLSX, XML","Acta mesa contratación, Anexo grupo de empresa..."
14,TOTAL,NaN,NaN,NaN,274,NaN,NaN

In [57]:
resumen.columns.tolist()

['Carpeta',
 'Organismo',
 'Año',
 'Descripción de la licitación',
 'Total docs',
 'Formatos',
 'Categorías presentes']

In [58]:
inventario.columns.tolist()

resumen.columns.tolist()

resumen.head(10)

,Carpeta,Organismo,Año,Descripción de la licitación,Total docs,Formatos,Categorías presentes
0,07_INSS_Reconocimientos_Medicos_2025,INSS,2025,Reconocimientos médicos personal INSS,21,"DOCX, PDF","Acta mesa contratación, Anuncio formalización,..."
1,10_INSS_Reconocimientos_Medicos_2023,INSS,2023,Reconocimientos médicos personal INSS,16,"DOCX, PDF","Anuncio formalización, Anuncio licitación, Can..."
2,11_TGSS_Reconocimientos_Medicos_2023,TGSS,2023,Reconocimientos médicos empleados TGSS/UPI/Int...,18,"DOCX, PDF","Anuncio formalización, Cancelación adjudicació..."
3,12_SACYL_Ecografias_Segovia_2023,SACYL,2023,Procedimientos diagnósticos mediante ultrasoni...,18,PDF,"Acta mesa contratación, Anuncio formalización,..."
4,13_FREMAP_RMN_Avila_Burgos_Salamanca_Segovia_2023,FREMAP,2023,"Resonancias magnéticas en Ávila, Burgos, Salam...",26,"PDF, XLSX, XML","Anexo, Anexo LOPD, Anexo nomenclator, Anexo se..."
5,14_UMIVALE_Asistencia_Ambulatoria_Segovia_2023,UMIVALE,2023,Asistencia ambulatoria y fisioterapia en Segovia,17,"DOCX, PDF, XLSM","Acta mesa contratación, Anuncio formalización,..."
6,15_FREMAP_Asistencia_Sanitaria_Especializada_C...,FREMAP,2023,Asistencia Sanitaria Especializada CyL y Canta...,6,PDF,"Anuncio licitación, Convocatoria adjudicación,..."
7,16_TGSS_Reconocimientos_Medicos_2024,TGSS,2024,Reconocimientos médicos laboral y oftalmológic...,15,"DOCX, PDF","Acta mesa contratación, Anuncio licitación, Co..."
8,17_FREMAP_Electromiografias_Segovia_2024,FREMAP,2024,Pruebas de electromiografías en Segovia,16,"DOC, PDF, XLS","Anexo, Anuncio formalización, Anuncio licitaci..."
9,18_SACYL_Procedimientos_Quirurgicos_Diagnostic...,SACYL,2024,Procedimientos quirúrgicos y diagnósticos GAS ...,23,PDF,"Acta mesa contratación, Anuncio licitación, Ca..."

In [59]:
import pandas as pd

ruta = "../data/Silver/Inventario_Documentos_Licitaciones_Los_Tilos.xlsx"

licitaciones = pd.read_excel(
    ruta,
    sheet_name="Resumen por Carpeta"
)

licitaciones = licitaciones[
    licitaciones["Carpeta"] != "TOTAL"
]

licitaciones.head()

,Carpeta,Organismo,Año,Descripción de la licitación,Total docs,Formatos,Categorías presentes
0,07_INSS_Reconocimientos_Medicos_2025,INSS,2025,Reconocimientos médicos personal INSS,21,"DOCX, PDF","Acta mesa contratación, Anuncio formalización,..."
1,10_INSS_Reconocimientos_Medicos_2023,INSS,2023,Reconocimientos médicos personal INSS,16,"DOCX, PDF","Anuncio formalización, Anuncio licitación, Can..."
2,11_TGSS_Reconocimientos_Medicos_2023,TGSS,2023,Reconocimientos médicos empleados TGSS/UPI/Int...,18,"DOCX, PDF","Anuncio formalización, Cancelación adjudicació..."
3,12_SACYL_Ecografias_Segovia_2023,SACYL,2023,Procedimientos diagnósticos mediante ultrasoni...,18,PDF,"Acta mesa contratación, Anuncio formalización,..."
4,13_FREMAP_RMN_Avila_Burgos_Salamanca_Segovia_2023,FREMAP,2023,"Resonancias magnéticas en Ávila, Burgos, Salam...",26,"PDF, XLSX, XML","Anexo, Anexo LOPD, Anexo nomenclator, Anexo se..."

In [60]:
inventario = pd.read_excel(
    ruta,
    sheet_name="Inventario Completo"
)

inventario["Categoría"].value_counts()

Categoría
Cancelación adjudicación          23
Acta mesa contratación            22
Oferta económica                  20
Anuncio formalización             19
Pliego técnico                    17
Convocatoria adjudicación         16
Otro                              16
Anuncio licitación                14
Resolución aprobación             13
Anexo                             13
Memoria justificativa             12
Pliego administrativo             10
Informe insuf. medios              8
DEUC                               7
Resolución de inicio               7
Doc. 1 — Declaración               6
Declaración responsable            4
Resolución adjudicación            4
Doc. 2 — Declaración               3
Nota informativa mesa              3
Doc. 3 — Declaración               3
Designación mesa contrat.          3
Anexo nomenclator                  3
Publicación recurso                3
Pliego condiciones                 3
Anexo LOPD                         3
Anexo requisitos empresa           2
Requerimiento                      2
Anexo servicios oblig./opc.        2
Declaración art. 71 LCSP           1
Informe criterios valoración       1
Contrato formalizado               1
Declaración adscripción medios     1
Notificación adjudicación          1
Oferta técnica                     1
Descripción servicios              1
TFM / Entrega                      1
Informe técnico valoración         1
Anexo grupo de empresas            1
Composición órgano apertura        1
Listado licitadores                1
Nota rectificación pliego          1
Name: count, dtype: int64

In [61]:
pliegos = inventario[
    inventario["Nombre del documento"]
    .str.contains(
        "pliego|pcap|ppt|tecnico|administrativo",
        case=False,
        na=False
    )
]

pliegos[
    [
        "Carpeta / Expediente",
        "Nombre del documento"
    ]
]

,Carpeta / Expediente,Nombre del documento
16,07_INSS_Reconocimientos_Medicos_2025,Pliego_Clausulas_Administrativas.pdf
17,07_INSS_Reconocimientos_Medicos_2025,Pliego_Prescripciones_Tecnicas.pdf
33,10_INSS_Reconocimientos_Medicos_2023,Pliego_Clausulas_Administrativas.pdf
34,10_INSS_Reconocimientos_Medicos_2023,Pliego_Prescripciones_Tecnicas.pdf
51,11_TGSS_Reconocimientos_Medicos_2023,Pliego_Prescripciones_Tecnicas.pdf
68,12_SACYL_Ecografias_Segovia_2023,Pliego_Clausulas_Administrativas.pdf
69,12_SACYL_Ecografias_Segovia_2023,Pliego_Prescripciones_Tecnicas.pdf
70,12_SACYL_Ecografias_Segovia_2023,Pliego_Prescripciones_Tecnicas_02.pdf
94,13_FREMAP_RMN_Avila_Burgos_Salamanca_Segovia_2023,Pliego_Condiciones_Particulares.pdf
95,13_FREMAP_RMN_Avila_Burgos_Salamanca_Segovia_2023,Pliego_Prescripciones_Tecnicas.pdf
113,14_UMIVALE_Asistencia_Ambulatoria_Segovia_2023,Pliego_Clausulas_Administrativas.pdf
114,14_UMIVALE_Asistencia_Ambulatoria_Segovia_2023,Pliego_Prescripciones_Tecnicas.pdf
118,15_FREMAP_Asistencia_Sanitaria_Especializada_C...,Pliego_Clausulas_Administrativas.pdf
119,15_FREMAP_Asistencia_Sanitaria_Especializada_C...,Pliego_Prescripciones_Tecnicas.pdf
133,16_TGSS_Reconocimientos_Medicos_2024,Pliego_Clausulas_Administrativas.pdf
134,16_TGSS_Reconocimientos_Medicos_2024,Pliego_Prescripciones_Tecnicas.pdf
147,17_FREMAP_Electromiografias_Segovia_2024,Pliego_Clausulas_Administrativas.pdf
148,17_FREMAP_Electromiografias_Segovia_2024,Pliego_Prescripciones_Tecnicas.pdf
158,18_SACYL_Procedimientos_Quirurgicos_Diagnostic...,B5_02___Resolucion_aprobacion_pliego_2.pdf
159,18_SACYL_Procedimientos_Quirurgicos_Diagnostic...,B5_03_Resolucion_Anular_pliegos_y_retrotraer_a...
167,18_SACYL_Procedimientos_Quirurgicos_Diagnostic...,Informe_Tecnico_Valoracion.pdf
170,18_SACYL_Procedimientos_Quirurgicos_Diagnostic...,Pliego_Clausulas_Administrativas.pdf
171,18_SACYL_Procedimientos_Quirurgicos_Diagnostic...,Pliego_Prescripciones_Tecnicas.pdf
172,18_SACYL_Procedimientos_Quirurgicos_Diagnostic...,Pliego_Prescripciones_Tecnicas_02.pdf
173,18_SACYL_Procedimientos_Quirurgicos_Diagnostic...,Pliego_Prescripciones_Tecnicas_03.pdf
174,18_SACYL_Procedimientos_Quirurgicos_Diagnostic...,Pliego_Prescripciones_Tecnicas_04.pdf
191,20_SACYL_Procedimientos_Diagnosticos_Ecografia...,Pliego_Clausulas_Administrativas.pdf
192,20_SACYL_Procedimientos_Diagnosticos_Ecografia...,Pliego_Prescripciones_Tecnicas.pdf
246,22_TGSS_Reconocimientos_Medicos_2025,Pliego_Clausulas_Administrativas.pdf
247,22_TGSS_Reconocimientos_Medicos_2025,Pliego_Prescripciones_Tecnicas.pdf
265,23_FREMAP_Pruebas_Diagnosticas_CyL_2024_2025,Nota_Rectificacion_Pliego.pdf
268,23_FREMAP_Pruebas_Diagnosticas_CyL_2024_2025,Pliego_Condiciones_Particulares.pdf
269,23_FREMAP_Pruebas_Diagnosticas_CyL_2024_2025,Pliego_Condiciones_Particulares_02.pdf
270,23_FREMAP_Pruebas_Diagnosticas_CyL_2024_2025,Pliego_Prescripciones_Tecnicas.pdf

In [62]:
import pdfplumber

def extraer_pdf(ruta_pdf):

    texto = ""

    try:

        with pdfplumber.open(ruta_pdf) as pdf:

            for pagina in pdf.pages:

                texto += (
                    pagina.extract_text() or ""
                )

    except Exception as e:

        print(e)

    return texto

In [63]:
from pathlib import Path

carpeta_base = Path("../data/Silver/Licitaciones")

registros = []

for pdf in carpeta_base.rglob("*.pdf"):

    texto = extraer_pdf(pdf)

    registros.append({
        "archivo": pdf.name,
        "ruta": str(pdf),
        "texto": texto
    })

pdfs = pd.DataFrame(registros)

pdfs.head()

,archivo,ruta,texto
0,Acta_Mesa_Contratacion_n1.pdf,..\data\Silver\Licitaciones\07_INSS_Reconocimi...,SECRETARIA DE ESTADO\nDE LA SEGURIDAD SOCIAL\n...
1,Acta_Mesa_Contratacion_n2.pdf,..\data\Silver\Licitaciones\07_INSS_Reconocimi...,SECRETARIA DE ESTADO\nDE LA SEGURIDAD SOCIAL\n...
2,Anuncio_de_Licitacion.pdf,..\data\Silver\Licitaciones\07_INSS_Reconocimi...,Anuncio de licitación\nNúmero de Expediente 40...
3,Anuncio_Formalizacion.pdf,..\data\Silver\Licitaciones\07_INSS_Reconocimi...,Anuncio de formalización de contrato\nNúmero d...
4,Anuncio_Formalizacion_02.pdf,..\data\Silver\Licitaciones\07_INSS_Reconocimi...,Anuncio de formalización de contrato\nNúmero d...

In [65]:
pdfs["expediente"] = (
    pdfs["ruta"]
    .str.split("\\")
    .str[-2]
)

In [66]:
pdfs[["expediente","archivo"]].head()

                             expediente                        archivo
0  07_INSS_Reconocimientos_Medicos_2025  Acta_Mesa_Contratacion_n1.pdf
1  07_INSS_Reconocimientos_Medicos_2025  Acta_Mesa_Contratacion_n2.pdf
2  07_INSS_Reconocimientos_Medicos_2025      Anuncio_de_Licitacion.pdf
3  07_INSS_Reconocimientos_Medicos_2025      Anuncio_Formalizacion.pdf
4  07_INSS_Reconocimientos_Medicos_2025   Anuncio_Formalizacion_02.pdf

In [67]:
texto_licitaciones = (
    pdfs
    .groupby("expediente")["texto"]
    .sum()
    .reset_index()
)

In [68]:
texto_licitaciones.shape

(14, 2)

In [69]:
texto_licitaciones["num_caracteres"] = (
    texto_licitaciones["texto"]
    .str.len()
)

texto_licitaciones[
    ["expediente","num_caracteres"]
].sort_values(
    "num_caracteres",
    ascending=False
)

                                           expediente  num_caracteres
9   18_SACYL_Procedimientos_Quirurgicos_Diagnostic...          713385
6   15_FREMAP_Asistencia_Sanitaria_Especializada_C...          450134
10  20_SACYL_Procedimientos_Diagnosticos_Ecografia...          396534
13       23_FREMAP_Pruebas_Diagnosticas_CyL_2024_2025          380166
5      14_UMIVALE_Asistencia_Ambulatoria_Segovia_2023          359792
8            17_FREMAP_Electromiografias_Segovia_2024          322316
4   13_FREMAP_RMN_Avila_Burgos_Salamanca_Segovia_2023          321908
0                07_INSS_Reconocimientos_Medicos_2025          309920
12               22_TGSS_Reconocimientos_Medicos_2025          300321
11        21_FREMAP_RMN_Burgos_Salamanca_Segovia_2025          265341
1                10_INSS_Reconocimientos_Medicos_2023          256919
3                    12_SACYL_Ecografias_Segovia_2023          245733
7                16_TGSS_Reconocimientos_Medicos_2024          205020
2                11_TGSS_Reconocimientos_Medicos_2023          110135

In [70]:
texto_licitaciones.iloc[0]["texto"][:5000]

'SECRETARIA DE ESTADO\nDE LA SEGURIDAD SOCIAL\nY PENSIONES\nDirección Provincial de Segovia\nSecretaría Provincial\nACTA N.º 1 DE LA UNIDAD DE ASISTENCIA TECNICA\nFecha y hora de celebración\n18 de julio de 2025 a las 09:07:00\nLugar de celebración\nSala de juntas de la secretaria provincial\nAsistentes\nSECRETARIO\nDña. Elena Sancho Sanz, Jefa de Sección\nVOCAL\nD./Dña. Tomasz Marek Zydorczyk, Jefe de negociado\nOrden del día\n1.- Acto de apertura oferta criterios cuantificables automáticamente (art. 159): 40/VC-184/25 - Servicio de\nreconocimientos médicos personal adscrito al INSS\n2.- Acto de valoración oferta criterios cuantificables automáticamente (art. 159): 40/VC-184/25 - Servicio de\nreconocimientos médicos personal adscrito al INSS\n3.- Propuesta adjudicación: 40/VC-184/25 - Servicio de reconocimientos médicos personal adscrito al INSS\n4.- Mejor valorado - Requerimiento de documentación: 40/VC-184/25 - Servicio de reconocimientos\nmédicos personal adscrito al INSS\nSe Expone:\n1.- Acto de apertura oferta criterios cuantificables automáticamente (art. 159): 40/VC-184/25 -\nServicio de reconocimientos médicos personal adscrito al INSS\nHan concurrido las siguientes empresas:\nNIF EMPRESA FECHA DE PRESENTACIÓN\nB98844574 ASPY PREVENCION.S.L.U 17 de julio de 2025 a las 09:41:54\nB40227019 HOSPITAL RECOLETAS 09 de julio de 2025 a las 14:05:34\nSEGOVIA NUESTRA SEÑORA DE\nLA MISERICORDIA\nB64076482 QUIRON PREVENCION S.L.U 16 de julio de 2025 a las 11:48:32\nA40213217 TILOSALUD, S.A. 11 de julio de 2025 a las 11:08:16\nB06290241 VITALY HEALTH SERVICES, SL 15 de julio de 2025 a las 11:28:52\nTras la revisión de la documentación aportada por los licitadores la mesa concluye admitir a todos los\nlicitadores.\n6\nCalle Pinar de Valsaín, nº 1\nPágina 1 de 5 buzon.inss-segovia.licitaciones@seg-social.es 40005 - SEGOVIA\nTel.: 921 41 44 52\nCódigo DIR3: EA00421822.- Acto de valoración oferta criterios cuantificables automáticamente (art. 159): 40/VC-184/25 -\nServicio de reconocimientos médicos personal adscrito al INSS\nUna vez remitida la información por el equipo técnico, éste ha valorado las proposiciones técnicas de\nacuerdo a los criterios del PCAP de la siguiente manera:\nLOTE 1\nempresa nif precio Puntos precio Hierro y SOH T4 libre Vitamina D Amilasa y Gesión TOTAL\nFerritina lipasa de citas\nResultados\nPlataforma\ndigital\nsegura\nPuntuación =\n55-\n(55*(oferta\nempresa-\nmejor\noferta)/mejor 15\noferta)) 5 ptos 5 ptos 5 ptos 5 ptos 5 ptos 5 ptos ptos.\nQUIRON PREVENCION\nS.L.U B64076482 52,90 € 48,10 5 5 5 0 5 5 15 88,10\nVITALY HEALTH\nSERVICES, SL B06290241 56,71 € 43,64 5 5 5 0 5 5 15 83,64\nASPY PREVENCIÓN,\nS.L.U B98844574 47,00 € 55,00 5 5 5 0 0 5 15 90,00\nLOTE 2\nEmpresa nif precio puntuación precio Valoración Gesión de Total\nfoniátrica citas\nResultados\nPlataforma\ndigital segura\n5 ptos 5 ptos 15 ptos.\nPuntuación = 75-(75*(oferta\nempresa-mejor\noferta)/mejor oferta))\nTILOSALUD A40213217 € 55,00 75,00 5 5 15 100,00\nHOSPITAL RECOLETAS SEGOVIA\nNUESTRA SEÑORA DE LA B40227019 € 60,00 68,18 5 5 0 78,18\nMISERICORDIA SL\nLOTE 3\nempresa nif precio Puntuación Resultados Gesión de\nprecio Plataforma citas\ndigital\nsegura\n5 ptos 15 ptos.\nTOTAL\nPuntuación =\n80-(80*(oferta\nempresa-mejor\noferta)/mejor\noferta))\nA4021321\n76,80 5 15 96,80\nTILOSALUD, S.A. 7 104,00 €\nHOSPITAL RECOLETAS\nB4022701\nSEGOVIA NUESTRA SEÑORA 80,00 5 0 85,00\n9 100,00 €\nDE LA MISERICORDIA SL\nMINISTERIO\nDE INCLUSIÓN, MIGRACIONES\nY SEGURIDAD SOCIAL\nPágina 2 de 5\nINSTITUTO NACIONAL\nDE LA SEGURIDAD SOCIALSECRETARIA DE ESTADO\nDE LA SEGURIDAD SOCIAL\nY PENSIONES\nDirección Provincial de Segovia\nSecretaría Provincial\nLOTE 4\nEmpresa nif precio Puntacion precio Gesión de Total\nResultados\ncitas\nPlataforma\ndigital\nsegura\nPuntuación = 80-\n(80*(oferta empresa-mejor\noferta)/mejor oferta)) 5 ptos 15 ptos.\n69,00\nTILOSALUD, S.A. A40213217 € 80,00 5 15 100,00\nHOSPITAL RECOLETAS\nSEGOVIA NUESTRA SEÑORA 72,00\nDE LA MISERICORDIA SL B40227019 € 76,52 5 0 81,52\n3.- Propuesta adjudicación: 40/VC-184/25 - Servicio de reconocimientos médicos personal adscrito al INSS\nDe acuerdo a la evaluación de las propuestas aportadas por los licitadores, la mesa concluye la siguiente lista\nordenada de manera decreciente de puntuación de acuerdo a las puntuaciones obtenidas por los licitadores en las\ndiferentes fases:\nLOTE 1\nempresa nif Puntos precio Hierro y SOH T4 libre Vitamina D Amilasa y Gesión TOTAL\nFerritina lipasa de citas\nResultados\nPlataforma\ndigital\nsegura\nPuntuación = 55-\n(55*(oferta\nempresa-mejor\noferta)/mejor 15\noferta)) 5 ptos 5 ptos 5 ptos 5 ptos 5 ptos 5 ptos ptos.\nQUIRON PREVENCION\nS.L.U B64076482 48,10 5 5 5 0 5 5 15 88,10\nVITALY HEALTH\nSERVICES, SL B06290241 43,64 5 5 5 0 5 5 15 83,64\nASPY PREVENCIÓN,\nS.L.U B98844574 55,00 5 5 5 0 0 5 15 90,00\n6\nCalle Pinar de Valsaín, nº 1\nPágina 3 de 5 buzon.inss-segovia.licitaciones@seg-social.es 40005 - SEGOVIA\nTel.: 921 41 44 52\nCódigo DIR3: EA0042182LOTE 2\nEmpresa nif puntuación precio Valoración Gesión de Total\nfoniátrica citas\nResultados\nPlataforma\ndigital segura\n5 ptos 5 ptos 15 ptos.\nPu'

In [71]:
inventario["Categoría"].value_counts()

Categoría
Cancelación adjudicación          23
Acta mesa contratación            22
Oferta económica                  20
Anuncio formalización             19
Pliego técnico                    17
Convocatoria adjudicación         16
Otro                              16
Anuncio licitación                14
Resolución aprobación             13
Anexo                             13
Memoria justificativa             12
Pliego administrativo             10
Informe insuf. medios              8
DEUC                               7
Resolución de inicio               7
Doc. 1 — Declaración               6
Declaración responsable            4
Resolución adjudicación            4
Doc. 2 — Declaración               3
Nota informativa mesa              3
Doc. 3 — Declaración               3
Designación mesa contrat.          3
Anexo nomenclator                  3
Publicación recurso                3
Pliego condiciones                 3
Anexo LOPD                         3
Anexo requisitos empresa           2
Requerimiento                      2
Anexo servicios oblig./opc.        2
Declaración art. 71 LCSP           1
Informe criterios valoración       1
Contrato formalizado               1
Declaración adscripción medios     1
Notificación adjudicación          1
Oferta técnica                     1
Descripción servicios              1
TFM / Entrega                      1
Informe técnico valoración         1
Anexo grupo de empresas            1
Composición órgano apertura        1
Listado licitadores                1
Nota rectificación pliego          1
Name: count, dtype: int64

In [72]:
pliegos = inventario[
    inventario["Categoría"].isin([
        "Pliego técnico",
        "Pliego administrativo"
    ])
].copy()

pliegos.shape

(27, 9)

In [73]:
pliegos[
    [
        "Carpeta / Expediente",
        "Nombre del documento",
        "Categoría"
    ]
].head(30)

,Carpeta / Expediente,Nombre del documento,Categoría
16,07_INSS_Reconocimientos_Medicos_2025,Pliego_Clausulas_Administrativas.pdf,Pliego administrativo
17,07_INSS_Reconocimientos_Medicos_2025,Pliego_Prescripciones_Tecnicas.pdf,Pliego técnico
33,10_INSS_Reconocimientos_Medicos_2023,Pliego_Clausulas_Administrativas.pdf,Pliego administrativo
34,10_INSS_Reconocimientos_Medicos_2023,Pliego_Prescripciones_Tecnicas.pdf,Pliego técnico
51,11_TGSS_Reconocimientos_Medicos_2023,Pliego_Prescripciones_Tecnicas.pdf,Pliego técnico
68,12_SACYL_Ecografias_Segovia_2023,Pliego_Clausulas_Administrativas.pdf,Pliego administrativo
69,12_SACYL_Ecografias_Segovia_2023,Pliego_Prescripciones_Tecnicas.pdf,Pliego técnico
70,12_SACYL_Ecografias_Segovia_2023,Pliego_Prescripciones_Tecnicas_02.pdf,Pliego técnico
95,13_FREMAP_RMN_Avila_Burgos_Salamanca_Segovia_2023,Pliego_Prescripciones_Tecnicas.pdf,Pliego técnico
113,14_UMIVALE_Asistencia_Ambulatoria_Segovia_2023,Pliego_Clausulas_Administrativas.pdf,Pliego administrativo
114,14_UMIVALE_Asistencia_Ambulatoria_Segovia_2023,Pliego_Prescripciones_Tecnicas.pdf,Pliego técnico
118,15_FREMAP_Asistencia_Sanitaria_Especializada_C...,Pliego_Clausulas_Administrativas.pdf,Pliego administrativo
119,15_FREMAP_Asistencia_Sanitaria_Especializada_C...,Pliego_Prescripciones_Tecnicas.pdf,Pliego técnico
133,16_TGSS_Reconocimientos_Medicos_2024,Pliego_Clausulas_Administrativas.pdf,Pliego administrativo
134,16_TGSS_Reconocimientos_Medicos_2024,Pliego_Prescripciones_Tecnicas.pdf,Pliego técnico
147,17_FREMAP_Electromiografias_Segovia_2024,Pliego_Clausulas_Administrativas.pdf,Pliego administrativo
148,17_FREMAP_Electromiografias_Segovia_2024,Pliego_Prescripciones_Tecnicas.pdf,Pliego técnico
170,18_SACYL_Procedimientos_Quirurgicos_Diagnostic...,Pliego_Clausulas_Administrativas.pdf,Pliego administrativo
171,18_SACYL_Procedimientos_Quirurgicos_Diagnostic...,Pliego_Prescripciones_Tecnicas.pdf,Pliego técnico
172,18_SACYL_Procedimientos_Quirurgicos_Diagnostic...,Pliego_Prescripciones_Tecnicas_02.pdf,Pliego técnico
173,18_SACYL_Procedimientos_Quirurgicos_Diagnostic...,Pliego_Prescripciones_Tecnicas_03.pdf,Pliego técnico
174,18_SACYL_Procedimientos_Quirurgicos_Diagnostic...,Pliego_Prescripciones_Tecnicas_04.pdf,Pliego técnico
191,20_SACYL_Procedimientos_Diagnosticos_Ecografia...,Pliego_Clausulas_Administrativas.pdf,Pliego administrativo
192,20_SACYL_Procedimientos_Diagnosticos_Ecografia...,Pliego_Prescripciones_Tecnicas.pdf,Pliego técnico
246,22_TGSS_Reconocimientos_Medicos_2025,Pliego_Clausulas_Administrativas.pdf,Pliego administrativo
247,22_TGSS_Reconocimientos_Medicos_2025,Pliego_Prescripciones_Tecnicas.pdf,Pliego técnico
270,23_FREMAP_Pruebas_Diagnosticas_CyL_2024_2025,Pliego_Prescripciones_Tecnicas.pdf,Pliego técnico

In [74]:
docs_pliegos = pliegos["Nombre del documento"].unique()

In [75]:
pdfs_pliegos = pdfs[
    pdfs["archivo"].isin(docs_pliegos)
].copy()

In [76]:
pdfs_pliegos.shape

(27, 4)

In [77]:
texto_pliegos = (
    pdfs_pliegos
    .groupby("expediente")["texto"]
    .sum()
    .reset_index()
)

In [78]:
texto_pliegos.shape

(13, 2)

In [79]:
print(
    texto_pliegos.iloc[0]["texto"][:10000]
)

PLIEGO SERVICIOS /PROC. ABIERTO SIMPLIFICADO ART. 159.6 LCSP/
EXPTE: 40/VC-184/25
LICITACIÓN ELECTRÓNICA
Calle Pinar de Valsaín, nª 1
Página 1 de 65 buzon.inss-segovia.licitaciones@seg-social.es 40005 - SEGOVIA
TEL.: 921 41 44 52
Código DIR3: EA0042182ÍNDICE
I. OBJETO DEL CONTRATO
II. NATURALEZA, RÉGIMEN JURÍDICO, DOCUMENTOS DE NATURALEZA CONTRACTUAL Y
JURISDICCIÓN
III. PRESUPUESTO BASE DE LICITACIÓN Y VALOR ESTIMADO DEL CONTRATO
IV. PROCEDIMIENTO Y CRITERIOS DE ADJUDICACIÓN
V. CAPACIDAD PARA CONTRATAR
VI. PRESENTACIÓN DE PROPOSICIONES
VII. PLAZO DE ADMISIÓN Y EXAMEN DE PROPOSICIONES POR LOS ÓRGANOS
COMPETENTES
VIII. ADJUDICACIÓN DEL CONTRATO Y GARANTÍA DEFINITIVA
IX. FORMALIZACIÓN DEL CONTRATO
X. PLAZO DE EJECUCIÓN DEL CONTRATO
XI. CONDICIONES DE EJECUCIÓN Y RECEPCIÓN
XII. PAGO DEL PRECIO Y PLAZO DE GARANTÍA
XIII. OBLIGACIONES DEL CONTRATISTA
XIV. PENALIDADES
XV. REVISIÓN DE PRECIOS
XVI. MODIFICACIÓN, CESIÓN Y SUBCONTRATACIÓN DEL CONTRATO
XVII. RESOLUCIÓN DEL CONTRATO
XVIII. PROTECCIÓN DE DATOS DE CARÁCTER PERSONAL
Documento n.º 1 DECLARACIÓN Y OFERTA
Documento n.º 2 DECLARACIÓN ART. 71 LCSP
Calle Pinar de Valsaín, nª 1
Página 2 de 65 buzon.inss-segovia.licitaciones@seg-social.es 40005 - SEGOVIA
TEL.: 921 41 44 52
Código DIR3: EA0042182SERVICIOS /Procedimiento abierto simplificado Art. 159.6 LCSP/ licitación
electrónica/
PLIEGO DE CLÁUSULAS ADMINISTRATIVAS PARTICULARES QUE HA DE REGIR LA
CONTRATACIÓN, POR PROCEDIMIENTO ABIERTO SIMPLIFICADO PREVISTO EN EL
ARTÍCULO 159.6 DE LA LCSP, DE LOS SERVICIOS DE RECONOCIMIENTO MÉDICO-
LABORAL GENERAL Y RECONOCIMIENTOS MÉDICOS DE OTORRINOLARINGOLOGÍA,
GINECOLOGÍA Y UROLOGÍA PARA EL PERSONAL QUE PRESTA SERVICIOS EN LA
DIRECCIÓN PROVINCIAL DEL INSTITUTO NACIONAL DE LA SEGURIDAD SOCIAL DE
SEGOVIA; EXPEDIENTE N.º: 40/VC-184/25. PERIODO 15/07/2025 A 30/06/2026
PRIMERA. - OBJETO DEL CONTRATO.
1.1 El contrato al que se refiere el presente pliego tiene por objeto la ejecución de los
servicios de reconocimiento médico-laboral general y reconocimientos médicos de
otorrinolaringología, ginecología y urología para el personal que presta servicios en
la Dirección Provincial del Instituto Nacional de la Seguridad Social de Segovia, que
se describen en el pliego de prescripciones técnicas que se acompaña, en el que se
han tenido en cuenta para su definición las consideraciones sociales, ambientales y
de innovación.
La necesidad e idoneidad del objeto descrito se acredita en el expediente
administrativo tramitado al efecto, quedando constancia en el mismo de que el
Instituto Nacional de la Seguridad Social (en adelante, INSS) carece de medios
propios para ejecutar la prestación que se contrata.
1.2 El objeto del presente expediente está dividido en lotes, conforme se deduce del
Pliego de prescripciones técnicas que se adjunta y conforme al número y
denominación que más abajo figura, pudiendo el licitador ofertar por uno o varios de
dichos lotes, siempre que resulten completos. De igual forma, en ningún caso se
condicionará la adjudicación de uno o varios lotes, a la circunstancia de resultar
adjudicatario de todos o de varios de ellos. En todo caso, cada lote constituirá un
contrato.
Los lotes en que se divide el objeto de este contrato, con indicación de la codificación
de la nomenclatura de Clasificación de Productos por Actividades (CPA) y del
Vocabulario Común de Contratos (CPV) de la Comisión Europea, son los siguientes:
Codificación Codificación
Lote Denominación
CPA CPV
Reconocimiento médico laboral con especial
1 86.21.10 85121100
atención al aparato musculoesquelético
2 Reconocimiento médico otorrinolaringológico 86.22.1 85121240
3 Reconocimiento médico ginecológico 86.22.1 85121210
4 Reconocimiento médico urológico 86.22.1 85121292
Calle Pinar de Valsaín, nª 1
Página 3 de 65 buzon.inss-segovia.licitaciones@seg-social.es 40005 - SEGOVIA
TEL.: 921 41 44 52
Código DIR3: EA00421821.3 En la definición del objeto del presente contrato se han tenido en cuenta las
consideraciones sociales, según lo previsto en el apartado 7.1 del Acuerdo del
Consejo de Ministros de 12 de abril de 2019, por el que se aprueba el Plan para el
impulso de la contratación pública socialmente responsable en el marco de la Ley
9/2017, de 8 de noviembre, de Contratos del Sector Público, publicado por Orden
PCI/566/2019, de 21 de mayo.
SEGUNDA. - NATURALEZA, RÉGIMEN JURÍDICO, DOCUMENTOS DE NATURALEZA
CONTRACTUAL Y JURISDICCIÓN.
2.1 El contrato al que se refiere el presente pliego tiene naturaleza administrativa,
calificándose de servicios, y se regirá, además de por lo establecido en el mismo, por
lo dispuesto en la Ley 9/2017, de 8 de noviembre, de Contratos del Sector Público,
por la que se transponen al ordenamiento jurídico español las Directivas del
Parlamento Europeo y del Consejo 2014/23/UE y 2014/24/UE, de 26 de febrero de
2014 (en adelante LCSP); por el Real Decreto 817/2009, de 8 de mayo, por el que
se desarrolla parcialmente la Ley 30/2007, de 30 de octubre, de Contratos del Sector
Público, en todo lo que no se oponga a la citada ley; por el Reglamento General de
la Ley de Contratos de las Administraciones Públicas, aprobado por Real Decreto
1098/2001, de 12 de octubre (en adelante, RGLCAP), en todo lo que no se oponga
a ambos; por el resto de normas de desarrollo en vigor, concordantes y
complementarias a aquélla, siempre que no se opongan a las normas citadas; y,
supletoriamente, por las restantes normas vigentes de derecho administrativo, y en
su defecto, de derecho privado.
2.2 El licitador acepta de forma expresa su sumisión a la legislación anteriormente citada,
a los pliegos de cláusulas administrativas generales que, en su caso, sean aplicables,
y al presente pliego de cláusulas administrativas particulares y de prescripciones
técnicas que rige este contrato.
2.3 La ejecución de este contrato se ajustará, además de a las previsiones contenidas
en el presente pliego y en el documento de formalización que se suscriba, a las
condiciones expresadas en el Pliego de prescripciones técnicas que se acompaña
como anexo a éste, y del que forma parte inseparable, y en todo lo que no se oponga
a ambos, a la proposición que formule el licitador que finalmente resulte adjudicatario;
estableciéndose, salvo caso de error material o manifiesto, la siguiente prelación en
el supuesto de que surjan contradicciones de contenido entre los diversos
documentos referidos:
a) Pliego de prescripciones técnicas (PPT).
b) Pliego de cláusulas administrativas particulares (PCAP).
c) Contrato a suscribir.
d) Proposición formulada por el licitador.
Calle Pinar de Valsaín, nª 1
Página 4 de 65 buzon.inss-segovia.licitaciones@seg-social.es 40005 - SEGOVIA
TEL.: 921 41 44 52
Código DIR3: EA0042182En relación con esta última, se dará asimismo preferencia, en caso de discrepancia,
a la cuantía expresada en letra, siempre que no existan importes unitarios que reflejar
como precios ciertos del contrato, en cuyo caso éstos se entenderán siempre
prevalentes e invariables.
2.4 Las cuestiones litigiosas surgidas sobre la interpretación, modificación, efectos y
resolución de este contrato, serán resueltas por el órgano de contratación. El orden
jurisdiccional contencioso administrativo será el competente para resolver las
controversias que surjan entre las partes, de conformidad con lo establecido en el
artículo 27 de la LCSP.
Atendiendo al valor estimado de este contrato, no cabe la interposición de recurso
especial en materia de contratación.
2.5 El expediente que ampara la presente contratación es de tramitación ordinaria, de
conformidad con lo previsto en el artículo 116 de la LCSP.
Los plazos establecidos por días en este pliego se entenderán referidos a días
naturales, salvo que en el mismo se indique expresamente que solo deben
computarse los días hábiles. No obstante, si el último día del plazo fuera inhábil, éste
se entenderá prorrogado al primer día hábil siguiente, de conformidad con la
Disposición Adicional 12ª de la LCSP.
TERCERA. - PRESUPUESTO BASE DE LICITACIÓN Y VALOR ESTIMADO DEL CONTRATO.
3.1 El presupuesto base de licitación de este contrato asciende a la cuantía total de
quince mil novecientos setenta y cinco euros (15.975,00 €), IVA exento, resultando
de aplicación el detalle que a continuación se refleja a efectos de su determinación:
➢ Presupuesto del contrato (IVA exento): 15.975,00 €
La prestación de este servicio está exenta de tributación del IVA, según se
establece en el artículo 20 de la Ley 37/1992, de 28 de diciembre, del IVA.
Por otra parte, el presupuesto base de licitación de cada lote es el siguiente:
Importe N.º máx. Importe
Lote Denominación IVA
unitario previsto total
Reconocimiento médico laboral con especial
1 70,00 € exento 72 5.040,00 €
atención al aparato musculoesquelético
2 Reconocimiento médico otorrinolaringológico 60,00 € exento 66 3.960,00 €
3 Reconocimiento médico ginecológico 120,00 € exento 45 5.400,00 €
4 Reconocimiento médico urológico 75,00 € exento 21 1.575,00 €
Total 15.975,00 €
Calle Pinar de Valsaín, nª 1
Página 5 de 65 buzon.inss-segovia.licitaciones@seg-social.es 40005 - SEGOVIA
TEL.: 921 41 44 52
Código DIR3: EA0042182De acuerdo con lo dispuesto en el artículo 100.2 de la LCSP, el citado presupuesto
base de licitación se ha determinado conforme al siguiente desglose de costes
directos e indirectos:
En el presente contrato se ha estimado un 15% de costes indirectos teniendo en
cuenta las peculiaridades de las empresas que prestan el servicio a contratar,
encuadradas dentro del ámbito sanitario y de la prevención de riesgos laborales, que
por razón de su actividad y de la naturaleza del servicio prestado necesitan unas
infraestructuras y un personal de administración que influyen en sus costes, como
son sus propias oficinas, las dependencias de atención al público, el equipamiento e
instalaciones de tipo sanitario, el equipamiento informático, software y acceso a
telecomunicaciones, entre otros, así como los costes indirectos del personal
administrativo, comercial y gerencial de

In [80]:
dataset = texto_pliegos.copy()

In [81]:
import re

def extraer_cpv(texto):

    cpv = re.findall(
        r"\d{8}-\d",
        str(texto)
    )

    return cpv[0] if cpv else None

In [82]:
dataset["cpv"] = (
    dataset["texto"]
    .apply(extraer_cpv)
)

In [83]:
def contar_cpvs(texto):

    return len(
        re.findall(
            r"\d{8}-\d",
            str(texto)
        )
    )

In [84]:
dataset["num_cpvs"] = (
    dataset["texto"]
    .apply(contar_cpvs)
)

In [85]:
dataset["iso_9001"] = (
    dataset["texto"]
    .str.lower()
    .str.contains("iso 9001")
    .astype(int)
)

dataset["iso_14001"] = (
    dataset["texto"]
    .str.lower()
    .str.contains("iso 14001")
    .astype(int)
)

In [86]:
dataset["solvencia"] = (
    dataset["texto"]
    .str.lower()
    .str.contains("solvencia")
    .astype(int)
)

In [87]:
dataset["experiencia"] = (
    dataset["texto"]
    .str.lower()
    .str.contains("experiencia")
    .astype(int)
)

In [89]:
especialidades = [
    "ecografia",
    "radiologia",
    "resonancia",
    "electromiografia",
    "fisioterapia",
    "reconocimientos medicos"
]

In [90]:
for esp in especialidades:

    dataset[esp] = (
        dataset["texto"]
        .str.lower()
        .str.contains(
            esp,
            na=False
        )
        .astype(int)
    )

In [91]:
from sentence_transformers import SentenceTransformer

modelo = SentenceTransformer(
    "paraphrase-multilingual-MiniLM-L12-v2"
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

c:\Users\sebas\AppData\Local\Programs\Python\Python314\Lib\site-packages\huggingface_hub\file_download.py:137: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\sebas\.cache\huggingface\hub\models--sentence-transformers--paraphrase-multilingual-MiniLM-L12-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.89k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/526 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [92]:
embeddings = modelo.encode(
    dataset["texto"].tolist(),
    show_progress_bar=True
)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [93]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=50,
    stop_words=None
)

X = vectorizer.fit_transform(
    dataset["texto"]
)

palabras = vectorizer.get_feature_names_out()

print(palabras)

['al' 'artículo' 'cada' 'caso' 'cid' 'como' 'con' 'contratación'
 'contratista' 'contrato' 'datos' 'de' 'deberá' 'del' 'documentación' 'ed'
 'ejecución' 'el' 'empresa' 'en' 'es' 'este' 'la' 'las' 'lcsp'
 'licitación' 'licitador' 'lo' 'los' 'no' 'objeto' 'oferta' 'para'
 'personal' 'plazo' 'pliego' 'por' 'procedimiento' 'que' 'salud' 'se'
 'segovia' 'seguridad' 'servicio' 'servicios' 'si' 'social' 'su' 'un'
 'una']

In [94]:
pdfs_pliegos.shape

texto_pliegos.shape

texto_pliegos.iloc[0]["texto"][:10000]

'PLIEGO SERVICIOS /PROC. ABIERTO SIMPLIFICADO ART. 159.6 LCSP/\nEXPTE: 40/VC-184/25\nLICITACIÓN ELECTRÓNICA\nCalle Pinar de Valsaín, nª 1\nPágina 1 de 65 buzon.inss-segovia.licitaciones@seg-social.es 40005 - SEGOVIA\nTEL.: 921 41 44 52\nCódigo DIR3: EA0042182ÍNDICE\nI. OBJETO DEL CONTRATO\nII. NATURALEZA, RÉGIMEN JURÍDICO, DOCUMENTOS DE NATURALEZA CONTRACTUAL Y\nJURISDICCIÓN\nIII. PRESUPUESTO BASE DE LICITACIÓN Y VALOR ESTIMADO DEL CONTRATO\nIV. PROCEDIMIENTO Y CRITERIOS DE ADJUDICACIÓN\nV. CAPACIDAD PARA CONTRATAR\nVI. PRESENTACIÓN DE PROPOSICIONES\nVII. PLAZO DE ADMISIÓN Y EXAMEN DE PROPOSICIONES POR LOS ÓRGANOS\nCOMPETENTES\nVIII. ADJUDICACIÓN DEL CONTRATO Y GARANTÍA DEFINITIVA\nIX. FORMALIZACIÓN DEL CONTRATO\nX. PLAZO DE EJECUCIÓN DEL CONTRATO\nXI. CONDICIONES DE EJECUCIÓN Y RECEPCIÓN\nXII. PAGO DEL PRECIO Y PLAZO DE GARANTÍA\nXIII. OBLIGACIONES DEL CONTRATISTA\nXIV. PENALIDADES\nXV. REVISIÓN DE PRECIOS\nXVI. MODIFICACIÓN, CESIÓN Y SUBCONTRATACIÓN DEL CONTRATO\nXVII. RESOLUCIÓN DEL CONTRATO\nXVIII. PROTECCIÓN DE DATOS DE CARÁCTER PERSONAL\nDocumento n.º 1 DECLARACIÓN Y OFERTA\nDocumento n.º 2 DECLARACIÓN ART. 71 LCSP\nCalle Pinar de Valsaín, nª 1\nPágina 2 de 65 buzon.inss-segovia.licitaciones@seg-social.es 40005 - SEGOVIA\nTEL.: 921 41 44 52\nCódigo DIR3: EA0042182SERVICIOS /Procedimiento abierto simplificado Art. 159.6 LCSP/ licitación\nelectrónica/\nPLIEGO DE CLÁUSULAS ADMINISTRATIVAS PARTICULARES QUE HA DE REGIR LA\nCONTRATACIÓN, POR PROCEDIMIENTO ABIERTO SIMPLIFICADO PREVISTO EN EL\nARTÍCULO 159.6 DE LA LCSP, DE LOS SERVICIOS DE RECONOCIMIENTO MÉDICO-\nLABORAL GENERAL Y RECONOCIMIENTOS MÉDICOS DE OTORRINOLARINGOLOGÍA,\nGINECOLOGÍA Y UROLOGÍA PARA EL PERSONAL QUE PRESTA SERVICIOS EN LA\nDIRECCIÓN PROVINCIAL DEL INSTITUTO NACIONAL DE LA SEGURIDAD SOCIAL DE\nSEGOVIA; EXPEDIENTE N.º: 40/VC-184/25. PERIODO 15/07/2025 A 30/06/2026\nPRIMERA. - OBJETO DEL CONTRATO.\n1.1 El contrato al que se refiere el presente pliego tiene por objeto la ejecución de los\nservicios de reconocimiento médico-laboral general y reconocimientos médicos de\notorrinolaringología, ginecología y urología para el personal que presta servicios en\nla Dirección Provincial del Instituto Nacional de la Seguridad Social de Segovia, que\nse describen en el pliego de prescripciones técnicas que se acompaña, en el que se\nhan tenido en cuenta para su definición las consideraciones sociales, ambientales y\nde innovación.\nLa necesidad e idoneidad del objeto descrito se acredita en el expediente\nadministrativo tramitado al efecto, quedando constancia en el mismo de que el\nInstituto Nacional de la Seguridad Social (en adelante, INSS) carece de medios\npropios para ejecutar la prestación que se contrata.\n1.2 El objeto del presente expediente está dividido en lotes, conforme se deduce del\nPliego de prescripciones técnicas que se adjunta y conforme al número y\ndenominación que más abajo figura, pudiendo el licitador ofertar por uno o varios de\ndichos lotes, siempre que resulten completos. De igual forma, en ningún caso se\ncondicionará la adjudicación de uno o varios lotes, a la circunstancia de resultar\nadjudicatario de todos o de varios de ellos. En todo caso, cada lote constituirá un\ncontrato.\nLos lotes en que se divide el objeto de este contrato, con indicación de la codificación\nde la nomenclatura de Clasificación de Productos por Actividades (CPA) y del\nVocabulario Común de Contratos (CPV) de la Comisión Europea, son los siguientes:\nCodificación Codificación\nLote Denominación\nCPA CPV\nReconocimiento médico laboral con especial\n1 86.21.10 85121100\natención al aparato musculoesquelético\n2 Reconocimiento médico otorrinolaringológico 86.22.1 85121240\n3 Reconocimiento médico ginecológico 86.22.1 85121210\n4 Reconocimiento médico urológico 86.22.1 85121292\nCalle Pinar de Valsaín, nª 1\nPágina 3 de 65 buzon.inss-segovia.licitaciones@seg-social.es 40005 - SEGOVIA\nTEL.: 921 41 44 52\nCódigo DIR3: EA00421821.3 En la definición del objeto del presente contrato se han tenido en cuenta las\nconsideraciones sociales, según lo previsto en el apartado 7.1 del Acuerdo del\nConsejo de Ministros de 12 de abril de 2019, por el que se aprueba el Plan para el\nimpulso de la contratación pública socialmente responsable en el marco de la Ley\n9/2017, de 8 de noviembre, de Contratos del Sector Público, publicado por Orden\nPCI/566/2019, de 21 de mayo.\nSEGUNDA. - NATURALEZA, RÉGIMEN JURÍDICO, DOCUMENTOS DE NATURALEZA\nCONTRACTUAL Y JURISDICCIÓN.\n2.1 El contrato al que se refiere el presente pliego tiene naturaleza administrativa,\ncalificándose de servicios, y se regirá, además de por lo establecido en el mismo, por\nlo dispuesto en la Ley 9/2017, de 8 de noviembre, de Contratos del Sector Público,\npor la que se transponen al ordenamiento jurídico español las Directivas del\nParlamento Europeo y del Consejo 2014/23/UE y 2014/24/UE, de 26 de febrero de\n2014 (en adelante LCSP); por el Real Decreto 817/2009, de 8 de mayo, por el que\nse desarrolla parcialmente la Ley 30/2007, de 30 de octubre, de Contratos del Sector\nPúblico, en todo lo que no se oponga a la citada ley; por el Reglamento General de\nla Ley de Contratos de las Administraciones Públicas, aprobado por Real Decreto\n1098/2001, de 12 de octubre (en adelante, RGLCAP), en todo lo que no se oponga\na ambos; por el resto de normas de desarrollo en vigor, concordantes y\ncomplementarias a aquélla, siempre que no se opongan a las normas citadas; y,\nsupletoriamente, por las restantes normas vigentes de derecho administrativo, y en\nsu defecto, de derecho privado.\n2.2 El licitador acepta de forma expresa su sumisión a la legislación anteriormente citada,\na los pliegos de cláusulas administrativas generales que, en su caso, sean aplicables,\ny al presente pliego de cláusulas administrativas particulares y de prescripciones\ntécnicas que rige este contrato.\n2.3 La ejecución de este contrato se ajustará, además de a las previsiones contenidas\nen el presente pliego y en el documento de formalización que se suscriba, a las\ncondiciones expresadas en el Pliego de prescripciones técnicas que se acompaña\ncomo anexo a éste, y del que forma parte inseparable, y en todo lo que no se oponga\na ambos, a la proposición que formule el licitador que finalmente resulte adjudicatario;\nestableciéndose, salvo caso de error material o manifiesto, la siguiente prelación en\nel supuesto de que surjan contradicciones de contenido entre los diversos\ndocumentos referidos:\na) Pliego de prescripciones técnicas (PPT).\nb) Pliego de cláusulas administrativas particulares (PCAP).\nc) Contrato a suscribir.\nd) Proposición formulada por el licitador.\nCalle Pinar de Valsaín, nª 1\nPágina 4 de 65 buzon.inss-segovia.licitaciones@seg-social.es 40005 - SEGOVIA\nTEL.: 921 41 44 52\nCódigo DIR3: EA0042182En relación con esta última, se dará asimismo preferencia, en caso de discrepancia,\na la cuantía expresada en letra, siempre que no existan importes unitarios que reflejar\ncomo precios ciertos del contrato, en cuyo caso éstos se entenderán siempre\nprevalentes e invariables.\n2.4 Las cuestiones litigiosas surgidas sobre la interpretación, modificación, efectos y\nresolución de este contrato, serán resueltas por el órgano de contratación. El orden\njurisdiccional contencioso administrativo será el competente para resolver las\ncontroversias que surjan entre las partes, de conformidad con lo establecido en el\nartículo 27 de la LCSP.\nAtendiendo al valor estimado de este contrato, no cabe la interposición de recurso\nespecial en materia de contratación.\n2.5 El expediente que ampara la presente contratación es de tramitación ordinaria, de\nconformidad con lo previsto en el artículo 116 de la LCSP.\nLos plazos establecidos por días en este pliego se entenderán referidos a días\nnaturales, salvo que en el mismo se indique expresamente que solo deben\ncomputarse los días hábiles. No obstante, si el último día del plazo fuera inhábil, éste\nse entenderá prorrogado al primer día hábil siguiente, de conformidad con la\nDisposición Adicional 12ª de la LCSP.\nTERCERA. - PRESUPUESTO BASE DE LICITACIÓN Y VALOR ESTIMADO DEL CONTRATO.\n3.1 El presupuesto base de licitación de este contrato asciende a la cuantía total de\nquince mil novecientos setenta y cinco euros (15.975,00 €), IVA exento, resultando\nde aplicación el detalle que a continuación se refleja a efectos de su determinación:\n➢ Presupuesto del contrato (IVA exento): 15.975,00 €\nLa prestación de este servicio está exenta de tributación del IVA, según se\nestablece en el artículo 20 de la Ley 37/1992, de 28 de diciembre, del IVA.\nPor otra parte, el presupuesto base de licitación de cada lote es el siguiente:\nImporte N.º máx. Importe\nLote Denominación IVA\nunitario previsto total\nReconocimiento médico laboral con especial\n1 70,00 € exento 72 5.040,00 €\natención al aparato musculoesquelético\n2 Reconocimiento médico otorrinolaringológico 60,00 € exento 66 3.960,00 €\n3 Reconocimiento médico ginecológico 120,00 € exento 45 5.400,00 €\n4 Reconocimiento médico urológico 75,00 € exento 21 1.575,00 €\nTotal 15.975,00 €\nCalle Pinar de Valsaín, nª 1\nPágina 5 de 65 buzon.inss-segovia.licitaciones@seg-social.es 40005 - SEGOVIA\nTEL.: 921 41 44 52\nCódigo DIR3: EA0042182De acuerdo con lo dispuesto en el artículo 100.2 de la LCSP, el citado presupuesto\nbase de licitación se ha determinado conforme al siguiente desglose de costes\ndirectos e indirectos:\nEn el presente contrato se ha estimado un 15% de costes indirectos teniendo en\ncuenta las peculiaridades de las empresas que prestan el servicio a contratar,\nencuadradas dentro del ámbito sanitario y de la prevención de riesgos laborales, que\npor razón de su actividad y de la naturaleza del servicio prestado necesitan unas\ninfraestructuras y un personal de administración que influyen en sus costes, como\nson sus propias oficinas, las dependencias de atención al público, el equipamiento e\ninstalaciones de tipo sanitario, el equipamiento informático, software y acceso a\ntelecomunicaciones, entre otros, así como los costes indirectos del personal\nadministrativo, comercial y gerencial de'

In [95]:
stopwords_licitaciones = [
    "articulo",
    "artículos",
    "contratacion",
    "contratación",
    "procedimiento",
    "licitacion",
    "licitación",
    "licitador",
    "licitadores",
    "empresa",
    "empresas",
    "documentacion",
    "documentación",
    "pliego",
    "administrativo",
    "expediente",
    "lcsp",
    "contrato",
    "contratos",
    "servicio",
    "servicios",
    "caso",
    "datos",
    "objeto",
    "oferta",
    "parte",
    "partes"
]

In [96]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=100,
    stop_words=stopwords_licitaciones
)

X = vectorizer.fit_transform(
    dataset["texto"]
)

palabras = vectorizer.get_feature_names_out()

print(palabras)

['10' 'acuerdo' 'adjudicación' 'adjudicataria' 'adjudicatario'
 'administrativas' 'al' 'anexo' 'apartado' 'aplicación' 'artículo'
 'asistencia' 'así' 'cada' 'castilla' 'centro' 'cid' 'cláusulas' 'como'
 'con' 'condiciones' 'contratista' 'correspondiente' 'criterios'
 'cualquier' 'cuando' 'cumplimiento' 'de' 'deberá' 'deberán' 'del'
 'dirección' 'económica' 'ed' 'ejecución' 'el' 'en' 'entre' 'es' 'esta'
 'este' 'fecha' 'forma' 'fremap' 'general' 'importe' 'información' 'la'
 'las' 'ley' 'león' 'lo' 'los' 'lote' 'mediante' 'mismo' 'modelo' 'mutua'
 'médico' 'no' 'nº' 'nóicacifirev' 'número' 'ofertas' 'para' 'personal'
 'plazo' 'podrá' 'por' 'precio' 'presente' 'prestación' 'puntos' 'página'
 'que' 'realización' 'regional' 'responsable' 'salud' 'sanitaria' 'se'
 'segovia' 'seguridad' 'según' 'ser' 'será' 'si' 'siguiente' 'siguientes'
 'sin' 'sobre' 'social' 'su' 'todo' 'total' 'tratamiento' 'un' 'una' 'vsc'
 'órgano']

In [97]:
import re

for i in range(len(texto_pliegos)):

    texto = texto_pliegos.iloc[i]["texto"]

    cpvs = re.findall(
        r"\d{8}-\d",
        texto
    )

    print(
        texto_pliegos.iloc[i]["expediente"],
        cpvs[:10]
    )

07_INSS_Reconocimientos_Medicos_2025 []
10_INSS_Reconocimientos_Medicos_2023 []
11_TGSS_Reconocimientos_Medicos_2023 []
12_SACYL_Ecografias_Segovia_2023 ['85121200-5']
13_FREMAP_RMN_Avila_Burgos_Salamanca_Segovia_2023 []
14_UMIVALE_Asistencia_Ambulatoria_Segovia_2023 []
15_FREMAP_Asistencia_Sanitaria_Especializada_CyL_Cantabria_2023 ['85100000-0', '85100000-0', '85100000-0', '85100000-0', '85100000-0', '85100000-0', '85100000-0', '85100000-0']
16_TGSS_Reconocimientos_Medicos_2024 []
17_FREMAP_Electromiografias_Segovia_2024 ['85121200-5']
18_SACYL_Procedimientos_Quirurgicos_Diagnosticos_Segovia_2024 ['85111100-1', '85121200-5']
20_SACYL_Procedimientos_Diagnosticos_Ecografias_Imagen_Segovia_2025 ['85121200-5']
22_TGSS_Reconocimientos_Medicos_2025 []
23_FREMAP_Pruebas_Diagnosticas_CyL_2024_2025 []

In [98]:
def buscar_importes(texto):

    patron = r"\d{1,3}(?:\.\d{3})*(?:,\d+)?\s*€"

    return re.findall(
        patron,
        str(texto)
    )

In [99]:
for i in range(3):

    texto = texto_pliegos.iloc[i]["texto"]

    print(
        texto_pliegos.iloc[i]["expediente"]
    )

    print(
        buscar_importes(texto)[:10]
    )

    print("-"*50)

07_INSS_Reconocimientos_Medicos_2025
['15.975,00 €', '15.975,00 €', '70,00 €', '5.040,00 €', '60,00 €', '3.960,00 €', '120,00 €', '5.400,00 €', '75,00 €', '1.575,00 €']
--------------------------------------------------
10_INSS_Reconocimientos_Medicos_2023
['15.005,00 €', '50,00 €']
--------------------------------------------------
11_TGSS_Reconocimientos_Medicos_2023
[]
--------------------------------------------------

In [100]:
def buscar_meses(texto):

    return re.findall(
        r"(\d+)\s*meses",
        str(texto).lower()
    )

In [101]:
criterios = [
    "criterios de adjudicación",
    "criterios evaluables",
    "juicio de valor",
    "precio",
    "oferta económica"
]

for criterio in criterios:

    dataset[criterio] = (
        dataset["texto"]
        .str.lower()
        .str.contains(
            criterio,
            na=False
        )
        .astype(int)
    )

In [102]:
# CPVs
for i in range(3):
    print(re.findall(r"\d{8}-\d",
                     texto_pliegos.iloc[i]["texto"])[:10])

[]
[]
[]

In [103]:
# Importes
for i in range(3):
    print(buscar_importes(
        texto_pliegos.iloc[i]["texto"]
    )[:10])

['15.975,00 €', '15.975,00 €', '70,00 €', '5.040,00 €', '60,00 €', '3.960,00 €', '120,00 €', '5.400,00 €', '75,00 €', '1.575,00 €']
['15.005,00 €', '50,00 €']
[]

In [104]:
# Meses
for i in range(3):
    print(buscar_meses(
        texto_pliegos.iloc[i]["texto"]
    )[:10])

[]
[]
[]

In [106]:
dataset = texto_pliegos.copy()

In [107]:
import re

def cpv_principal(texto):

    cpvs = re.findall(
        r"\d{8}-\d",
        str(texto)
    )

    if len(cpvs) > 0:
        return cpvs[0]

    return None

In [108]:
dataset["cpv_principal"] = (
    dataset["texto"]
    .apply(cpv_principal)
)

In [109]:
def contar_cpvs(texto):

    return len(
        re.findall(
            r"\d{8}-\d",
            str(texto)
        )
    )

In [110]:
dataset["num_cpvs"] = (
    dataset["texto"]
    .apply(contar_cpvs)
)

In [111]:
requisitos = [
    "solvencia",
    "experiencia",
    "iso 9001",
    "iso 14001",
    "prevencion",
    "radiologia",
    "ecografia",
    "resonancia",
    "electromiografia",
    "fisioterapia",
    "personal sanitario"
]

In [112]:
for r in requisitos:

    dataset[r] = (
        dataset["texto"]
        .str.lower()
        .str.contains(
            r,
            na=False
        )
        .astype(int)
    )

In [113]:
criterios = [
    "criterios de adjudicación",
    "oferta económica",
    "juicio de valor",
    "precio"
]

In [114]:
for c in criterios:

    dataset[c] = (
        dataset["texto"]
        .str.lower()
        .str.contains(
            c,
            na=False
        )
        .astype(int)
    )

In [115]:
from sentence_transformers import SentenceTransformer

modelo = SentenceTransformer(
    "paraphrase-multilingual-MiniLM-L12-v2"
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [116]:
embeddings = modelo.encode(
    dataset["texto"].tolist(),
    show_progress_bar=True
)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [117]:
from sklearn.metrics.pairwise import cosine_similarity

sim = cosine_similarity(
    embeddings
)

In [118]:
sim_df = pd.DataFrame(
    sim,
    index=dataset["expediente"],
    columns=dataset["expediente"]
)

In [119]:
sim_df

expediente,07_INSS_Reconocimientos_Medicos_2025,10_INSS_Reconocimientos_Medicos_2023,11_TGSS_Reconocimientos_Medicos_2023,12_SACYL_Ecografias_Segovia_2023,13_FREMAP_RMN_Avila_Burgos_Salamanca_Segovia_2023,14_UMIVALE_Asistencia_Ambulatoria_Segovia_2023,15_FREMAP_Asistencia_Sanitaria_Especializada_CyL_Cantabria_2023,16_TGSS_Reconocimientos_Medicos_2024,17_FREMAP_Electromiografias_Segovia_2024,18_SACYL_Procedimientos_Quirurgicos_Diagnosticos_Segovia_2024,20_SACYL_Procedimientos_Diagnosticos_Ecografias_Imagen_Segovia_2025,22_TGSS_Reconocimientos_Medicos_2025,23_FREMAP_Pruebas_Diagnosticas_CyL_2024_2025
expediente,,,,,,,,,,,,,
07_INSS_Reconocimientos_Medicos_2025,1.000000,0.869386,0.583198,0.460686,0.573936,0.328381,0.469651,0.518873,0.357519,0.481513,0.442569,0.646959,0.446408
10_INSS_Reconocimientos_Medicos_2023,0.869386,1.000000,0.831088,0.618787,0.724474,0.511398,0.613857,0.751567,0.535365,0.635815,0.580734,0.812618,0.641729
11_TGSS_Reconocimientos_Medicos_2023,0.583198,0.831088,1.000000,0.735313,0.743317,0.668414,0.708176,0.864191,0.591913,0.780828,0.701945,0.875159,0.787858
12_SACYL_Ecografias_Segovia_2023,0.460686,0.618787,0.735313,1.000000,0.640623,0.542817,0.684772,0.717046,0.420956,0.917993,0.925828,0.694182,0.719238
13_FREMAP_RMN_Avila_Burgos_Salamanca_Segovia_2023,0.573936,0.724474,0.743317,0.640623,1.000000,0.582893,0.611915,0.672675,0.583069,0.680276,0.643030,0.685629,0.704584
14_UMIVALE_Asistencia_Ambulatoria_Segovia_2023,0.328381,0.511398,0.668414,0.542817,0.582893,1.000000,0.719327,0.715959,0.619649,0.603065,0.459742,0.696933,0.713593
15_FREMAP_Asistencia_Sanitaria_Especializada_CyL_Cantabria_2023,0.469651,0.613857,0.708176,0.684772,0.611915,0.719327,1.000000,0.765049,0.517852,0.728880,0.611078,0.710845,0.728981
16_TGSS_Reconocimientos_Medicos_2024,0.518873,0.751567,0.864191,0.717046,0.672675,0.715959,0.765049,1.000000,0.514154,0.760881,0.661616,0.888239,0.823876
17_FREMAP_Electromiografias_Segovia_2024,0.357519,0.535365,0.591913,0.420956,0.583069,0.619649,0.517852,0.514154,1.000000,0.434393,0.399201,0.509654,0.526589
18_SACYL_Procedimientos_Quirurgicos_Diagnosticos_Segovia_2024,0.481513,0.635815,0.780828,0.917993,0.680276,0.603065,0.728880,0.760881,0.434393,1.000000,0.889442,0.753230,0.752310
20_SACYL_Procedimientos_Diagnosticos_Ecografias_Imagen_Segovia_2025,0.442569,0.580734,0.701945,0.925828,0.643030,0.459742,0.611078,0.661616,0.399201,0.889442,1.000000,0.641113,0.673241
22_TGSS_Reconocimientos_Medicos_2025,0.646959,0.812618,0.875159,0.694182,0.685629,0.696933,0.710845,0.888239,0.509654,0.753230,0.641113,1.000000,0.783758
23_FREMAP_Pruebas_Diagnosticas_CyL_2024_2025,0.446408,0.641729,0.787858,0.719238,0.704584,0.713593,0.728981,0.823876,0.526589,0.752310,0.673241,0.783758,1.000000

In [120]:
dataset[
    [
        "expediente",
        "cpv_principal",
        "num_cpvs"
    ]
]

                                           expediente cpv_principal  num_cpvs
0                07_INSS_Reconocimientos_Medicos_2025          None         0
1                10_INSS_Reconocimientos_Medicos_2023          None         0
2                11_TGSS_Reconocimientos_Medicos_2023          None         0
3                    12_SACYL_Ecografias_Segovia_2023    85121200-5         1
4   13_FREMAP_RMN_Avila_Burgos_Salamanca_Segovia_2023          None         0
5      14_UMIVALE_Asistencia_Ambulatoria_Segovia_2023          None         0
6   15_FREMAP_Asistencia_Sanitaria_Especializada_C...    85100000-0         8
7                16_TGSS_Reconocimientos_Medicos_2024          None         0
8            17_FREMAP_Electromiografias_Segovia_2024    85121200-5         1
9   18_SACYL_Procedimientos_Quirurgicos_Diagnostic...    85111100-1         2
10  20_SACYL_Procedimientos_Diagnosticos_Ecografia...    85121200-5         1
11               22_TGSS_Reconocimientos_Medicos_2025          None         0
12       23_FREMAP_Pruebas_Diagnosticas_CyL_2024_2025          None         0

In [121]:
dataset[
    [
        "expediente",
        "solvencia",
        "experiencia",
        "radiologia",
        "ecografia",
        "resonancia",
        "electromiografia"
    ]
]

,expediente,solvencia,experiencia,radiologia,ecografia,resonancia,electromiografia
0,07_INSS_Reconocimientos_Medicos_2025,1,0,0,0,0,0
1,10_INSS_Reconocimientos_Medicos_2023,1,0,0,0,0,0
2,11_TGSS_Reconocimientos_Medicos_2023,0,0,0,0,0,0
3,12_SACYL_Ecografias_Segovia_2023,1,1,0,0,1,0
4,13_FREMAP_RMN_Avila_Burgos_Salamanca_Segovia_2023,0,0,0,0,1,0
5,14_UMIVALE_Asistencia_Ambulatoria_Segovia_2023,1,1,0,0,0,0
6,15_FREMAP_Asistencia_Sanitaria_Especializada_C...,1,1,0,0,0,0
7,16_TGSS_Reconocimientos_Medicos_2024,1,1,0,0,0,0
8,17_FREMAP_Electromiografias_Segovia_2024,1,0,0,0,0,0
9,18_SACYL_Procedimientos_Quirurgicos_Diagnostic...,1,1,0,0,1,0
10,20_SACYL_Procedimientos_Diagnosticos_Ecografia...,1,1,0,1,1,0
11,22_TGSS_Reconocimientos_Medicos_2025,1,1,0,0,0,0
12,23_FREMAP_Pruebas_Diagnosticas_CyL_2024_2025,0,0,0,0,0,0

In [122]:
for i in range(len(texto_pliegos)):

    texto = texto_pliegos.iloc[i]["texto"].lower()

    if "criterios de adjudicación" in texto:

        print("="*100)
        print(texto_pliegos.iloc[i]["expediente"])
        pos = texto.find("criterios de adjudicación")

        print(texto[pos:pos+3000])

====================================================================================================
07_INSS_Reconocimientos_Medicos_2025
criterios de adjudicación
v. capacidad para contratar
vi. presentación de proposiciones
vii. plazo de admisión y examen de proposiciones por los órganos
competentes
viii. adjudicación del contrato y garantía definitiva
ix. formalización del contrato
x. plazo de ejecución del contrato
xi. condiciones de ejecución y recepción
xii. pago del precio y plazo de garantía
xiii. obligaciones del contratista
xiv. penalidades
xv. revisión de precios
xvi. modificación, cesión y subcontratación del contrato
xvii. resolución del contrato
xviii. protección de datos de carácter personal
documento n.º 1 declaración y oferta
documento n.º 2 declaración art. 71 lcsp
calle pinar de valsaín, nª 1
página 2 de 65 buzon.inss-segovia.licitaciones@seg-social.es 40005 - segovia
tel.: 921 41 44 52
código dir3: ea0042182servicios /procedimiento abierto simplificado art. 159.6 lcsp/ licitación
electrónica/
pliego de cláusulas administrativas particulares que ha de regir la
contratación, por procedimiento abierto simplificado previsto en el
artículo 159.6 de la lcsp, de los servicios de reconocimiento médico-
laboral general y reconocimientos médicos de otorrinolaringología,
ginecología y urología para el personal que presta servicios en la
dirección provincial del instituto nacional de la seguridad social de
segovia; expediente n.º: 40/vc-184/25. periodo 15/07/2025 a 30/06/2026
primera. - objeto del contrato.
1.1 el contrato al que se refiere el presente pliego tiene por objeto la ejecución de los
servicios de reconocimiento médico-laboral general y reconocimientos médicos de
otorrinolaringología, ginecología y urología para el personal que presta servicios en
la dirección provincial del instituto nacional de la seguridad social de segovia, que
se describen en el pliego de prescripciones técnicas que se acompaña, en el que se
han tenido en cuenta para su definición las consideraciones sociales, ambientales y
de innovación.
la necesidad e idoneidad del objeto descrito se acredita en el expediente
administrativo tramitado al efecto, quedando constancia en el mismo de que el
instituto nacional de la seguridad social (en adelante, inss) carece de medios
propios para ejecutar la prestación que se contrata.
1.2 el objeto del presente expediente está dividido en lotes, conforme se deduce del
pliego de prescripciones técnicas que se adjunta y conforme al número y
denominación que más abajo figura, pudiendo el licitador ofertar por uno o varios de
dichos lotes, siempre que resulten completos. de igual forma, en ningún caso se
condicionará la adjudicación de uno o varios lotes, a la circunstancia de resultar
adjudicatario de todos o de varios de ellos. en todo caso, cada lote constituirá un
contrato.
los lotes en que se divide el objeto de este contrato, con indicación de la codificación
de la nomenclatura de clasificación de productos por actividades (cpa) y del
vocabulario común de contratos (cpv) de la comisión europea, son los siguientes:
codificación codificación
lote denominación
====================================================================================================
10_INSS_Reconocimientos_Medicos_2023
criterios de adjudicación
v. capacidad para contratar
vi. presentación de proposiciones
vii. plazo de admisión y examen de proposiciones por los órganos
competentes
viii. adjudicación del contrato y garantía definitiva
ix. formalización del contrato
x. plazo de ejecución del contrato
xi. condiciones de ejecución y recepción
xii. pago del precio y plazo de garantía
xiii. obligaciones del contratista
xiv. penalidades
xv. revisión de precios
xvi. modificación, cesión y subcontratación del contrato
xvii. resolución del contrato
xviii. protección de datos de carácter personal
documento nº 1 declaración y oferta
documento nº 2 declaración art. 71 lcsp
ministerio
de inclusión, seguridad social
y migraciones
-2-
instituto nacional
de la seguridad socialservicios /procedimiento abierto simplificado art. 159.6 lcsp/ licitación
electrónica
pliego de cláusulas administrativas particulares que ha de regir la
contratación, por procedimiento abierto simplificado previsto en el
artículo 159.6 de la lcsp, de los servicios del reconocimiento medico-
laboral general y reconocimientos medicos de otorrinolaringologia,
ginecologia y urologia para la personal que presta servicios en la
direccion provincial del inss de segovia; expediente nº: 40/vc-224/23.
primera.- objeto del contrato.
1.1 el contrato al que se refiere el presente pliego tiene por objeto la ejecución de los
servicios de reconocimiento médico laboral con especial atención al aparato
musculoesquelético y los reconocimientos médicos otorrinolaringológico,
ginecológico y urológico de los empleados/as de la dirección provincial del instituto
nacional de la seguridad social en segovia, durante el periodo de 01-06- 2023 hasta
el 31-05-2024, que se describen en el liego de prescripciones técnicas que se
acompaña, en el que se han tenido en cuenta para su definición las consideraciones
sociales, ambientales y de innovación.
la necesidad e idoneidad del objeto descrito se acredita en el expediente
administrativo tramitado al efecto, quedando constancia en el mismo de que el
instituto nacional de la seguridad social (en adelante, inss) carece de medios
propios para ejecutar la prestación que se contrata.
1.2 el objeto del presente expediente está dividido en lotes, conforme se deduce del
pliego de prescripciones técnicas que se adjunta y conforme al número y
denominación que más bajo figura, pudiendo el licitador ofertar por uno o varios de
dichos lotes, siempre que resulten completos. de igual forma, en ningún caso se
condicionará la adjudicación de uno o varios lotes, a la circunstancia de resultar
adjudicatario de todos o de varios de ellos. en todo caso, cada lote constituirá un
contrato.
los lotes en que se divide el objeto de este contrato, con indicación de la codificación
de la nomenclatura de clasificación de productos por actividades (cpa) y del
vocabulario común de contratos (cpv) de la comisión europea, son los siguientes:
codificación codificación
lote denominación
cpa cpv
reconocimiento médico labor
====================================================================================================
12_SACYL_Ecografias_Segovia_2023
criterios de adjudicación evaluables mediante aplicación de fórmulas
se presentarán los documentos que permitan valorar la proposición de acuerdo con los
criterios de adjudicación evaluables mediante la mera aplicación de fórmulas y que
están indicados en el apartado 15.1.2 del cuadro de características de este pliego. a
los efectos de valoración de la documentación aportada por el licitador, se deberán
presentar los documentos firmados.
en el caso de que se establezcan modelos de documentos para la presentación de la
oferta de estos criterios, los mismos se formularán de forma ajustada a los citados
modelos.
d) unión temporal de empresas.
en caso de que la oferta se presentara por una unión temporal de empresarios, a la
declaración responsable se deberá acompañar el compromiso de constitución de dicha
unión temporal de empresas.
e) otros documentos complementarios.
además de la aportación de los documentos reseñados anteriormente, será requisito
indispensable para licitar, la presentación de los documentos específicos que se
relacionen, en su caso, en el apartado 20.1 del cuadro de características.
f) documentación técnica exigida en el pliego de prescripciones técnicas de la
licitación.
pliego modelo de servicios – procedimiento abierto simplificado 14/58gerencia regional de salud
2.5.1.2- procedimiento con criterios que dependen de juicio de
valor y criterios evaluables mediante fórmulas.
- se presentarán dos sobres o archivos electrónicos:
 sobre de criterios que dependen de un juicio de valor, hasta
un máximo del 25 % o del 45% si fueran prestaciones de carácter intelectual.
 sobre de criterios evaluables mediante la mera aplicación
de fórmulas.
- en el sobre de “criterios que dependen de un juicio de valor” se incluirá la
siguiente documentación:
a) declaración responsable, según modelo del anexo 1 de este pliego.
-cuando el pliego prevea la división en lotes del objeto del contrato, si los requisitos de
solvencia económica y financiera o técnica y profesional exigidos variaran de un lote a
otro, se aportará una declaración responsable por cada lote o grupo de lotes al que se
apliquen los mismos requisitos de solvencia.
-si se hubiera presentado la solicitud de inscripción en el rolece o registro
autonómico, debe aportar junto con la declaración la siguiente documentación:
- acuse de recibo de la solicitud de inscripción emitido por el correspondiente
registro, y
- declaración responsable de haber aportado la documentación preceptiva y de no
haber recibido requerimiento de subsanación.
b) los documentos que permitan valorar la proposición de acuerdo con los criterios
de adjudicación que dependen de un juicio de valor y que están indicados en el
apartado 15.1.1 del cuadro de características de este pliego. a los efectos de
valoración de la documentación aportada por el licitador, se deberán presentar los
documentos firmados.
c) cualquier otra documentación técnica que se exija en el pliego de prescripciones
técnicas.
d) unión temporal de e
====================================================================================================
14_UMIVALE_Asistencia_Ambulatoria_Segovia_2023
criterios de adjudicación:
las ofertas de las empresas licitadoras serán valoradas hasta con un máximo de 100 puntos,
aplicando los criterios que se indican a continuación por orden decreciente de importancia:
i. oferta económica. 40
i.1. oferta económica 40
ii. oferta técnica cualitativa evaluable automáticamente. 60
ii.1 características de las instalaciones, medios materiales y humanos 10
superficie de las instalaciones destinada a la actividad objeto de la
ii.1.1 3
licitación
ii.1.2 personal destinado a la actividad objeto de la licitación 3
ii.1.3 existencia de aparcamiento sanitario exclusivo identificado 1
ii.1.4 facilidad de acceso al centro concertado 3
ii.2 calidad del servicio 32
ii.2.1 plan de sustitución de profesionales ante contingencias 1
ii.2.2 tiempos máximos para gestionar 1ª cita del paciente 4
ii.2.3 sistema de comunicación con el paciente 3
ii.2.4 sistema de registro de las asistencias o servicios 3
ii.2.5 tiempos máximos para ser atendido en consulta 3
ii.2.6 plazo de entregar a umivale activa, del informe de la consulta 12
ii.2.7 sistema de gestión de quejas y reclamaciones 3
ii.2.8 encuestas de satisfacción del paciente 3
ii.3 mejoras 18
ii.3.1 ampliación del horario de atención asistencial mínimo 5 ampliación del horario de atención asistencial en sábados o
ii.3.2 4 domingos y festivos
ii.3.3 existencia de consultas de otros especialistas 9
i. oferta económica. • en el fichero excel adjunto como oferta económica y servicios a contratar el licitador deberá facilitar obligatoriamente el precio unitario de todos los servicios,
exp. nº ser-23-0584-osa 9/16
firmado por: emilio navarro alventosa
cargo: mce
fecha: 23-11-2023 14:50:46
este documento es copia auténtica según el artículo 30.5 de la ley 11/2007, de 22 de junio. su autenticidad puede ser comprobada en la dirección
https://contratacion.umivale.es/licitacion/verificadorcopiaautentica.do
56
ed
9
:anigáp
29c5d9883b146d6b=noicacif
n ir ó e i v cc o e g r id id
o e c? tn
o e d iu .a
g c is it n a e l t a u
a e a s i r p a o tc c e r n o o d c a
c á i r f d ir
o e p v/
n o
o g
i i c d a ó t c ic
e il/ t s n e e . i e u
l g a i v s i m le
u d
. n n
o ó
i i c c a a
t c a if r i t r n e o v c a // l : s a p ra tt p h
29c5d9883b146d6b
:
nóicacifirev
ed
ogidócpliegos cláusulas particulares
19. criterios de adjudicación:
especialidades y pruebas que vayan a ser objeto del contrato y que se encuentran,
a su vez, recogidos en el pliego de prescripciones técnicas
• los precios unitarios ofertados no podrán ser superiores a los precios unitarios máximos
establecidos.
• el importe a valorar será el “importe total anual ofertado sin iva” resultado de los
datos cumplimentados en el fichero excel adjunto como anexo ii oferta económica y
servicios a contratar
• cada uno de los licitadores podrá mejorar a la baja el importe máximo anual. se valorará
con la mayor puntuación a la oferta económica más baja. la valoración del resto de las
ofertas económicas será conforme a la siguiente fórmula
====================================================================================================
15_FREMAP_Asistencia_Sanitaria_Especializada_CyL_Cantabria_2023
criterios de adjudicación
la información y, en su caso, documentación técnica referida a los criterios no cuantificables
mediante la mera aplicación de fórmulas, así como a los criterios cuantificables mediante la mera
aplicación de fórmulas se registrará en cada uno de los apartados correspondientes de la
pliego de cláusulas administrativas página 17 de 126lict/99/139/2022/0206 - contratación del servicio de asistencia sanitaria especializada en las comunidades
autónomas de castilla y león y cantabria para fremap, mutua colaboradora con la seguridad social nº 61.
presentación electrónica de ofertas a través del plef, en los términos, condiciones y alcance
indicados en la misma, así como en el anexo de condiciones particulares del presente pliego.
a estos efectos se recuerda a los licitadores que la mezcla de información o en su caso
documentación referida a los criterios mencionados en el párrafo anterior, supondrá los efectos
establecidos en la normativa de contratación pública.
4.4 examen de las proposiciones y propuesta de adjudicación
finalizado el plazo de presentación de proposiciones, fremap procederá a la apertura y calificación
de la información y, en su caso, de la documentación acreditativa del cumplimiento de los
requisitos previos presentada por los licitadores.
en el supuesto de apreciar defectos subsanables en la citada información y, en su caso,
documentación, esta mutua procederá a requerir a los licitadores para que los corrijan, a través
del plef, dentro del plazo establecido en la normativa de contratación pública, acordando la
exclusión de aquellos que no acrediten dicho cumplimento dentro del plazo establecido.
asimismo, fremap podrá recabar de los licitadores aclaraciones referidas a la información y, en su
caso, documentación presentada, o requerirles la presentación de información o documentación
adicional o complementaria a su propuesta.
posteriormente, fremap en aquellos procedimientos en los que así se establezca en la normativa
de contratación, procederá a la apertura, en actos públicos online, y posterior examen y valoración
del resto del contenido de las propuestas presentadas por los licitadores.
en el caso de los criterios no cuantificables mediante la mera aplicación de fórmulas, fremap
realizará la evaluación previa de los mismos, cuyo resultado hará público en el acto en el que se
proceda a la apertura del sobre que contenga los elementos de la oferta que se valorarán mediante
la mera aplicación de fórmulas, en aquellos procedimientos en los que así se establezca en la
normativa de contratación.
en el caso de los procedimientos con negociación, adicionalmente a lo expuesto, se estará a lo
dispuesto en el anexo de condiciones particulares.
las proposiciones presentadas se clasificarán, por orden decreciente, una vez ponderados los
criterios de adjudicación que deban aplicarse para efectuar la selección del adjudicatario y que se
detallan en el anexo de condiciones particulares.
en el caso de existencia de una o
====================================================================================================
16_TGSS_Reconocimientos_Medicos_2024
criterios de adjudicación de las ofertas ....................................................... 21
decimocuarta. - adjudicación del contrato y accesibilidad de las ofertas presentadas
y la valoración de las mismas ................................................................................................................. 24
decimoquinta. - garantías exigibles ................................................................................................. 25
decimosexta. - decisión de no adjudicar o celebrar el contrato y desistimiento del
procedimiento de adjudicación .............................................................................................................. 25
decimoseptima. - formalización del contrato ................................................................................ 26
decimooctava. - duración, ejecución, prórroga del contrato, cumplimiento, recepción
y liquidación ................................................................................................................................................. 27
decimonovena.- condiciones especiales de ejecución .............................................................. 28
vigesima.- presentación de las facturas y pago del precio .......................................................... 29
vigesimo primera. - obligaciones del contratista y reglas específicas respecto del
personal de la empresa contratista ....................................................................................................... 31
vigesimo segunda.- penalidades...................................................................................................... 37
vigesimo tercera.- revisión de precios ........................................................................................ 39ministerio
de inclusion, seguridad social
y migraciones tesorería general
de la seguridad social
direccion provincial de segovia
dir3: ea0042343
3
vigesimo cuarta.- modificación, cesión y subcontratación del contrato ............................. 39
vigesimo quinta .- resolución del contrato ................................................................................... 40
vigesimo sexta- comunicaciones y notificaciones por medios telemáticos ........................ 40
vigesimo septima. -prerrogativas de la administración, régimen de recursos y
jurisdicción competente ........................................................................................................................... 41
apéndice:
➢ relación de medios acreditativos de los requisitos de aptitud para contratar
modelos:
➢ documento 1 modelo de no consentimiento del interesado para que el órgano encargado de la
tramitación pueda comprobar los datos certificados a través de medios telemáticos
➢ documento 2 modelo de declaración responsable –artículo 159.4 lcsp
➢ documento 3 modelo de declaración responsable sobre empresas vinculadas a los efectos del artículo
86 del rglcap
➢ documento 4 modelo de oferta económi
====================================================================================================
17_FREMAP_Electromiografias_Segovia_2024
criterios de adjudicación
anexo xii desglose costes
mutua colaboradora con la seguridad social nº 151 página 2 de 37pliego de cláusulas administrativas particulares
servicio de pruebas de electromiografía (emg) en régimen ambulatorio, en el ámbito
territorial de segovia, para asepeyo, mutua colaboradora con la seguridad social nº
151
exp. sp00145-2024
0. cuadro de características
a.- poder adjudicador
a.1 órgano de contratación
subdirección general sanitaria (perfil de contratante)
b.- objeto del contrato
b.1 objeto
asistencia sanitaria para la realización de pruebas de electromiografía (emg), en régimen ambulatorio,
en el ámbito territorial de segovia, para asepeyo, mutua colaboradora con la seguridad social nº 151,
a fin de prestar asistencia sanitaria y recuperadora a los trabajadores al servicio de las empresas aso-
ciadas a asepeyo y a los trabajadores por cuenta propia adheridos a la misma para los cuales tenga la

In [123]:
for palabra in [
    "oferta económica",
    "juicio de valor",
    "criterios evaluables",
    "precio"
]:

    print("\n", palabra)

    for i in range(len(texto_pliegos)):

        texto = texto_pliegos.iloc[i]["texto"].lower()

        if palabra in texto:

            print(texto_pliegos.iloc[i]["expediente"])

 oferta económica
07_INSS_Reconocimientos_Medicos_2025
10_INSS_Reconocimientos_Medicos_2023
12_SACYL_Ecografias_Segovia_2023
14_UMIVALE_Asistencia_Ambulatoria_Segovia_2023
15_FREMAP_Asistencia_Sanitaria_Especializada_CyL_Cantabria_2023
16_TGSS_Reconocimientos_Medicos_2024
17_FREMAP_Electromiografias_Segovia_2024
18_SACYL_Procedimientos_Quirurgicos_Diagnosticos_Segovia_2024
20_SACYL_Procedimientos_Diagnosticos_Ecografias_Imagen_Segovia_2025
22_TGSS_Reconocimientos_Medicos_2025

 juicio de valor
12_SACYL_Ecografias_Segovia_2023
18_SACYL_Procedimientos_Quirurgicos_Diagnosticos_Segovia_2024
20_SACYL_Procedimientos_Diagnosticos_Ecografias_Imagen_Segovia_2025

 criterios evaluables
12_SACYL_Ecografias_Segovia_2023
14_UMIVALE_Asistencia_Ambulatoria_Segovia_2023
18_SACYL_Procedimientos_Quirurgicos_Diagnosticos_Segovia_2024
20_SACYL_Procedimientos_Diagnosticos_Ecografias_Imagen_Segovia_2025

 precio
07_INSS_Reconocimientos_Medicos_2025
10_INSS_Reconocimientos_Medicos_2023
11_TGSS_Reconocimientos_Medicos_2023
12_SACYL_Ecografias_Segovia_2023
13_FREMAP_RMN_Avila_Burgos_Salamanca_Segovia_2023
14_UMIVALE_Asistencia_Ambulatoria_Segovia_2023
15_FREMAP_Asistencia_Sanitaria_Especializada_CyL_Cantabria_2023
16_TGSS_Reconocimientos_Medicos_2024
17_FREMAP_Electromiografias_Segovia_2024
18_SACYL_Procedimientos_Quirurgicos_Diagnosticos_Segovia_2024
20_SACYL_Procedimientos_Diagnosticos_Ecografias_Imagen_Segovia_2025
22_TGSS_Reconocimientos_Medicos_2025

In [124]:
palabras = [
    "presupuesto base de licitación",
    "valor estimado",
    "importe de licitación",
    "presupuesto máximo"
]

for palabra in palabras:

    print("\n", palabra)

    for i in range(len(texto_pliegos)):

        texto = texto_pliegos.iloc[i]["texto"].lower()

        if palabra in texto:

            print(texto_pliegos.iloc[i]["expediente"])

 presupuesto base de licitación
07_INSS_Reconocimientos_Medicos_2025
10_INSS_Reconocimientos_Medicos_2023
12_SACYL_Ecografias_Segovia_2023
14_UMIVALE_Asistencia_Ambulatoria_Segovia_2023
16_TGSS_Reconocimientos_Medicos_2024
17_FREMAP_Electromiografias_Segovia_2024
18_SACYL_Procedimientos_Quirurgicos_Diagnosticos_Segovia_2024
20_SACYL_Procedimientos_Diagnosticos_Ecografias_Imagen_Segovia_2025
22_TGSS_Reconocimientos_Medicos_2025

 valor estimado
07_INSS_Reconocimientos_Medicos_2025
10_INSS_Reconocimientos_Medicos_2023
12_SACYL_Ecografias_Segovia_2023
14_UMIVALE_Asistencia_Ambulatoria_Segovia_2023
15_FREMAP_Asistencia_Sanitaria_Especializada_CyL_Cantabria_2023
16_TGSS_Reconocimientos_Medicos_2024
17_FREMAP_Electromiografias_Segovia_2024
18_SACYL_Procedimientos_Quirurgicos_Diagnosticos_Segovia_2024
20_SACYL_Procedimientos_Diagnosticos_Ecografias_Imagen_Segovia_2025
22_TGSS_Reconocimientos_Medicos_2025

 importe de licitación
12_SACYL_Ecografias_Segovia_2023

 presupuesto máximo
14_UMIVALE_Asistencia_Ambulatoria_Segovia_2023

In [125]:
resumen = resumen.copy()

resumen = resumen.rename(
    columns={
        "Carpeta":"expediente"
    }
)

In [126]:
dataset_final = dataset.merge(
    resumen,
    on="expediente",
    how="left"
)

In [127]:
dataset_final.shape
dataset_final.head()

,expediente,texto,cpv_principal,num_cpvs,solvencia,experiencia,iso 9001,iso 14001,prevencion,radiologia,...,criterios de adjudicación,oferta económica,juicio de valor,precio,Organismo,Año,Descripción de la licitación,Total docs,Formatos,Categorías presentes
0,07_INSS_Reconocimientos_Medicos_2025,PLIEGO SERVICIOS /PROC. ABIERTO SIMPLIFICADO A...,None,0,1,0,0,0,0,0,...,1,1,0,1,INSS,2025,Reconocimientos médicos personal INSS,21,"DOCX, PDF","Acta mesa contratación, Anuncio formalización,..."
1,10_INSS_Reconocimientos_Medicos_2023,"MINISTERIO\nDE INCLUSIÓN, SEGURIDAD SOCIAL\nY ...",None,0,1,0,0,0,0,0,...,1,1,0,1,INSS,2023,Reconocimientos médicos personal INSS,16,"DOCX, PDF","Anuncio formalización, Anuncio licitación, Can..."
2,11_TGSS_Reconocimientos_Medicos_2023,"MINISTERIO\nDE INCLUSIÓN, SEGURIDAD SOCIAL\nY ...",None,0,0,0,0,0,0,0,...,0,0,0,1,TGSS,2023,Reconocimientos médicos empleados TGSS/UPI/Int...,18,"DOCX, PDF","Anuncio formalización, Cancelación adjudicació..."
3,12_SACYL_Ecografias_Segovia_2023,Gerencia Regional de Salud\nPLIEGO MODELO DE C...,85121200-5,1,1,1,0,0,0,0,...,1,1,1,1,SACYL,2023,Procedimientos diagnósticos mediante ultrasoni...,18,PDF,"Acta mesa contratación, Anuncio formalización,..."
4,13_FREMAP_RMN_Avila_Burgos_Salamanca_Segovia_2023,PLIEGO DE CONDICIONES TÉCNICAS QUE HA DE REGIR...,None,0,0,0,0,0,0,0,...,0,0,0,1,FREMAP,2023,"Resonancias magnéticas en Ávila, Burgos, Salam...",26,"PDF, XLSX, XML","Anexo, Anexo LOPD, Anexo nomenclator, Anexo se..."

In [128]:
dataset_final["Organismo"].value_counts()

Organismo
FREMAP     4
SACYL      3
TGSS       3
INSS       2
UMIVALE    1
Name: count, dtype: int64

In [129]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

dataset_final["organismo_enc"] = (
    le.fit_transform(
        dataset_final["Organismo"]
    )
)

In [130]:
dataset_final["Año"]

0          2025
1          2023
2          2023
3          2023
4          2023
5          2023
6          2023
7          2024
8          2024
9          2024
10         2025
11         2025
12    2024-2025
Name: Año, dtype: object

In [131]:
dataset_final["Total docs"]

0     21
1     16
2     18
3     18
4     26
5     17
6      6
7     15
8     16
9     23
10    18
11    24
12    23
Name: Total docs, dtype: int64

In [132]:
emb_df = pd.DataFrame(
    embeddings,
    columns=[
        f"emb_{i}"
        for i in range(
            embeddings.shape[1]
        )
    ]
)

In [133]:
dataset_final = pd.concat(
    [
        dataset_final.reset_index(drop=True),
        emb_df.reset_index(drop=True)
    ],
    axis=1
)